using WowPacketParser.Misc;

namespace WowPacketParser.Enums.Version.V5_4_8_18414
{
    public static class Opcodes_5_4_8a
    {
        public static BiDictionary<Opcode, int> Opcodes(Direction direction)
        {
            if (direction == Direction.ClientToServer || direction == Direction.BNClientToServer)
                return ClientOpcodes;
            if (direction == Direction.ServerToClient || direction == Direction.BNServerToClient)
                return ServerOpcodes;
            return MiscOpcodes;
        }

        private static readonly BiDictionary<Opcode, int> ClientOpcodes = new BiDictionary<Opcode, int>
        {
        //                                                                    /checked in code
        //                                                                     /checked with sniff
            {Opcode.CMSG_ACCEPT_LEVEL_GRANT,                       0x02FB}, //+-
            {Opcode.CMSG_ACCEPT_TRADE,                             0x144D}, //++
            {Opcode.CMSG_ACTIVATE_TAXI,                            0x03C9}, //++
            {Opcode.CMSG_ACTIVATE_TAXI_EXPRESS,                    0x06FB}, //++
            {Opcode.CMSG_ADDON_REGISTERED_PREFIXES,                0x040E}, //++
            {Opcode.CMSG_ADD_FRIEND,                               0x09A6}, //+-
            {Opcode.CMSG_ADD_IGNORE,                               0x0D20}, //+-
            {Opcode.CMSG_ALTER_APPEARANCE,                         0x07F0}, //+-
            {Opcode.CMSG_AREA_SPIRIT_HEALER_QUERY,                 0x03F1}, //++
            {Opcode.CMSG_AREA_SPIRIT_HEALER_QUEUE,                 0x12D8}, //++
            {Opcode.CMSG_AREA_TRIGGER,                             0x1C44}, //++
            {Opcode.CMSG_ATTACK_STOP,                              0x0345}, //++
            {Opcode.CMSG_ATTACK_SWING,                             0x02E7}, //++
            {Opcode.CMSG_AUCTION_HELLO_REQUEST,                    0x0379}, //++
            {Opcode.CMSG_AUCTION_LIST_BIDDER_ITEMS,                0x12D0}, //++
            {Opcode.CMSG_AUCTION_LIST_ITEMS,                       0x02EA}, //++
            {Opcode.CMSG_AUCTION_LIST_OWNER_ITEMS,                 0x0361}, //++
            {Opcode.CMSG_AUCTION_PLACE_BID,                        0x03C8}, //++
            {Opcode.CMSG_AUCTION_REMOVE_ITEM,                      0x0259}, //+-
            {Opcode.CMSG_AUCTION_SELL_ITEM,                        0x02EB}, //+-
            {Opcode.CMSG_AUTH_CONTINUED_SESSION,                   0x0F49}, //+-
            {Opcode.CMSG_AUTH_SESSION,                             0x00B2}, //+-
            {Opcode.CMSG_AUTOBANK_ITEM,                            0x066D}, //++
            {Opcode.CMSG_AUTOSTORE_BANK_ITEM,                      0x02CF}, //++
            {Opcode.CMSG_AUTOSTORE_LOOT_ITEM,                      0x0354}, //++
            {Opcode.CMSG_AUTO_DECLINE_GUILD_INVITES,               0x06CB}, //++
            {Opcode.CMSG_AUTO_EQUIP_ITEM,                          0x025F}, //++
            {Opcode.CMSG_AUTO_STORE_BAG_ITEM,                      0x067C}, //+-
            {Opcode.CMSG_BANKER_ACTIVATE,                          0x02E9}, //+-
            {Opcode.CMSG_BATTLEFIELD_LEAVE,                        0x0257}, //+-
            {Opcode.CMSG_BATTLEFIELD_LIST,                         0x1C41}, //+-
            {Opcode.CMSG_BATTLEFIELD_PORT,                         0x1379}, //+-
            {Opcode.CMSG_BATTLEMASTER_JOIN,                        0x0769}, //+-
            {Opcode.CMSG_BATTLEMASTER_JOIN_ARENA,                  0x02D2}, //++
            {Opcode.CMSG_BATTLE_CHAR_BOOST,                        0x08E3}, //+-
            {Opcode.CMSG_BATTLE_PAY_START_PURCHASE,                0x1886}, //++
            {Opcode.CMSG_BATTLE_PET_DELETE_PET,                    0x18B6}, //+-
            {Opcode.CMSG_BATTLE_PET_INITIAL_UPDATE_RESPONSE,       0x1A07}, //+-
            {Opcode.CMSG_BATTLE_PET_MODIFY_NAME,                   0x1887}, //+-
            {Opcode.CMSG_BATTLE_PET_ROUND,                         0x17BA}, //++
            {Opcode.CMSG_BATTLE_PET_SET_BATTLE_SLOT,               0x0163}, //+-
            {Opcode.CMSG_BATTLE_PET_SET_FLAGS,                     0x17AC}, //+-
            {Opcode.CMSG_BATTLE_PET_SUMMON_COMPANION,              0x1896}, //+-
            {Opcode.CMSG_BEGIN_TRADE,                              0x1CE3}, //++
            {Opcode.CMSG_BF_MGR_ENTRY_INVITE_RESPONSE,             0x1806}, //+-
            {Opcode.CMSG_BF_MGR_QUEUE_EXIT_REQUEST,                0x08B3}, //+-
            {Opcode.CMSG_BF_MGR_QUEUE_INVITE_RESPONSE,             0x0A97}, //+-
            {Opcode.CMSG_BINDER_ACTIVATE,                          0x1248}, //+-
            {Opcode.CMSG_BLACK_MARKET_BID_ON_ITEM,                 0x12C8}, //++
            {Opcode.CMSG_BLACK_MARKET_OPEN,                        0x075A}, //++
            {Opcode.CMSG_BLACK_MARKET_REQUEST_ITEMS,               0x127A}, //++
            {Opcode.CMSG_BUY_BACK_ITEM,                            0x0661}, //+-
            {Opcode.CMSG_BUY_BANK_SLOT,                            0x12F2}, //+-
            {Opcode.CMSG_BUY_ITEM,                                 0x02E2}, //++
            {Opcode.CMSG_CALENDAR_ADD_EVENT,                       0x0A37}, //+-
            {Opcode.CMSG_CALENDAR_EVENT_INVITE,                    0x1D8E}, //--
            {Opcode.CMSG_CANCEL_AURA,                              0x1861}, //++
            {Opcode.CMSG_CANCEL_AUTO_REPEAT_SPELL,                 0x1272}, //+- hunter pet opcode
            {Opcode.CMSG_CANCEL_CAST,                              0x18C0}, //++
            {Opcode.CMSG_CANCEL_CHANNELLING,                       0x08C0}, //++
            {Opcode.CMSG_CANCEL_MOUNT_AURA,                        0x10E3}, //++
            {Opcode.CMSG_CANCEL_TEMP_ENCHANTMENT,                  0x024B}, //--
            {Opcode.CMSG_CANCEL_TRADE,                             0x1941}, //++
            {Opcode.CMSG_CAST_SPELL,                               0x0206}, //++
            {Opcode.CMSG_CHALLENGE_MODE_REQUEST_LEADERS,           0x15DB}, //++
            {Opcode.CMSG_CHANGE_SEATS_ON_CONTROLLED_VEHICLE,       0x08F8}, //+-
            {Opcode.CMSG_CHARACTER_RENAME_REQUEST,                 0x0963}, //+-
            {Opcode.CMSG_CHAR_CUSTOMIZE,                           0x0A13}, //+-
            {Opcode.CMSG_CHAR_DELETE,                              0x04E2}, //+-
            {Opcode.CMSG_CHAR_RACE_OR_FACTION_CHANGE,              0x0329}, //+-
            {Opcode.CMSG_CHAT_ADDON_MESSAGE_INSTANCE_CHAT,         0x08AF}, //++ addon
            {Opcode.CMSG_CHAT_ADDON_MESSAGE_GUILD,                 0x0E3B}, //++ addon
            {Opcode.CMSG_CHAT_ADDON_MESSAGE_PARTY,                 0x028E}, //++ addon
            {Opcode.CMSG_CHAT_ADDON_MESSAGE_WHISPER,               0x0EBB}, //++
            {Opcode.CMSG_CHAT_CHANNEL_ANNOUNCEMENTS,               0x06AF}, //--
            {Opcode.CMSG_CHAT_CHANNEL_BAN,                         0x08BF}, //--
            {Opcode.CMSG_CHAT_CHANNEL_INVITE,                      0x10AB}, //--
            {Opcode.CMSG_CHAT_CHANNEL_KICK,                        0x0E0B}, //--
            {Opcode.CMSG_CHAT_CHANNEL_LIST,                        0x0C1B}, //++
            {Opcode.CMSG_CHAT_CHANNEL_MODERATOR,                   0x00AE}, //--
            {Opcode.CMSG_CHAT_CHANNEL_MUTE,                        0x000A}, //--
            {Opcode.CMSG_CHAT_CHANNEL_OWNER,                       0x00AF}, //--
            {Opcode.CMSG_CHAT_CHANNEL_PASSWORD,                    0x0A1E}, //--
            {Opcode.CMSG_CHAT_CHANNEL_UNBAN,                       0x081F}, //--
            {Opcode.CMSG_CHAT_CHANNEL_UNMODERATOR,                 0x041E}, //--
            {Opcode.CMSG_CHAT_CHANNEL_UNMUTE,                      0x022A}, //--
            {Opcode.CMSG_CHAT_JOIN_CHANNEL,                        0x148E}, //++
            {Opcode.CMSG_CHAT_LEAVE_CHANNEL,                       0x042A}, //+-
            {Opcode.CMSG_CHAT_MESSAGE_AFK,                         0x0EAB}, //++
            {Opcode.CMSG_CHAT_MESSAGE_CHANNEL,                     0x00BB}, //+-
            {Opcode.CMSG_CHAT_MESSAGE_DND,                         0x002E}, //++
            {Opcode.CMSG_CHAT_MESSAGE_EMOTE,                       0x103E}, //+-
            {Opcode.CMSG_CHAT_MESSAGE_GUILD,                       0x0CAE}, //+-
            {Opcode.CMSG_CHAT_MESSAGE_OFFICER,                     0x0ABF}, //+-
            {Opcode.CMSG_CHAT_MESSAGE_PARTY,                       0x109A}, //++
            {Opcode.CMSG_CHAT_MESSAGE_RAID,                        0x083E}, //+-
            {Opcode.CMSG_CHAT_MESSAGE_RAID_WARNING,                0x16AB}, //++
            {Opcode.CMSG_CHAT_MESSAGE_SAY,                         0x0A9A}, //++
            {Opcode.CMSG_CHAT_MESSAGE_WHISPER,                     0x123E}, //++
            {Opcode.CMSG_CHAT_MESSAGE_YELL,                        0x04AA}, //+-
            {Opcode.CMSG_CHAT_REPORT_IGNORED,                      0x048A}, //+-
            {Opcode.CMSG_CHAT_UNREGISTER_ALL_ADDON_PREFIXES,       0x029F}, //++
            {Opcode.CMSG_CLEAR_RAID_MARKER,                        0x1443}, //+-
            {Opcode.CMSG_CLEAR_TRADE_ITEM,                         0x00A7}, //++
            {Opcode.CMSG_CLIENT_PORT_GRAVEYARD,                    0x12EA}, //+-
            {Opcode.CMSG_CONTACT_LIST,                             0x0BB4}, //+-
            {Opcode.CMSG_CORPSE_QUERY,                             0x1FBE}, //++
            {Opcode.CMSG_CREATE_CHARACTER,                         0x0F1D}, //+-
            {Opcode.CMSG_DEL_FRIEND,                               0x1103}, //+-
            {Opcode.CMSG_DEL_IGNORE,                               0x0737}, //+-
            {Opcode.CMSG_DESTROY_ITEM,                             0x0026}, //+-
            {Opcode.CMSG_DF_GET_JOIN_STATUS,                       0x032D}, //++
            {Opcode.CMSG_DF_GET_SYSTEM_INFO,                       0x006B}, //++
            {Opcode.CMSG_DISCARDED_TIME_SYNC_ACKS,                 0x115B}, //++
            {Opcode.CMSG_DISMISS_CRITTER,                          0x12DB}, //--
            {Opcode.CMSG_DO_READY_CHECK,                           0x0817}, //+-
            {Opcode.CMSG_DUEL_PROPOSED,                            0x1A26}, //+-
            {Opcode.CMSG_DUEL_RESPONSE,                            0x03E2}, //+-
            {Opcode.CMSG_EJECT_PASSENGER,                          0x06E7}, //--
            {Opcode.CMSG_EMOTE,                                    0x1924}, //++
            {Opcode.CMSG_ENABLE_TAXI_NODE,                         0x0741}, //++
            {Opcode.CMSG_ENUM_CHARACTERS,                          0x00E0}, //++
            {Opcode.CMSG_EQUIPMENT_SET_DELETE,                     0x02E8}, //+-
            {Opcode.CMSG_EQUIPMENT_SET_USE,                        0x036E}, //+-
            {Opcode.CMSG_FORCE_MOVE_ROOT_ACK,                      0x107A}, //++
            {Opcode.CMSG_FORCE_MOVE_UNROOT_ACK,                    0x1051}, //++
            {Opcode.CMSG_GAME_OBJ_REPORT_USE,                      0x06D9}, //++ ??
            {Opcode.CMSG_GAME_OBJ_USE,                             0x06D8}, //++ ??
            {Opcode.CMSG_GAME_SHOP_QUERY,                          0x0DE0}, //++
            {Opcode.CMSG_GENERATE_RANDOM_CHARACTER_NAME,           0x0B1C}, //+-
            {Opcode.CMSG_GET_ITEM_PURCHASE_DATA,                   0x1258}, //+-
            {Opcode.CMSG_GET_MIRROR_IMAGE_DATA,                    0x02A3}, //++
            {Opcode.CMSG_GET_PVP_OPTIONS_ENABLED,                  0x0A22}, //++
            {Opcode.CMSG_GET_TIMEZONE_INFORMATION,                 0x18B2}, //++
            {Opcode.CMSG_GM_TICKET_CREATE,                         0x1A86}, //--
            {Opcode.CMSG_GM_TICKET_DELETE_TICKET,                  0x1A23}, //+-
            {Opcode.CMSG_GM_TICKET_GET_TICKET,                     0x1F89}, //++
            {Opcode.CMSG_GM_TICKET_GET_SYSTEM_STATUS,              0x0A82}, //+-
            {Opcode.CMSG_GM_TICKET_GET_CASE_STATUS,                0x15A8}, //++
            {Opcode.CMSG_GM_TICKET_UPDATE_TEXT,                    0x0A26}, //--
            {Opcode.CMSG_GOSSIP_HELLO,                             0x12F3}, //++
            {Opcode.CMSG_GOSSIP_SELECT_OPTION,                     0x0748}, //++
            {Opcode.CMSG_GRANT_LEVEL,                              0x0662}, //--
            {Opcode.CMSG_GROUP_ASSISTANT_LEADER,                   0x1897}, //+-
            {Opcode.CMSG_GROUP_DISBAND,                            0x1798}, //++
            {Opcode.CMSG_GROUP_INVITE,                             0x072D}, //+-
            {Opcode.CMSG_GROUP_INVITE_RESPONSE,                    0x0D61}, //+-
            {Opcode.CMSG_GROUP_RAID_CONVERT,                       0x032C}, //+-
            {Opcode.CMSG_GROUP_SET_LEADER,                         0x15BB}, //+-
            {Opcode.CMSG_GROUP_SET_ROLES,                          0x1A92}, //+-
            {Opcode.CMSG_GROUP_UNINVITE_GUID,                      0x0CE1}, //+-
            {Opcode.CMSG_GUILD_ACCEPT,                             0x18A2}, //+-
            {Opcode.CMSG_GUILD_ADD_RANK,                           0x047A}, //+-
            {Opcode.CMSG_GUILD_ASSIGN_MEMBER_RANK,                 0x05D0}, //+-
            {Opcode.CMSG_GUILD_BANK_ACTIVATE,                      0x0372}, //+-
            {Opcode.CMSG_GUILD_BANK_BUY_TAB,                       0x0251}, //+-
            {Opcode.CMSG_GUILD_BANK_DEPOSIT_MONEY,                 0x0770}, //+-
            {Opcode.CMSG_GUILD_BANK_LOG_QUERY,                     0x0CD3}, //+-
            {Opcode.CMSG_GUILD_BANK_REMAINING_WITHDRAW_MONEY_QUERY, 0x14DB}, //++
            {Opcode.CMSG_GUILD_BANK_UPDATE_TAB,                    0x07C2}, //+-
            {Opcode.CMSG_GUILD_DECLINE_INVITATION,                 0x147B}, //+-
            {Opcode.CMSG_GUILD_DELETE_RANK,                        0x0D79}, //+-
            {Opcode.CMSG_GUILD_DEMOTE_MEMBER,                      0x1553}, //+-
            {Opcode.CMSG_GUILD_DISBAND,                            0x0D73}, //+-
            {Opcode.CMSG_GUILD_EVENT_LOG_QUERY,                    0x15D9}, //+-
            {Opcode.CMSG_GUILD_GET_RANKS,                          0x0D50}, //+-
            {Opcode.CMSG_GUILD_GET_ROSTER,                         0x1459}, //+-
            {Opcode.CMSG_GUILD_INFO_TEXT,                          0x0C70}, //+-
            {Opcode.CMSG_GUILD_INVITE,                             0x0869}, //+-
            {Opcode.CMSG_GUILD_LEAVE,                              0x04D8}, //+-
            {Opcode.CMSG_GUILD_MOTD,                               0x1473}, //+-
            {Opcode.CMSG_GUILD_NEWS_UPDATE_STICKY,                 0x04D1}, //+-
            {Opcode.CMSG_GUILD_OFFICER_REMOVE_MEMBER,              0x0CD8}, //+-
            {Opcode.CMSG_GUILD_PERMISSIONS_QUERY,                  0x145A}, //--
            {Opcode.CMSG_GUILD_PROMOTE_MEMBER,                     0x0571}, //+-
            {Opcode.CMSG_GUILD_QUERY_NEWS,                         0x1C58}, //+-
            {Opcode.CMSG_GUILD_REQUEST_CHALLENGE_UPDATE,           0x147A}, //+-
            {Opcode.CMSG_GUILD_SET_ACHIEVEMENT_TRACKING,           0x0CF0}, //++
            {Opcode.CMSG_GUILD_SET_GUILD_MASTER,                   0x1A83}, //+-
            {Opcode.CMSG_GUILD_SET_NOTE,                           0x05DA}, //+-
            {Opcode.CMSG_GUILD_SET_RANK_PERMISSIONS,               0x0C7A}, //+-
            {Opcode.CMSG_GUILD_SWITCH_RANK,                        0x0CD1}, //--
            {Opcode.CMSG_IGNORE_TRADE,                             0x0276}, //++
            {Opcode.CMSG_INITIATE_TRADE,                           0x0267}, //++
            {Opcode.CMSG_INSPECT,                                  0x1259}, //++
            {Opcode.CMSG_INSPECT_HONOR_STATS,                      0x19C3}, //++
            {Opcode.CMSG_ITEM_TEXT_QUERY,                          0x0123}, //++
            {Opcode.CMSG_LEARN_TALENT,                             0x02A7}, //+-
            {Opcode.CMSG_LFG_JOIN,                                 0x046B}, //++
            {Opcode.CMSG_LFG_TELEPORT,                             0x1AA6}, //+-
            {Opcode.CMSG_LF_GUILD_ADD_APPLICATION,                 0x0C63}, //+-
            {Opcode.CMSG_LF_GUILD_BROWSE,                          0x159A}, //+-
            {Opcode.CMSG_LF_GUILD_GET_APPLICATIONS,                0x0558}, //+-
            {Opcode.CMSG_LF_GUILD_GET_RECRUITS,                    0x057A}, //--
            {Opcode.CMSG_LF_GUILD_REMOVE_APPLICATION,              0x1C53}, //+-
            {Opcode.CMSG_LF_GUILD_SET_GUILD_POST,                  0x1D9F}, //--
            {Opcode.CMSG_LIST_INVENTORY,                           0x02D8}, //++
            {Opcode.CMSG_LOADING_SCREEN_NOTIFY,                    0x1DBD}, //++
            {Opcode.CMSG_LOGOUT_CANCEL,                            0x06C1}, //++
            {Opcode.CMSG_LOGOUT_REQUEST,                           0x1349}, //+-
            {Opcode.CMSG_LOG_DISCONNECT,                           0x10B3}, //++
            {Opcode.CMSG_LOOT_MONEY,                               0x02F6}, //+-
            {Opcode.CMSG_LOOT_RELEASE,                             0x0840}, //++
            {Opcode.CMSG_LOOT_ROLL,                                0x15C2}, //++
            {Opcode.CMSG_LOOT_UNIT,                                0x1CE2}, //+-
            {Opcode.CMSG_MAIL_CREATE_TEXT_ITEM,                    0x1270}, //+-
            {Opcode.CMSG_MAIL_DELETE,                              0x14E2}, //+-
            {Opcode.CMSG_MAIL_GET_LIST,                            0x077A}, //++
            {Opcode.CMSG_MAIL_MARK_AS_READ,                        0x0241}, //++
            {Opcode.CMSG_MAIL_RETURN_TO_SENDER,                    0x1FA8}, //+-
            {Opcode.CMSG_MAIL_TAKE_ITEM,                           0x1371}, //++
            {Opcode.CMSG_MAIL_TAKE_MONEY,                          0x06FA}, //++
            {Opcode.CMSG_MINIMAP_PING,                             0x0837}, //+-
            {Opcode.CMSG_MOVE_APPLY_MOVEMENT_FORCE_ACK,            0x08D3}, //++
            {Opcode.CMSG_MOVE_CHNG_TRANSPORT,                      0x09DB}, //++
            {Opcode.CMSG_MOVE_FALL_LAND,                           0x08FA}, //++
            {Opcode.CMSG_MOVE_FEATHER_FALL_ACK,                    0x08D0}, //++ pair SMSG 0C60 08E0
            {Opcode.CMSG_MOVE_FORCE_FLIGHT_SPEED_CHANGE_ACK,       0x09DA}, //++
            {Opcode.CMSG_MOVE_FORCE_RUN_BACK_SPEED_CHANGE_ACK,     0x0158}, //++
            {Opcode.CMSG_MOVE_FORCE_RUN_SPEED_CHANGE_ACK,          0x10F3}, //++
            {Opcode.CMSG_MOVE_FORCE_SWIM_SPEED_CHANGE_ACK,         0x1853}, //++
            {Opcode.CMSG_MOVE_FORCE_WALK_SPEED_CHANGE_ACK,         0x00DB}, //++
            {Opcode.CMSG_MOVE_GRAVITY_DISABLE_ACK,                 0x09D3}, //++
            {Opcode.CMSG_MOVE_GRAVITY_ENABLE_ACK,                  0x11D8}, //++
            {Opcode.CMSG_MOVE_HEARTBEAT,                           0x01F2}, //++
            {Opcode.CMSG_MOVE_JUMP,                                0x1153}, //++
            {Opcode.CMSG_MOVE_KNOCK_BACK_ACK,                      0x00F2}, //++ pair 0562
            {Opcode.CMSG_MOVE_REMOVE_MOVEMENT_FORCE_ACK,           0x10DB}, //++
            {Opcode.CMSG_MOVE_SET_CAN_FLY_ACK,                     0x1052}, //++
            {Opcode.CMSG_MOVE_SET_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY_ACK, 0x11DB}, //++
            {Opcode.CMSG_MOVE_SET_COLLISION_HEIGHT_ACK,            0x09FB}, //++
            {Opcode.CMSG_MOVE_SET_FLY,                             0x01F1}, //++
            {Opcode.CMSG_MOVE_SET_FACING,                          0x1050}, //++
            {Opcode.CMSG_MOVE_SET_PITCH,                           0x017A}, //++
            {Opcode.CMSG_MOVE_SET_RUN_MODE,                        0x0979}, //++
            {Opcode.CMSG_MOVE_SET_WALK_MODE,                       0x08D1}, //++
            {Opcode.CMSG_MOVE_SPLINE_DONE,                         0x11D9}, //++
            {Opcode.CMSG_MOVE_START_ASCEND,                        0x11FA}, //++
            {Opcode.CMSG_MOVE_START_BACKWARD,                      0x09D8}, //++
            {Opcode.CMSG_MOVE_START_DESCEND,                       0x01D1}, //+-
            {Opcode.CMSG_MOVE_START_FORWARD,                       0x095A}, //++
            {Opcode.CMSG_MOVE_START_PITCH_DOWN,                    0x08D8}, //++
            {Opcode.CMSG_MOVE_START_PITCH_UP,                      0x00D8}, //++
            {Opcode.CMSG_MOVE_START_STRAFE_LEFT,                   0x01F8}, //++
            {Opcode.CMSG_MOVE_START_STRAFE_RIGHT,                  0x1058}, //++
            {Opcode.CMSG_MOVE_START_SWIM,                          0x1858}, //++
            {Opcode.CMSG_MOVE_START_TURN_LEFT,                     0x01D0}, //++
            {Opcode.CMSG_MOVE_START_TURN_RIGHT,                    0x107B}, //++
            {Opcode.CMSG_MOVE_STOP,                                0x08F1}, //++
            {Opcode.CMSG_MOVE_STOP_ASCEND,                         0x115A}, //++
            {Opcode.CMSG_MOVE_STOP_PITCH,                          0x007A}, //++
            {Opcode.CMSG_MOVE_STOP_STRAFE,                         0x0171}, //++
            {Opcode.CMSG_MOVE_STOP_SWIM,                           0x0950}, //++
            {Opcode.CMSG_MOVE_STOP_TURN,                           0x1170}, //++
            {Opcode.CMSG_MOVE_TELEPORT_ACK,                        0x0078}, //++
            {Opcode.CMSG_MOVE_TIME_SKIPPED,                        0x0150}, //++
            {Opcode.CMSG_MOVE_WATER_WALK_ACK,                      0x10F2}, //++
            {Opcode.CMSG_NAME_QUERY,                               0x0328}, //++
            {Opcode.CMSG_NEUTRAL_PLAYER_SELECT_FACTION,            0x0027}, //+-
            {Opcode.CMSG_NULL_0060,                                0x0060}, //+-
            {Opcode.CMSG_NULL_0082,                                0x0082}, //+-
            {Opcode.CMSG_NULL_0141,                                0x0141}, //+-
            {Opcode.CMSG_NULL_01C0,                                0x01C0}, //+-
            {Opcode.CMSG_NULL_02D6,                                0x02D6}, //+-
            {Opcode.CMSG_NULL_02DA,                                0x02DA}, //+-
            {Opcode.CMSG_NULL_033D,                                0x033D}, //+-
            {Opcode.CMSG_NULL_0360,                                0x0360}, //++
            {Opcode.CMSG_NULL_03C4,                                0x03C4}, //+-
            {Opcode.CMSG_NULL_05E1,                                0x05E1}, //+-
            {Opcode.CMSG_NULL_0644,                                0x0644}, //+-
            {Opcode.CMSG_NULL_06D4,                                0x06D4}, //+-
            {Opcode.CMSG_NULL_0813,                                0x0813}, //+-
            {Opcode.CMSG_NULL_0A23,                                0x0A23}, //+-
            {Opcode.CMSG_NULL_0C62,                                0x0C62}, //+-
            {Opcode.CMSG_NULL_1063,                                0x1063}, //++ battle pet
            {Opcode.CMSG_NULL_1124,                                0x1124}, //+-
            {Opcode.CMSG_NULL_1207,                                0x1207}, //+-
            {Opcode.CMSG_NULL_135B,                                0x135B}, //+-
            {Opcode.CMSG_NULL_1362,                                0x1362}, //++
            {Opcode.CMSG_NULL_1452,                                0x1452}, //+-
            {Opcode.CMSG_NULL_14E0,                                0x14E0}, //+-
            {Opcode.CMSG_NULL_15E2,                                0x15E2}, //+-
            {Opcode.CMSG_NULL_1A87,                                0x1A87}, //+-
            {Opcode.CMSG_NULL_1C45,                                0x1C45}, //+-
            {Opcode.CMSG_NULL_1C5A,                                0x1C5A}, //+-
            {Opcode.CMSG_NULL_1D61,                                0x1D61}, //+-
            {Opcode.CMSG_NULL_1DC3,                                0x1DC3}, //+-
            {Opcode.CMSG_NULL_1F34,                                0x1F34}, //+-
            {Opcode.CMSG_NULL_1F8E,                                0x1F8E}, //+-
            {Opcode.CMSG_NULL_1F9F,                                0x1F9F}, //+-
            {Opcode.CMSG_OBJECT_UPDATE_FAILED,                     0x1061}, //+-
            {Opcode.CMSG_OFFER_PETITION,                           0x15BE}, //+-
            {Opcode.CMSG_OPENING_CINEMATIC,                        0x0130}, //+-
            {Opcode.CMSG_OPEN_ITEM,                                0x1D10}, //+-
            {Opcode.CMSG_OPT_OUT_OF_LOOT,                          0x06E0}, //--
            {Opcode.CMSG_PETITION_BUY,                             0x12D9}, //+-
            {Opcode.CMSG_PETITION_DECLINE,                         0x1279}, //+-
            {Opcode.CMSG_PETITION_QUERY,                           0x0255}, //+-
            {Opcode.CMSG_PETITION_RENAME,                          0x1F9A}, //+-
            {Opcode.CMSG_PETITION_SHOW_LIST,                       0x037B}, //+-
            {Opcode.CMSG_PETITION_SHOW_SIGNATURES,                 0x136B}, //+-
            {Opcode.CMSG_PETITION_SIGN,                            0x06DA}, //+-
            {Opcode.CMSG_PET_ABANDON,                              0x07D0}, //+-
            {Opcode.CMSG_PET_ACTION,                               0x025B}, //+-
            {Opcode.CMSG_PET_CAST_SPELL,                           0x044D}, //+-
            {Opcode.CMSG_PET_RENAME,                               0x0A32}, //+-
            {Opcode.CMSG_PET_SET_ACTION,                           0x12E9}, //+-
            {Opcode.CMSG_PET_STOP_ATTACK,                          0x065B}, //--
            {Opcode.CMSG_PING,                                     0x0012}, //++
            {Opcode.CMSG_PLAYER_LOGIN,                             0x158F}, //++
            {Opcode.CMSG_PVP_LOG_DATA,                             0x14C2}, //+-
            {Opcode.CMSG_QUERY_BATTLE_PET_NAME,                    0x1CE0}, //+-
            {Opcode.CMSG_QUERY_COUNTDOWN_TIMER,                    0x044E}, //++
            {Opcode.CMSG_QUERY_CREATURE,                           0x0842}, //++
            {Opcode.CMSG_QUERY_GAME_OBJECT,                        0x1461}, //++
            {Opcode.CMSG_QUERY_GUILD_INFO,                         0x1AB6}, //+-
            {Opcode.CMSG_QUERY_INSPECT_ACHIEVEMENTS,               0x0373}, //++
            {Opcode.CMSG_QUERY_NEXT_MAIL_TIME,                     0x077B}, //++
            {Opcode.CMSG_QUERY_NPC_TEXT,                           0x0287}, //++
            {Opcode.CMSG_QUERY_PAGE_TEXT,                          0x1022}, //+-
            {Opcode.CMSG_QUERY_PET_NAME,                           0x1C62}, //++
            {Opcode.CMSG_QUERY_QUEST_INFO,                         0x02D5}, //++
            {Opcode.CMSG_QUERY_REALM_NAME,                         0x1A16}, //++
            {Opcode.CMSG_QUERY_TIME,                               0x0640}, //++
            {Opcode.CMSG_QUERY_VOID_STORAGE,                       0x0140}, //+-
            {Opcode.CMSG_QUEST_CONFIRM_ACCEPT,                     0x124B}, //--
            {Opcode.CMSG_QUEST_GIVER_ACCEPT_QUEST,                 0x06D1}, //++
            {Opcode.CMSG_QUEST_GIVER_CHOOSE_REWARD,                0x07CB}, //++
            {Opcode.CMSG_QUEST_GIVER_COMPLETE_QUEST,               0x0659}, //++
            {Opcode.CMSG_QUEST_GIVER_HELLO,                        0x02DB}, //++
            {Opcode.CMSG_QUEST_GIVER_QUERY_QUEST,                  0x12F0}, //++
            {Opcode.CMSG_QUEST_GIVER_REQUEST_REWARD,               0x0378}, //++
            {Opcode.CMSG_QUEST_GIVER_STATUS_MULTIPLE_QUERY,        0x02F1}, //++
            {Opcode.CMSG_QUEST_GIVER_STATUS_QUERY,                 0x036A}, //++
            {Opcode.CMSG_QUEST_LOG_REMOVE_QUEST,                   0x0779}, //+-
            {Opcode.CMSG_QUEST_NPC_QUERY,                          0x1DAE}, //++
            {Opcode.CMSG_QUEST_POI_QUERY,                          0x10C2}, //++
            {Opcode.CMSG_RANDOM_ROLL,                              0x08A3}, //+-
            {Opcode.CMSG_READY_CHECK_RESPONSE,                     0x158B}, //+-
            {Opcode.CMSG_READY_FOR_ACCOUNT_DATA_TIMES,             0x031C}, //++
            {Opcode.CMSG_READ_ITEM,                                0x0D00}, //++
            //{Opcode.CMSG_REALM_SPLIT,                              0x18B2}, //--
            {Opcode.CMSG_RECLAIM_CORPSE,                           0x03D3}, //++
            {Opcode.CMSG_REFORGE_ITEM,                             0x0C4F}, //++
            {Opcode.CMSG_REORDER_CHARACTERS,                       0x08A7}, //+-
            {Opcode.CMSG_REPAIR_ITEM,                              0x02C1}, //+-
            {Opcode.CMSG_REPOP_REQUEST,                            0x134A}, //+-
            {Opcode.CMSG_REPORT_PVP_PLAYER_AFK,                    0x06F9}, //--
            {Opcode.CMSG_REQUEST_ACCOUNT_DATA,                     0x1D8A}, //++
            {Opcode.CMSG_REQUEST_BATTLEFIELD_STATUS,               0x1F9E}, //++
            {Opcode.CMSG_REQUEST_CATEGORY_COOLDOWNS,               0x1203}, //++
            {Opcode.CMSG_REQUEST_CEMETERY_LIST,                    0x06E4}, //++
            {Opcode.CMSG_REQUEST_CONQUEST_FORMULA_CONSTANTS,       0x0365}, //++
            {Opcode.CMSG_REQUEST_FORCED_REACTIONS,                 0x06F5}, //++
            {Opcode.CMSG_REQUEST_GUILD_REWARDS_LIST,               0x06C4}, //+-
            {Opcode.CMSG_REQUEST_GUILD_XP,                         0x05F8}, //+-
            {Opcode.CMSG_REQUEST_HOTFIX,                           0x158D}, //+-
            {Opcode.CMSG_REQUEST_INSPECT_RATED_BG_STATS,           0x0882}, //++
            {Opcode.CMSG_REQUEST_PARTY_MEMBER_STATS,               0x0806}, //+-
            {Opcode.CMSG_REQUEST_PLAYED_TIME,                      0x03F6}, //++
            {Opcode.CMSG_REQUEST_PVP_REWARDS,                      0x0375}, //+-
            {Opcode.CMSG_REQUEST_RAID_INFO,                        0x0A87}, //+-
            {Opcode.CMSG_REQUEST_RATED_INFO,                       0x0826}, //+-
            {Opcode.CMSG_RESET_FACTION_CHEAT,                      0x10B6}, //+-
            {Opcode.CMSG_RESET_INSTANCES,                          0x0C69}, //+-
            {Opcode.CMSG_RESUME_TOKEN_ACK,                         0x0292}, //++ pair SMSG 18BA
            {Opcode.CMSG_RESURRECT_RESPONSE,                       0x0B0C}, //++
            {Opcode.CMSG_SAVE_CUF_PROFILES,                        0x06E6}, //++
            {Opcode.CMSG_SAVE_EQUIPMENT_SET,                       0x0669}, //+-
            //{Opcode.CMSG_SELECT_FACTION,                           0x0027}, //
            {Opcode.CMSG_SELL_ITEM,                                0x1358}, //+-
            {Opcode.CMSG_SEND_MAIL,                                0x1DBA}, //++
            {Opcode.CMSG_SEND_TEXT_EMOTE,                          0x07E9}, //++
            {Opcode.CMSG_SET_ACTION_BAR_TOGGLES,                   0x0672}, //++
            {Opcode.CMSG_SET_ACTION_BUTTON,                        0x1F8C}, //++
            {Opcode.CMSG_SET_ACTIVE_MOVER,                         0x09F0}, //++
            {Opcode.CMSG_SET_CONTACT_NOTES,                        0x0937}, //+-
            {Opcode.CMSG_SET_DUNGEON_DIFFICULTY,                   0x1A36}, //+-
            {Opcode.CMSG_SET_EVERYONE_IS_ASSISTANT,                0x01E1}, //+-
            {Opcode.CMSG_SET_LOOT_METHOD,                          0x0DE1}, //+- ??
            {Opcode.CMSG_SET_LOOT_SPECIALIZATION,                  0x1260}, //+-
            {Opcode.CMSG_SET_PLAYER_DECLINED_NAMES,                0x09E2}, //++
            {Opcode.CMSG_SET_PRIMARY_TALENT_TREE,                  0x06C6}, //+-
            {Opcode.CMSG_SET_PVP,                                  0x02C5}, //+-
            {Opcode.CMSG_SET_RAID_DIFFICULTY,                      0x1093}, //+-
            {Opcode.CMSG_SET_SELECTION,                            0x0740}, //++
            {Opcode.CMSG_SET_SHEATHED,                             0x0249}, //++
            {Opcode.CMSG_SET_TAXI_BENCHMARK_MODE,                  0x0762}, //+-
            {Opcode.CMSG_SET_TITLE,                                0x03C7}, //+-
            {Opcode.CMSG_SET_TRADE_GOLD,                           0x14E3}, //++
            {Opcode.CMSG_SET_TRADE_ITEM,                           0x03D5}, //++
            {Opcode.CMSG_SHOWING_CLOAK,                            0x02F2}, //+-
            {Opcode.CMSG_SHOWING_HELM,                             0x126B}, //+-
            {Opcode.CMSG_SHOW_TRADE_SKILL,                         0x179F}, //++
            {Opcode.CMSG_SOCKET_GEMS,                              0x02CB}, //+-
            {Opcode.CMSG_SPELL_CLICK,                              0x067A}, //+-
            {Opcode.CMSG_SPIRIT_HEALER_ACTIVATE,                   0x0340}, //++
            {Opcode.CMSG_SPLIT_ITEM,                               0x02EC}, //+-
            {Opcode.CMSG_STAND_STATE_CHANGE,                       0x03E6}, //+-
            {Opcode.CMSG_SUGGESTION_SUBMIT,                        0x0A12}, //+-
            {Opcode.CMSG_SUMMON_RESPONSE,                          0x0A33}, //--
            {Opcode.CMSG_SUPPORT_TICKET_SUBMIT_BUG,                0x0861}, //+-
            {Opcode.CMSG_SUPPORT_TICKET_SUBMIT_COMPLAINT,          0x030D}, //-- sub_66E294
            {Opcode.CMSG_SWAP_INV_ITEM,                            0x03DF}, //++
            {Opcode.CMSG_SWAP_ITEM,                                0x035D}, //++
            {Opcode.CMSG_SWAP_VOID_ITEM,                           0x0655}, //+-
            {Opcode.CMSG_TAXI_NODE_STATUS_QUERY,                   0x02E1}, //++
            {Opcode.CMSG_TAXI_QUERY_AVAILABLE_NODES,               0x02E3}, //++
            {Opcode.CMSG_TIME_SYNC_RESPONSE,                       0x01DB}, //+-
            {Opcode.CMSG_TIME_SYNC_RESPONSE_FAILED,                0x0058}, //+-
            {Opcode.CMSG_TOTEM_DESTROYED,                          0x1263}, //++
            {Opcode.CMSG_TRAINER_BUY_SPELL,                        0x0352}, //+-
            {Opcode.CMSG_TRAINER_LIST,                             0x034B}, //+-
            {Opcode.CMSG_TRANSMOGRIFY_ITEMS,                       0x06D7}, //+-
            {Opcode.CMSG_TURN_IN_PETITION,                         0x0673}, //+-
            {Opcode.CMSG_TUTORIAL_FLAG,                            0x1D36}, //++
            {Opcode.CMSG_UI_TIME_REQUEST,                          0x15AB}, //+-
            {Opcode.CMSG_UNACCEPT_TRADE,                           0x0023}, //++
            {Opcode.CMSG_UNK_0002,                                 0x0002}, //++
            {Opcode.CMSG_UNK_0087,                                 0x0087}, //++
            {Opcode.CMSG_UNK_009A,                                 0x009A}, //++ like CMSG_MESSAGECHAT_ADDON...
            {Opcode.CMSG_UNK_00D9,                                 0x00D9}, //++ PENDING_STRAFE_STOP
            {Opcode.CMSG_UNK_0247,                                 0x0247}, //+-
            {Opcode.CMSG_UNK_0264,                                 0x0264}, //+-
            {Opcode.CMSG_UNK_0265,                                 0x0265}, //+-
            {Opcode.CMSG_UNK_02C4,                                 0x02C4}, //+-
            {Opcode.CMSG_UNK_0377,                                 0x0377}, //-- battle pet
            {Opcode.CMSG_UNK_03E4,                                 0x03E4}, //+-
            {Opcode.CMSG_UNK_0656,                                 0x0656}, //+-
            {Opcode.CMSG_UNK_06C5,                                 0x06C5}, //++ battle pet
            {Opcode.CMSG_UNK_06C9,                                 0x06C9}, //++
            {Opcode.CMSG_UNK_09FA,                                 0x09FA}, //++
            {Opcode.CMSG_UNK_0A16,                                 0x0A16}, //++
            {Opcode.CMSG_UNK_10A2,                                 0x10A2}, //+-
            {Opcode.CMSG_UNK_10A7,                                 0x10A7}, //+-
            {Opcode.CMSG_UNK_10C3,                                 0x10C3}, //++
            {Opcode.CMSG_UNK_10D3,                                 0x10D3}, //++
            {Opcode.CMSG_UNK_12B3,                                 0x12B3}, //++
            {Opcode.CMSG_UNK_1341,                                 0x1341}, //++
            {Opcode.CMSG_UNK_1370,                                 0x1370}, //++
            {Opcode.CMSG_UNK_1446,                                 0x1446}, //+-
            {Opcode.CMSG_UNK_178A,                                 0x178A}, //++ raid
            {Opcode.CMSG_UNK_1841,                                 0x1841}, //+-
            {Opcode.CMSG_UNK_185B,                                 0x185B}, //++
            {Opcode.CMSG_UNK_19C2,                                 0x19C2}, //+-
            {Opcode.CMSG_UNK_1D9D,                                 0x1D9D}, //++ LFG
            {Opcode.CMSG_UNLEARN_SKILL,                            0x0268}, //++
            {Opcode.CMSG_UNLOCK_VOID_STORAGE,                      0x0444}, //+-
            {Opcode.CMSG_UPDATE_ACCOUNT_DATA,                      0x0068}, //++
            {Opcode.CMSG_UPDATE_RAID_TARGET,                       0x0886}, //++
            {Opcode.CMSG_UPGRADE_ITEM,                             0x1042}, //++
            {Opcode.CMSG_USED_FOLLOW,                              0x0374}, //++
            {Opcode.CMSG_USE_ITEM,                                 0x1CC1}, //-- sub_696A02
            {Opcode.CMSG_VIOLENCE_LEVEL,                           0x0040}, //+-
            {Opcode.CMSG_VOICE_SESSION_ENABLE,                     0x15A9}, //++
            {Opcode.CMSG_VOID_STORAGE_TRANSFER,                    0x1440}, //+-
            {Opcode.CMSG_WARDEN_DATA,                              0x1816}, //+-
            {Opcode.CMSG_WHO,                                      0x18A3}, //+-
            {Opcode.CMSG_WRAP_ITEM,                                0x02DF}, //+-
        };

        private static readonly BiDictionary<Opcode, int> ServerOpcodes = new BiDictionary<Opcode, int>
        {
            {Opcode.SMSG_ACCOUNT_CRITERIA_UPDATE,                  0x189E}, //++
            {Opcode.SMSG_ACCOUNT_DATA_TIMES,                       0x162B}, //++
            {Opcode.SMSG_ACHIEVEMENT_DELETED,                      0x1A2F}, //--
            {Opcode.SMSG_ACHIEVEMENT_EARNED,                       0x080B}, //--
            {Opcode.SMSG_ACTIVATE_TAXI_REPLY,                      0x02A7}, //++
            {Opcode.SMSG_ADDON_INFO,                               0x160A}, //++
            {Opcode.SMSG_ADD_LOSS_OF_CONTROL,                      0x0C13}, //++
            {Opcode.SMSG_ADJUST_SPLINE_DURATION,                   0x023B}, //++
            {Opcode.SMSG_AI_REACTION,                              0x06AF}, //++
            {Opcode.SMSG_ALL_ACCOUNT_CRITERIA,                     0x0A9E}, //++
            {Opcode.SMSG_ALL_ACHIEVEMENT_DATA,                     0x180A}, //++
            {Opcode.SMSG_ARCHAEOLOGY_SURVERY_CAST,                 0x1160}, //++
            {Opcode.SMSG_AREA_SPIRIT_HEALER_TIME,                  0x188E}, //++
            {Opcode.SMSG_AREA_TRIGGER_DENIED,                      0x148F}, //++ pair 1C44
            {Opcode.SMSG_AREA_TRIGGER_NO_CORPSE,                   0x089E}, //+-
            {Opcode.SMSG_ATTACKER_STATE_UPDATE,                    0x06AA}, //++
            {Opcode.SMSG_ATTACK_START,                             0x1A9E}, //++
            {Opcode.SMSG_ATTACK_STOP,                              0x12AF}, //++
            {Opcode.SMSG_AUCTION_BIDDER_NOTIFICATION,              0x11C1}, //++
            {Opcode.SMSG_AUCTION_COMMAND_RESULT,                   0x1002}, //++
            {Opcode.SMSG_AUCTION_HELLO_RESPONSE,                   0x10A7}, //++
            {Opcode.SMSG_AUCTION_LIST_BIDDER_ITEMS_RESULT,         0x0B24}, //++
            {Opcode.SMSG_AUCTION_LIST_RESULT,                      0x0982}, //++
            {Opcode.SMSG_AUCTION_OUTBID_NOTIFICATION,              0x1A9F}, //++
            {Opcode.SMSG_AUCTION_OWNER_NOTIFICATION,               0x1A8E}, //+-
            {Opcode.SMSG_AURA_POINTS_DEPLETED,                     0x1553}, //++
            {Opcode.SMSG_AURA_UPDATE,                              0x0072}, //++
            {Opcode.SMSG_AUTH_CHALLENGE,                           0x0949}, //-+
            {Opcode.SMSG_AUTH_RESPONSE,                            0x0ABA}, //++
            {Opcode.SMSG_BARBER_SHOP_RESULT,                       0x0C3F}, //+-
            {Opcode.SMSG_BATTLEFIELD_LIST,                         0x160E}, //++
            {Opcode.SMSG_BATTLEFIELD_MGR_EJECTED,                  0x18C2}, //--
            {Opcode.SMSG_BATTLEFIELD_MGR_ENTERING,                 0x081B}, //--
            {Opcode.SMSG_BATTLEFIELD_MGR_STATE_CHANGED,            0x083A}, //--
            {Opcode.SMSG_BATTLEFIELD_RATED_INFO,                   0x0EBA}, //++
            {Opcode.SMSG_BATTLEFIELD_STATUS,                       0x0433}, //++
            {Opcode.SMSG_BATTLEFIELD_STATUS_ACTIVE,                0x1AAF}, //++
            {Opcode.SMSG_BATTLEFIELD_STATUS_FAILED,                0x1140}, //+-
            {Opcode.SMSG_BATTLEFIELD_STATUS_NEED_CONFIRMATION,     0x1EAF}, //++
            {Opcode.SMSG_BATTLEFIELD_STATUS_QUEUED,                0x122E}, //++
            {Opcode.SMSG_BATTLEFIELD_STATUS_WAIT_FOR_GROUPS,       0x10A6}, //--
            {Opcode.SMSG_BATTLEGROUND_PLAYER_JOINED,               0x1E2F}, //++
            {Opcode.SMSG_BATTLEGROUND_PLAYER_LEFT,                 0x0206}, //+-
            {Opcode.SMSG_BATTLEGROUND_PLAYER_POSITIONS,            0x060A}, //++
            {Opcode.SMSG_BATTLE_PAY_GET_DISTRIBUTION_LIST_RESPONSE, 0x043F}, //--
            {Opcode.SMSG_BATTLE_PAY_PURCHASE_UPDATE,               0x14E2}, //++ pair+ 1886
            {Opcode.SMSG_BATTLE_PAY_START_PURCHASE_RESPONSE,       0x0612}, //++ pair 1886
            {Opcode.SMSG_BATTLE_PET_CHAT_RESTRICTED,               0x06BE}, //--
            {Opcode.SMSG_BATTLE_PET_DEBUG_QUEUE_DUMP_RESPONSE,     0x001E}, //--
            {Opcode.SMSG_BATTLE_PET_DELETED,                       0x18AB}, //+-
            {Opcode.SMSG_BATTLE_PET_FINALIZE_LOCATION,             0x082E}, //++
            {Opcode.SMSG_BATTLE_PET_FINAL_ROUND,                   0x1C2F}, //--
            {Opcode.SMSG_BATTLE_PET_FINISHED,                      0x04BB}, //++
            {Opcode.SMSG_BATTLE_PET_FIRST_ROUND,                   0x0613}, //--
            {Opcode.SMSG_BATTLE_PET_INITIAL_UPDATE,                0x0E1E}, //--
            {Opcode.SMSG_BATTLE_PET_JOURNAL,                       0x1542}, //++
            {Opcode.SMSG_BATTLE_PET_JOURNAL_LOCK_ACQUIRED,         0x1A0F}, //++
            {Opcode.SMSG_BATTLE_PET_JOURNAL_LOCK_DENIED,           0x0203}, //+-
            {Opcode.SMSG_BATTLE_PET_MAX_GAME_LENGTH_WARNING,       0x022B}, //--
            {Opcode.SMSG_BATTLE_PET_PVP_CHALLENGE,                 0x1E0B}, //--
            {Opcode.SMSG_BATTLE_PET_QUERY_NAME_RESPONSE,           0x1540}, //++
            {Opcode.SMSG_BATTLE_PET_QUEUE_PROPOSE_MATCH,           0x1202}, //--
            {Opcode.SMSG_BATTLE_PET_QUEUE_STATUS,                  0x00A6}, //--
            {Opcode.SMSG_BATTLE_PET_REPLACEMENTS_MADE,             0x1A1A}, //--
            {Opcode.SMSG_BATTLE_PET_REQUEST_FAILED,                0x022F}, //--
            {Opcode.SMSG_BATTLE_PET_ROUND_RESULT,                  0x0C1A}, //-- pair 17BA
            {Opcode.SMSG_BATTLE_PET_SCENE_OBJECT_FINAL_ROUND,      0x161F}, //--
            {Opcode.SMSG_BATTLE_PET_SCENE_OBJECT_FINISHED,         0x18E1}, //--
            {Opcode.SMSG_BATTLE_PET_SCENE_OBJECT_ROUND_RESULT,     0x109B}, //--
            {Opcode.SMSG_BATTLE_PET_SLOT_UPDATE,                   0x16AF}, //+-
            {Opcode.SMSG_BATTLE_PET_UPDATES,                       0x041A}, //+-
            {Opcode.SMSG_BINDER_CONFIRM,                           0x1287}, //+-
            {Opcode.SMSG_BIND_POINT_UPDATE,                        0x0E3B}, //++
            {Opcode.SMSG_BLACK_MARKET_OPEN_RESULT,                 0x00AE}, //++
            {Opcode.SMSG_BLACK_MARKET_REQUEST_ITEMS_RESULT,        0x128B}, //++
            {Opcode.SMSG_BREAK_TARGET,                             0x021A}, //++
            {Opcode.SMSG_BUY_FAILED,                               0x1563}, //+-
            {Opcode.SMSG_BUY_SUCCEEDED,                            0x101A}, //++
            {Opcode.SMSG_CALENDAR_CLEAR_PENDING_ACTION,            0x1E3A}, //--
            {Opcode.SMSG_CALENDAR_COMMAND_RESULT,                  0x142A}, //--
            {Opcode.SMSG_CALENDAR_EVENT_INITIAL_INVITES,           0x16AE}, //--
            {Opcode.SMSG_CALENDAR_EVENT_INVITE,                    0x15C3}, //--
            {Opcode.SMSG_CALENDAR_EVENT_INVITE_ALERT,              0x0A9F}, //--
            {Opcode.SMSG_CALENDAR_EVENT_INVITE_REMOVED,            0x00A2}, //--
            {Opcode.SMSG_CALENDAR_EVENT_INVITE_REMOVED_ALERT,      0x122B}, //--
            {Opcode.SMSG_CALENDAR_EVENT_INVITE_STATUS,             0x1C9B}, //--
            {Opcode.SMSG_CALENDAR_EVENT_INVITE_STATUS_ALERT,       0x0412}, //--
            {Opcode.SMSG_CALENDAR_EVENT_INVITE_MODERATOR_STATUS,   0x048F}, //--
            {Opcode.SMSG_CALENDAR_EVENT_REMOVED_ALERT,             0x049B}, //--
            {Opcode.SMSG_CALENDAR_EVENT_UPDATED_ALERT,             0x0A0E}, //--
            {Opcode.SMSG_CALENDAR_RAID_LOCKOUT_ADDED,              0x0CAB}, //--
            {Opcode.SMSG_CALENDAR_RAID_LOCKOUT_REMOVED,            0x11E0}, //--
            {Opcode.SMSG_CALENDAR_RAID_LOCKOUT_UPDATED,            0x0E1F}, //--
            {Opcode.SMSG_CALENDAR_SEND_CALENDAR,                   0x1A0A}, //--
            {Opcode.SMSG_CALENDAR_SEND_EVENT,                      0x12AE}, //--
            {Opcode.SMSG_CALENDAR_SEND_NUM_PENDING,                0x0A3F}, //++
            {Opcode.SMSG_CAMERA_SHAKE,                             0x0C3A}, //--
            {Opcode.SMSG_CAN_DUEL_RESULT,                          0x083F}, //--
            {Opcode.SMSG_CANCEL_AUTO_REPEAT,                       0x1E0F}, //++
            {Opcode.SMSG_CANCEL_ORPHAN_SPELL_VISUAL,               0x1412}, //--
            {Opcode.SMSG_CANCEL_COMBAT,                            0x11E1}, //++
            {Opcode.SMSG_CANCEL_SCENE,                             0x120E}, //++
            {Opcode.SMSG_CAST_FAILED,                              0x143A}, //++
            {Opcode.SMSG_CATEGORY_COOLDOWN,                        0x01DB}, //++
            {Opcode.SMSG_CHALLENGE_MODE_ALL_MAP_STATS,             0x11C2}, //++ pair 1452
            {Opcode.SMSG_CHALLENGE_MODE_REQUEST_LEADERS_RESULT,    0x182E}, //++ pair 15DB
            {Opcode.SMSG_CHALLENGE_MODE_REWARDS,                   0x168A}, //++ pair 1C5A
            {Opcode.SMSG_CHANNEL_LIST,                             0x0B22}, //++ pair 0C1B
            {Opcode.SMSG_CHANNEL_NOTIFY,                           0x0F06}, //--
            {Opcode.SMSG_CHARACTER_RENAME_RESULT,                  0x0CBF}, //--
            {Opcode.SMSG_CHAT,                                     0x1A9A}, //++
            {Opcode.SMSG_CHAT_NOT_IN_PARTY,                        0x0A8A}, //++ pair 009A
            {Opcode.SMSG_CHAT_PLAYER_AMBIGUOUS,                    0x061A}, //--
            {Opcode.SMSG_CHAT_PLAYER_NOTFOUND,                     0x1082}, //++
            {Opcode.SMSG_CHAT_RESTRICTED,                          0x1A3B}, //--
            {Opcode.SMSG_CHAT_SERVER_MESSAGE,                      0x0302}, //+-
            {Opcode.SMSG_CHEAT_IGNORE_DIMISHING_RETURNS,           0x05D8}, //+-
            {Opcode.SMSG_CLEAR_ALL_SPELL_CHARGES,                  0x0C5B}, //++
            {Opcode.SMSG_CLEAR_QUEST_COMPLETED_BIT,                0x03EC}, //+-
            {Opcode.SMSG_CLEAR_QUEST_COMPLETED_BITS,               0x0364}, //++
            {Opcode.SMSG_CLEAR_SPELL_CHARGES,                      0x00F2}, //+-
            {Opcode.SMSG_CLEAR_TARGET,                             0x1061}, //++
            {Opcode.SMSG_CLIENTCACHE_VERSION,                      0x002A}, //++
            {Opcode.SMSG_CONTROL_UPDATE,                           0x1043}, //++
            {Opcode.SMSG_COMBAT_EVENT_FAILED,                      0x18C3}, //++
            {Opcode.SMSG_CONNECT_TO,                               0x1149}, //--
            {Opcode.SMSG_CONTACT_LIST,                             0x1F22}, //++
            {Opcode.SMSG_CONVERT_RUNE,                             0x1A1B}, //+-
            {Opcode.SMSG_COOLDOWN_CHEAT,                           0x0432}, //--
            {Opcode.SMSG_COOLDOWN_EVENT,                           0x1163}, //++
            {Opcode.SMSG_CORPSE_MAP_POSITION_QUERY_RESPONSE,       0x1A3A}, //+-
            {Opcode.SMSG_CORPSE_QUERY_RESPONSE,                    0x0E0B}, //++
            {Opcode.SMSG_CORPSE_RECLAIM_DELAY,                     0x022A}, //++
            {Opcode.SMSG_CLEAR_COOLDOWN,                           0x1458}, //--
            {Opcode.SMSG_CREATE_CHAR,                              0x1CAA}, //++
            {Opcode.SMSG_CRITERIA_DELETED,                         0x1C33}, //++
            {Opcode.SMSG_CRITERIA_UPDATE,                          0x0E9B}, //++
            {Opcode.SMSG_CROSSED_INEBRIATION_THRESHOLD,            0x1E9E}, //++
            {Opcode.SMSG_CUSTOM_LOAD_SCREEN,                       0x1CAF}, //++
            {Opcode.SMSG_DANCE_STUDIO_CREATE_RESULT,               0x1E9B}, //++
            {Opcode.SMSG_DAILY_QUESTS_RESET,                       0x1366}, //+-
            {Opcode.SMSG_DB_REPLY,                                 0x103B}, //++
            {Opcode.SMSG_DEATH_RELEASE_LOC,                        0x1063}, //+-
            {Opcode.SMSG_DEFENSE_MESSAGE,                          0x0A1F}, //+-
            {Opcode.SMSG_DELETE_CHAR,                              0x0C9F}, //+-
            {Opcode.SMSG_DESTROY_ARENA_UNIT,                       0x00BE}, //++
            {Opcode.SMSG_DESTROY_OBJECT,                           0x14C2}, //++
            {Opcode.SMSG_DISMOUNT,                                 0x0E3A}, //++
            {Opcode.SMSG_DISPEL_FAILED,                            0x085B}, //+-
            {Opcode.SMSG_DISPLAY_PROMOTION,                        0x00A3}, //++
            {Opcode.SMSG_DUEL_COMPLETE,                            0x1C0A}, //--
            {Opcode.SMSG_DUEL_COUNTDOWN,                           0x129F}, //--
            {Opcode.SMSG_DUEL_IN_BOUNDS,                           0x163A}, //+-
            {Opcode.SMSG_DUEL_OUT_OF_BOUNDS,                       0x001A}, //--
            {Opcode.SMSG_DUEL_REQUESTED,                           0x0022}, //--
            {Opcode.SMSG_DUEL_WINNER,                              0x10E1}, //--
            {Opcode.SMSG_DURABILITY_DAMAGE_DEATH,                  0x1E3E}, //++
            {Opcode.SMSG_EMOTE,                                    0x0987}, //--
            {Opcode.SMSG_ENABLE_BARBER_SHOP,                       0x1222}, //--
            {Opcode.SMSG_ENCHANTMENT_LOG,                          0x12A3}, //++
            {Opcode.SMSG_ENCOUNTER_END,                            0x120F}, //++
            {Opcode.SMSG_ENCOUNTER_START,                          0x1E8A}, //++
            {Opcode.SMSG_ENUM_CHARACTERS_RESULT,                   0x11C3}, //++
            {Opcode.SMSG_ENVIRONMENTAL_DAMAGE_LOG,                 0x0DF1}, //--
            {Opcode.SMSG_EXPLORATION_EXPERIENCE,                   0x189A}, //+-
            {Opcode.SMSG_FACTION_BONUS_INFO,                       0x0A0B}, //++
            {Opcode.SMSG_FAILED_PLAYER_CONDITION,                  0x1223}, //++
            {Opcode.SMSG_FEATURE_SYSTEM_STATUS,                    0x16BB}, //++
            {Opcode.SMSG_FEATURE_SYSTEM_STATUS_GLUE_SCREEN,        0x121E}, //++
            {Opcode.SMSG_FLIGHT_SPLINE_SYNC,                       0x0063}, //++
            {Opcode.SMSG_FORCE_SET_VEHICLE_REC_ID,                 0x149F}, //++
            {Opcode.SMSG_FRIEND_STATUS,                            0x0532}, //++
            {Opcode.SMSG_GAMEOBJECT_DESPAWN_ANIM,                  0x108B}, //++
            {Opcode.SMSG_GAME_OBJECT_ACTIVATE_ANIM_KIT,            0x0C8A}, //++
            {Opcode.SMSG_GAME_OBJECT_CUSTOM_ANIM,                  0x001F}, //++
            {Opcode.SMSG_GAME_SHOP_QUERY_RESPONSE,                 0x1ABF}, //--
            {Opcode.SMSG_GAME_STORE_INGAME_BUY_FAILED,             0x023A}, //++
            {Opcode.SMSG_GAME_TIME_UPDATE,                         0x0E1B}, //++
            {Opcode.SMSG_GENERATE_RANDOM_CHARACTER_NAME_RESULT,    0x169F}, //+-
            {Opcode.SMSG_GMRESPONSE_RECEIVED,                      0x148E}, //++
            {Opcode.SMSG_GM_TICKET_GET_TICKET,                     0x129B}, //++
            {Opcode.SMSG_GM_TICKET_RESOLVE_RESPONSE,               0x1ABE}, //+-
            {Opcode.SMSG_GM_TICKET_SYSTEM_STATUS,                  0x163B}, //++
            {Opcode.SMSG_GOD_MODE,                                 0x1862}, //+-
            {Opcode.SMSG_GOSSIP_COMPLETE,                          0x034E}, //+-
            {Opcode.SMSG_GOSSIP_MESSAGE,                           0x0244}, //--
            {Opcode.SMSG_GOSSIP_POI,                               0x0785}, //++
            {Opcode.SMSG_GROUP_DECLINE,                            0x17A3}, //+-
            {Opcode.SMSG_GROUP_DESTROYED,                          0x1B27}, //--
            {Opcode.SMSG_GROUP_INVITE,                             0x0A8F}, //--
            {Opcode.SMSG_GROUP_LIST,                               0x0CBB}, //--
            {Opcode.SMSG_GROUP_SET_LEADER,                         0x18BF}, //+-
            {Opcode.SMSG_GROUP_SET_ROLE,                           0x1E1F}, //--
            {Opcode.SMSG_GUILD_ACHIEVEMENT_DATA,                   0x0EF8}, //++
            {Opcode.SMSG_GUILD_ACHIEVEMENT_EARNED,                 0x1BF1}, //--
            {Opcode.SMSG_GUILD_BANK_LOG_QUERY_RESULTS,             0x0FF0}, //--
            {Opcode.SMSG_GUILD_BANK_QUERY_RESULTS,                 0x0B79}, //--
            {Opcode.SMSG_GUILD_BANK_REMAINING_WITHDRAW_MONEY,      0x0B78}, //++
            {Opcode.SMSG_GUILD_CHALLENGE_UPDATE,                   0x0AE9}, //--
            {Opcode.SMSG_GUILD_CHANGE_NAME_RESULT,                 0x0BE9}, //+-
            {Opcode.SMSG_GUILD_COMMAND_RESULT,                     0x0EF1}, //--
            {Opcode.SMSG_GUILD_CRITERIA_DATA,                      0x1BF0}, //--
            {Opcode.SMSG_GUILD_DECLINE,                            0x1AF9}, //--
            {Opcode.SMSG_GUILD_EVENT_BANK_MONEY_CHANGED,           0x0F68}, //--
            {Opcode.SMSG_GUILD_EVENT_TAB_ADDED,                    0x1BE9}, //--
            {Opcode.SMSG_GUILD_EVENT_TAB_MODIFIED,                 0x0BF1}, //--
            {Opcode.SMSG_GUILD_EVENT_TAB_TEXT_CHANGED,             0x0A70}, //--
            {Opcode.SMSG_GUILD_EVENT_LOG_QUERY_RESULTS,            0x1AF1}, //--
            {Opcode.SMSG_GUILD_EVENT_PRESENCE_CHANGE,              0x0B70}, //++
            {Opcode.SMSG_GUILD_FLAGGED_FOR_RENAME,                 0x0FE9}, //+-
            {Opcode.SMSG_GUILD_INVITE,                             0x0F71}, //--
            {Opcode.SMSG_GUILD_INVITE_ACCEPT,                      0x0B69}, //--
            {Opcode.SMSG_GUILD_INVITE_CANCEL,                      0x0FE1}, //++
            {Opcode.SMSG_GUILD_LEAVE,                              0x0BF8}, //--
            {Opcode.SMSG_GUILD_MEMBER_DAILY_RESET,                 0x1BE8}, //+-
            {Opcode.SMSG_GUILD_MOTD,                               0x0B68}, //++
            {Opcode.SMSG_GUILD_NEWS_UPDATE,                        0x0AE8}, //--
            {Opcode.SMSG_GUILD_PARTY_STATE,                        0x0A78}, //++
            {Opcode.SMSG_GUILD_PERMISSIONS_QUERY_RESULTS,          0x0FF9}, //--
            {Opcode.SMSG_GUILD_RANKS,                              0x0A79}, //--
            {Opcode.SMSG_GUILD_RENAMED,                            0x0E70}, //++
            {Opcode.SMSG_GUILD_REPUTATION_WEEKLY_CAP,              0x1A71}, //--
            {Opcode.SMSG_GUILD_REWARD_LIST,                        0x1A69}, //--
            {Opcode.SMSG_GUILD_ROSTER,                             0x0BE0}, //++
            {Opcode.SMSG_GUILD_SET_GUILD_MASTER,                   0x0E69}, //--
            {Opcode.SMSG_GUILD_SEND_RANK_CHANGE,                   0x0A60}, //--
            {Opcode.SMSG_GUILD_SET_NOTE,                           0x0BE1}, //--
            {Opcode.SMSG_GUILD_XP,                                 0x0AF0}, //+-
            {Opcode.SMSG_GUILD_XP_GAIN,                            0x0FE0}, //+-
            {Opcode.SMSG_HEALTH_UPDATE,                            0x148B}, //++
            {Opcode.SMSG_HIGHEST_THREAT_UPDATE,                    0x14AE}, //++
            {Opcode.SMSG_HOTFIX_NOTIFY_BLOB,                       0x1EBA}, //--
            {Opcode.SMSG_INCREASE_CAST_TIME_FOR_SPELL,             0x00F3}, //+-
            {Opcode.SMSG_INITIALIZE_FACTIONS,                      0x0AAA}, //++
            {Opcode.SMSG_INITIAL_SETUP,                            0x0A8B}, //++
            {Opcode.SMSG_INIT_WORLD_STATES,                        0x1560}, //--
            {Opcode.SMSG_INSPECT_HONOR_STATS,                      0x1A1E}, //++ pair 19C3
            {Opcode.SMSG_INSPECT_RATED_BG_STATS,                   0x041F}, //++ pair 0882
            {Opcode.SMSG_INSPECT_TALENT,                           0x1842}, //++
            {Opcode.SMSG_INSTANCE_INFO,                            0x16BF}, //++
            {Opcode.SMSG_INSTANCE_RESET,                           0x160F}, //+-
            {Opcode.SMSG_INSTANCE_SAVE_CREATED,                    0x1EAE}, //++
            {Opcode.SMSG_INVALIDATE_PLAYER,                        0x102E}, //++
            {Opcode.SMSG_INVENTORY_CHANGE_FAILURE,                 0x0C1E}, //+-
            {Opcode.SMSG_IS_QUEST_COMPLETE_RESPONSE,               0x02EF}, //+-
            {Opcode.SMSG_ITEM_ENCHANT_TIME_UPDATE,                 0x10A2}, //++
            {Opcode.SMSG_ITEM_EXPIRE_PURCHASE_REFUND,              0x0E33}, //++
            {Opcode.SMSG_ITEM_PURCHASE_REFUND_RESULT,              0x049E}, //--
            {Opcode.SMSG_ITEM_PUSH_RESULT,                         0x0E0A}, //++
            {Opcode.SMSG_ITEM_TIME_UPDATE,                         0x18C1}, //+-
            {Opcode.SMSG_ITEM_UPGRADE_RESULT,                      0x0222}, //++
            {Opcode.SMSG_LEARNED_SPELL,                            0x129A}, //++
            {Opcode.SMSG_LEVEL_UP_INFO,                            0x1961}, //++
            {Opcode.SMSG_LFG_JOIN_RESULT,                          0x18E3}, //++
            {Opcode.SMSG_LFG_PLAYER_INFO,                          0x1861}, //++
            {Opcode.SMSG_LFG_PROPOSAL_UPDATE,                      0x1E3B}, //--
            {Opcode.SMSG_LFG_QUEUE_STATUS,                         0x1006}, //++
            {Opcode.SMSG_LFG_UPDATE_STATUS,                        0x0C2E}, //++
            {Opcode.SMSG_LFG_ROLE_CHECK_UPDATE,                    0x12BB}, //++
            {Opcode.SMSG_LF_GUILD_APPLICATIONS_LIST_CHANGED,       0x1A70}, //--
            {Opcode.SMSG_LF_GUILD_APPLICATIONS_LIST_UPDATED,       0x0AE0}, //++
            {Opcode.SMSG_LF_GUILD_BROWSE_UPDATED,                  0x0F69}, //+-
            {Opcode.SMSG_LOAD_CUF_PROFILES,                        0x0E32}, //++
            {Opcode.SMSG_LOAD_EQUIPMENT_SET,                       0x18E2}, //++
            {Opcode.SMSG_LOGIN_SET_TIME_SPEED,                     0x082B}, //++
            {Opcode.SMSG_LOGIN_VERIFY_WORLD,                       0x1C0F}, //+-
            {Opcode.SMSG_LOGOUT_CANCEL_ACK,                        0x0AAF}, //++
            {Opcode.SMSG_LOGOUT_COMPLETE,                          0x142F}, //+-
            {Opcode.SMSG_LOGOUT_RESPONSE,                          0x008F}, //++
            {Opcode.SMSG_LOG_XP_GAIN,                              0x1E9A}, //--
            {Opcode.SMSG_LOOT_CLEAR_MONEY,                         0x1632}, //++
            {Opcode.SMSG_LOOT_LIST,                                0x1C3F}, //++
            {Opcode.SMSG_LOOT_MASTER_LIST,                         0x02BF}, //+-
            {Opcode.SMSG_LOOT_MONEY_NOTIFY,                        0x14C0}, //++
            {Opcode.SMSG_LOOT_RELEASE,                             0x123F}, //+-
            {Opcode.SMSG_LOOT_REMOVED,                             0x0C3E}, //++
            {Opcode.SMSG_LOOT_RESPONSE,                            0x128A}, //++
            {Opcode.SMSG_LOOT_RESPONSE_COUNT,                      0x0C32}, //++
            {Opcode.SMSG_LOOT_ROLL,                                0x1840}, //++
            {Opcode.SMSG_LOOT_ROLL_WON,                            0x0A3A}, //++
            {Opcode.SMSG_LOOT_ROLLS_COMPLETE,                      0x101B}, //++
            {Opcode.SMSG_LOSS_OF_CONTROL_AURA_UPDATE,              0x049A}, //++
            {Opcode.SMSG_MAIL_COMMAND_RESULT,                      0x1A9B}, //+-
            {Opcode.SMSG_MAIL_LIST_RESULT,                         0x1C0B}, //+-
            {Opcode.SMSG_MAP_OBJECTIVES_INIT,                      0x023F}, //--
            {Opcode.SMSG_MINIMAP_PING,                             0x168F}, //+-
            {Opcode.SMSG_MIRROR_IMAGE_COMPONENTED_DATA,            0x04D9}, //++ pair CMSG 02A3
            {Opcode.SMSG_MIRROR_IMAGE_CREATURE_DATA,               0x04D0}, //--
            {Opcode.SMSG_MISSILE_CANCEL,                           0x1203}, //++
            {Opcode.SMSG_MODIFY_COOLDOWN,                          0x1E2E}, //++
            {Opcode.SMSG_MOTD,                                     0x183B}, //++
            {Opcode.SMSG_MOUNT_SPECIAL_ANIM,                       0x003A}, //++
            {Opcode.SMSG_MOVE_APPLY_MOVEMENT_FORCE,                0x1DBE}, //++
            {Opcode.SMSG_MOVE_COLLISION_DISABLE,                   0x15B8}, //+-
            {Opcode.SMSG_MOVE_COLLISION_ENABLE,                    0x1826}, //+-
            {Opcode.SMSG_MOVE_FEATHER_FALL,                        0x0C60}, //++
            {Opcode.SMSG_MOVE_GRAVITY_DISABLE,                     0x159F}, //++
            {Opcode.SMSG_MOVE_GRAVITY_ENABLE,                      0x0A27}, //++
            {Opcode.SMSG_MOVE_KNOCK_BACK,                          0x0562}, //++
            {Opcode.SMSG_MOVE_LAND_WALK,                           0x086A}, //++
            {Opcode.SMSG_MOVE_NORMAL_FALL,                         0x08E0}, //++
            {Opcode.SMSG_MOVE_REMOVE_MOVEMENT_FORCE,               0x0341}, //++
            {Opcode.SMSG_MOVE_ROOT,                                0x15AE}, //++
            {Opcode.SMSG_MOVE_SET_ACTIVE_MOVER,                    0x0C6D}, //+-
            {Opcode.SMSG_MOVE_SET_CAN_FLY,                         0x178D}, //++
            {Opcode.SMSG_MOVE_SET_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY, 0x0A03}, //++
            {Opcode.SMSG_MOVE_SET_COLLISION_HEIGHT,                0x0250}, //++
            {Opcode.SMSG_MOVE_SET_COMPOUND_STATE,                  0x0061}, //++
            {Opcode.SMSG_MOVE_SET_FLIGHT_BACK_SPEED,               0x0319}, //+-
            {Opcode.SMSG_MOVE_SET_FLIGHT_SPEED,                    0x006E}, //++
            {Opcode.SMSG_MOVE_SET_HOVERING,                        0x1802}, //+-
            {Opcode.SMSG_MOVE_SET_IGNORE_MOVEMENT_FORCES,          0x1065}, //+-
            {Opcode.SMSG_MOVE_SET_PITCH_RATE,                      0x17AB}, //+-
            {Opcode.SMSG_MOVE_SET_RUN_BACK_SPEED,                  0x0A83}, //++
            {Opcode.SMSG_MOVE_SET_RUN_SPEED,                       0x184C}, //++
            {Opcode.SMSG_MOVE_SET_SWIM_BACK_SPEED,                 0x0962}, //+-
            {Opcode.SMSG_MOVE_SET_SWIM_SPEED,                      0x0817}, //++
            {Opcode.SMSG_MOVE_SET_TURN_RATE,                       0x0069}, //+-
            {Opcode.SMSG_MOVE_SET_WALK_SPEED,                      0x0469}, //++
            {Opcode.SMSG_MOVE_SKIP_TIME,                           0x0A02}, //+-
            {Opcode.SMSG_MOVE_TELEPORT,                            0x0B39}, //++
            {Opcode.SMSG_MOVE_UNSET_IGNORE_MOVEMENT_FORCES,        0x0D61}, //+-
            {Opcode.SMSG_MOVE_UNROOT,                              0x1FAE}, //++
            {Opcode.SMSG_MOVE_UNSET_CAN_FLY,                       0x0162}, //++
            {Opcode.SMSG_MOVE_UNSET_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY, 0x0868}, //++
            {Opcode.SMSG_MOVE_UNSET_HOVERING,                      0x02D3}, //+-
            {Opcode.SMSG_MOVE_UPDATE,                              0x1A32}, //++
            {Opcode.SMSG_MOVE_UPDATE_COLLISION_HEIGHT,             0x1812}, //++
            {Opcode.SMSG_MOVE_UPDATE_FLIGHT_BACK_SPEED,            0x036A}, //--
            {Opcode.SMSG_MOVE_UPDATE_FLIGHT_SPEED,                 0x00E1}, //++
            {Opcode.SMSG_MOVE_UPDATE_KNOCK_BACK,                   0x0251}, //++
            {Opcode.SMSG_MOVE_UPDATE_PITCH_RATE,                   0x09E2}, //--
            {Opcode.SMSG_MOVE_UPDATE_APPLY_MOVEMENT_FORCE,         0x0AB6}, //++
            {Opcode.SMSG_MOVE_UPDATE_REMOVE_MOVEMENT_FORCE,        0x1464}, //++
            {Opcode.SMSG_MOVE_UPDATE_RUN_BACK_SPEED,               0x08A3}, //++
            {Opcode.SMSG_MOVE_UPDATE_RUN_SPEED,                    0x158E}, //++
            {Opcode.SMSG_MOVE_UPDATE_SWIM_BACK_SPEED,              0x025A}, //--
            {Opcode.SMSG_MOVE_UPDATE_SWIM_SPEED,                   0x01E2}, //++
            {Opcode.SMSG_MOVE_UPDATE_TELEPORT,                     0x15A9}, //++
            {Opcode.SMSG_MOVE_UPDATE_TURN_RATE,                    0x0D62}, //--
            {Opcode.SMSG_MOVE_UPDATE_WALK_SPEED,                   0x0047}, //++
            {Opcode.SMSG_MOVE_WATER_WALK,                          0x1F9A}, //++
            {Opcode.SMSG_NEW_TAXI_PATH,                            0x141B}, //++
            {Opcode.SMSG_NEW_WORLD,                                0x1C3B}, //++
            {Opcode.SMSG_NEW_WORLD_ABORT,                          0x0C1B}, //++
            {Opcode.SMSG_NOTIFICATION,                             0x0C2A}, //+-
            {Opcode.SMSG_NOTIFY_DEST_LOC_SPELL_CAST,               0x1E0E}, //--
            {Opcode.SMSG_NOTIFY_MISSILE_TRAJECTORY_COLLISION,      0x120A}, //++
            {Opcode.SMSG_NULL_0C9A,                                0x0C9A}, //++
            {Opcode.SMSG_NULL_0E2B,                                0x0E2B}, //++
            {Opcode.SMSG_NULL_0E8B,                                0x0E8B}, //++
            {Opcode.SMSG_NULL_1313,                                0x1313}, //++
            {Opcode.SMSG_ON_CANCEL_EXPECTED_RIDE_VEHICLE_AURA,     0x1A2A}, //++
            {Opcode.SMSG_ON_MONSTER_MOVE,                          0x1A07}, //++
            {Opcode.SMSG_OVERRIDE_LIGHT,                           0x068A}, //--
            {Opcode.SMSG_PARTY_COMMAND_RESULT,                     0x0F86}, //+-
            {Opcode.SMSG_PARTY_KILL_LOG,                           0x048A}, //++
            {Opcode.SMSG_PARTY_MEMBER_STATS,                       0x0A9A}, //+-
            {Opcode.SMSG_PETITION_ALREADY_SIGNED,                  0x0286}, //--
            {Opcode.SMSG_PETITION_QUERY_RESPONSE,                  0x1083}, //--
            {Opcode.SMSG_PETITION_RENAME_RESPONSE,                 0x082A}, //--
            {Opcode.SMSG_PETITION_SHOW_LIST,                       0x10A3}, //--
            {Opcode.SMSG_PETITION_SHOW_SIGNATURES,                 0x00AA}, //--
            {Opcode.SMSG_PETITION_SIGN_RESULTS,                    0x06AE}, //--
            {Opcode.SMSG_PET_ACTION_FEEDBACK,                      0x080E}, //++
            {Opcode.SMSG_PET_ACTION_SOUND,                         0x15E2}, //++
            {Opcode.SMSG_PET_ADDED,                                0x123A}, //+-
            {Opcode.SMSG_PET_CAST_FAILED,                          0x149B}, //++
            {Opcode.SMSG_PET_CLEAR_SPELLS,                         0x0C59}, //++
            {Opcode.SMSG_PET_DISMISS_SOUND,                        0x1ABB}, //++
            {Opcode.SMSG_PET_GOD_MODE,                             0x1940}, //+-
            {Opcode.SMSG_PET_GUIDS,                                0x1227}, //++
            {Opcode.SMSG_PET_MODE,                                 0x163F}, //++
            {Opcode.SMSG_PET_SPELLS_MESSAGE,                       0x095A}, //++
            {Opcode.SMSG_PHASE_SHIFT_CHANGE,                       0x02A2}, //++
            {Opcode.SMSG_PLAYED_TIME,                              0x11E2}, //+-
            {Opcode.SMSG_PLAYER_BOUND,                             0x1B60}, //+-
            {Opcode.SMSG_PLAYER_SKINNED,                           0x1463}, //++
            {Opcode.SMSG_PLAYER_VEHICLE_DATA,                      0x0861}, //++
            {Opcode.SMSG_PLAY_MUSIC,                               0x0023}, //++
            {Opcode.SMSG_PLAY_OBJECT_SOUND,                        0x1443}, //++
            {Opcode.SMSG_PLAY_ONE_SHOT_ANIM_KIT,                   0x043E}, //++
            {Opcode.SMSG_PLAY_SCENE,                               0x1C3A}, //++
            {Opcode.SMSG_PLAY_SOUND,                               0x102A}, //++
            {Opcode.SMSG_PLAY_SPELL_VISUAL,                        0x061E}, //++
            {Opcode.SMSG_PLAY_SPELL_VISUAL_KIT,                    0x11E3}, //++
            {Opcode.SMSG_PONG,                                     0x1969}, //-+
            {Opcode.SMSG_POWER_UPDATE,                             0x109F}, //++
            {Opcode.SMSG_PRE_RESSURECT,                            0x19C0}, //++
            {Opcode.SMSG_PROC_RESIST,                              0x12BE}, //++
            {Opcode.SMSG_PROPOSE_LEVEL_GRANT,                      0x109A}, //++
            {Opcode.SMSG_PVP_CREDIT,                               0x100A}, //++
            {Opcode.SMSG_PVP_LOG_DATA,                             0x1E8F}, //--
            {Opcode.SMSG_PVP_OPTIONS_ENABLED,                      0x080A}, //++ pair 0A22
            {Opcode.SMSG_PVP_SEASON,                               0x069B}, //++
            {Opcode.SMSG_QUERY_CREATURE_RESPONSE,                  0x048B}, //--
            {Opcode.SMSG_QUERY_GAME_OBJECT_RESPONSE,               0x06BF}, //++
            {Opcode.SMSG_QUERY_GUILD_INFO_RESPONSE,                0x1B79}, //++
            {Opcode.SMSG_QUERY_ITEM_TEXT_RESPONSE,                 0x1134}, //++ pair 0123
            {Opcode.SMSG_QUERY_NEXT_MAIL_TIME,                     0x089B}, //++ pair 077B
            {Opcode.SMSG_QUERY_NPC_TEXT_RESPONSE,                  0x140A}, //+-
            {Opcode.SMSG_QUERY_PAGE_TEXT_RESPONSE,                 0x081E}, //+-
            {Opcode.SMSG_QUERY_PET_NAME_RESPONSE,                  0x0ABE}, //++
            {Opcode.SMSG_QUERY_PLAYER_NAME_RESPONSE,               0x169B}, //++
            {Opcode.SMSG_QUERY_QUEST_INFO_RESPONSE,                0x0276}, //+-
            {Opcode.SMSG_QUERY_TIME_RESPONSE,                      0x100F}, //++
            {Opcode.SMSG_QUEST_CONFIRM_ACCEPT,                     0x13C7}, //+-
            {Opcode.SMSG_QUEST_FORCE_REMOVED,                      0x07C5}, //+-
            {Opcode.SMSG_QUEST_GIVER_INVALID_QUEST,                0x027D}, //++ pair 12F0 or 1DAE
            {Opcode.SMSG_QUEST_GIVER_OFFER_REWARD_MESSAGE,         0x074F}, //++
            {Opcode.SMSG_QUEST_GIVER_QUEST_COMPLETE,               0x0346}, //++
            {Opcode.SMSG_QUEST_GIVER_QUEST_DETAILS,                0x134C}, //++
            {Opcode.SMSG_QUEST_GIVER_QUEST_FAILED,                 0x12DE}, //+-
            {Opcode.SMSG_QUEST_GIVER_QUEST_LIST_MESSAGE,           0x02D4}, //+-
            {Opcode.SMSG_QUEST_GIVER_REQUEST_ITEMS,                0x0277}, //++
            {Opcode.SMSG_QUEST_GIVER_STATUS,                       0x1275}, //++
            {Opcode.SMSG_QUEST_GIVER_STATUS_MULTIPLE,              0x06CE}, //++
            {Opcode.SMSG_QUEST_LOG_FULL,                           0x07FD}, //+-
            {Opcode.SMSG_QUEST_NPC_QUERY_RESPONSE,                 0x036D}, //++
            {Opcode.SMSG_QUEST_POI_QUERY_RESPONSE,                 0x067F}, //++
            {Opcode.SMSG_QUEST_PUSH_RESULT,                        0x074D}, //+-
            {Opcode.SMSG_QUEST_UPDATE_ADD_CREDIT_SIMPLE,           0x07F5}, //++
            {Opcode.SMSG_QUEST_UPDATE_ADD_PVP_CREDIT,              0x0256}, //+-
            {Opcode.SMSG_QUEST_UPDATE_ADD_KILL,                    0x1645}, //++
            {Opcode.SMSG_QUEST_UPDATE_COMPLETE,                    0x0776}, //++
            {Opcode.SMSG_QUEST_UPDATE_FAILED,                      0x07DD}, //+-
            {Opcode.SMSG_QUEST_UPDATE_FAILED_TIMER,                0x06FF}, //+-
            {Opcode.SMSG_RAID_DIFFICULTY_SET,                      0x0591}, //+-
            {Opcode.SMSG_RAID_INSTANCE_MESSAGE,                    0x0CAF}, //++
            {Opcode.SMSG_RAID_MARKERS_CHANGED,                     0x0283}, //++
            {Opcode.SMSG_RAID_TARGET_UPDATE,                       0x008A}, //++
            {Opcode.SMSG_RANDOM_ROLL,                              0x141A}, //+-
            {Opcode.SMSG_READY_CHECK_COMPLETED,                    0x15C2}, //+-
            {Opcode.SMSG_READY_CHECK_RESPONSE,                     0x02AF}, //+-
            {Opcode.SMSG_READY_CHECK_STARTED,                      0x1C8E}, //+-
            {Opcode.SMSG_READ_ITEM_RESULT_OK,                      0x0305}, //++
            {Opcode.SMSG_REALM_QUERY_RESPONSE,                     0x063E}, //++
            {Opcode.SMSG_RECEIVED_MAIL,                            0x182B}, //+-
            {Opcode.SMSG_REFORGE_RESULT,                           0x141E}, //++
            {Opcode.SMSG_REFER_A_FRIEND_FAILURE,                   0x021E}, //--
            {Opcode.SMSG_REFRESH_SPELL_HISTORY,                    0x0170}, //++
            {Opcode.SMSG_REPORT_PVP_AFK_RESULT,                    0x18BE}, //++
            {Opcode.SMSG_REQUEST_CEMETERY_LIST_RESPONSE,           0x042A}, //++ pair 06E4
            {Opcode.SMSG_REQUEST_PVP_REWARDS_RESPONSE,             0x08AA}, //++
            {Opcode.SMSG_RESET_RANGED_COMBAT_TIMER,                0x0002}, //++
            {Opcode.SMSG_RESPEC_WIPE_CONFIRM,                      0x02AB}, //+-
            {Opcode.SMSG_RESPOND_INSPECT_ACHIEVEMENTS,             0x009E}, //++ pair 0373
            {Opcode.SMSG_RESUME_CAST_BAR,                          0x01D2}, //++
            {Opcode.SMSG_RESUME_COMMS,                             0x0969}, //--
            {Opcode.SMSG_RESUME_TOKEN,                             0x18BA}, //++
            {Opcode.SMSG_RESYNC_RUNES,                             0x15E3}, //++
            {Opcode.SMSG_RESURRECT_REQUEST,                        0x1062}, //++
            {Opcode.SMSG_ROLE_POLL_BEGIN,                          0x1A1F}, //++
            {Opcode.SMSG_SELL_ITEM,                                0x048E}, //+-
            {Opcode.SMSG_SEND_KNOWN_SPELLS,                        0x045A}, //++
            {Opcode.SMSG_SEND_RAID_TARGET_UPDATE_SINGLE,           0x160B}, //++
            {Opcode.SMSG_SEND_SPELL_CHARGES,                       0x10F1}, //++
            {Opcode.SMSG_SEND_SPELL_HISTORY,                       0x0050}, //++
            {Opcode.SMSG_SEND_UNLEARN_SPELLS,                      0x0D51}, //++
            {Opcode.SMSG_SERVER_FIRST_ACHIEVEMENT,                 0x028B}, //--
            {Opcode.SMSG_SETUP_CURRENCY,                           0x1A8B}, //++
            {Opcode.SMSG_SET_AI_ANIM_KIT,                          0x1E12}, //++
            {Opcode.SMSG_SET_ANIM_TIER,                            0x1C0E}, //++
            {Opcode.SMSG_SET_DF_FAST_LAUNCH_RESULT,                0x1041}, //+-
            {Opcode.SMSG_SET_DUNGEON_DIFFICULTY,                   0x1283}, //+-
            {Opcode.SMSG_SET_FACTION_AT_WAR,                       0x0C9B}, //+-
            {Opcode.SMSG_SET_FACTION_NOT_VISIBLE,                  0x1C2B}, //--
            {Opcode.SMSG_SET_FACTION_STANDING,                     0x10AA}, //+-
            {Opcode.SMSG_SET_FACTION_VISIBLE,                      0x1E8E}, //++
            {Opcode.SMSG_SET_FLAT_SPELL_MODIFIER,                  0x10F2}, //++
            {Opcode.SMSG_SET_FORCED_REACTIONS,                     0x068F}, //++
            {Opcode.SMSG_SET_ITEM_PURCHASE_DATA,                   0x1C9A}, //--
            {Opcode.SMSG_SET_PCT_SPELL_MODIFIER,                   0x09D3}, //++
            {Opcode.SMSG_SET_PLAYER_DECLINED_NAMES_RESULT,         0x180E}, //++
            {Opcode.SMSG_SET_PLAY_HOVER_ANIM,                      0x069F}, //++
            {Opcode.SMSG_SET_PROFICIENCY,                          0x1440}, //+-
            {Opcode.SMSG_SET_QUEST_COMPLETED_BIT,                  0x0354}, //++
            {Opcode.SMSG_SET_TIME_ZONE_INFORMATION,                0x19C1}, //++
            {Opcode.SMSG_SET_VIGNETTE,                             0x0CBE}, //++
            {Opcode.SMSG_SHOW_BANK,                                0x0007}, //++
            {Opcode.SMSG_SHOW_NEUTRAL_PLAYER_FACTION_SELECT_UI,    0x15E0}, //++
            {Opcode.SMSG_SHOW_TAXI_NODES,                          0x1E1A}, //++
            {Opcode.SMSG_SHOW_TRADE_SKILL_RESPONSE,                0x00BA}, //++
            {Opcode.SMSG_SPELL_CHANNEL_START,                      0x10F9}, //++
            {Opcode.SMSG_SPELL_CHANNEL_UPDATE,                     0x11D9}, //+-
            {Opcode.SMSG_SPELL_COOLDOWN,                           0x0452}, //++
            {Opcode.SMSG_SPELL_DAMAGE_SHIELD,                      0x05F3}, //++
            {Opcode.SMSG_SPELL_DELAYED,                            0x087A}, //++
            {Opcode.SMSG_SPELL_DISPELL_LOG,                        0x0DF9}, //+-
            {Opcode.SMSG_SPELL_ENERGIZE_LOG,                       0x0D79}, //+-
            {Opcode.SMSG_SPELL_EXECUTE_LOG,                        0x00D8}, //+-
            {Opcode.SMSG_SPELL_FAILED_OTHER,                       0x040B}, //++
            {Opcode.SMSG_SPELL_FAILURE,                            0x04AF}, //++
            {Opcode.SMSG_SPELL_GO,                                 0x09D8}, //++
            {Opcode.SMSG_SPELL_HEAL_LOG,                           0x09FB}, //+-
            {Opcode.SMSG_SPELL_INSTAKILL_LOG,                      0x09F8}, //++
            {Opcode.SMSG_SPELL_INTERRUPT_LOG,                      0x1851}, //++
            {Opcode.SMSG_SPELL_MISS_LOG,                           0x1570}, //++
            {Opcode.SMSG_SPELL_NON_MELEE_DAMAGE_LOG,               0x1450}, //++
            {Opcode.SMSG_SPELL_OR_DAMAGE_IMMUNE,                   0x08FB}, //++
            {Opcode.SMSG_SPELL_PERIODIC_AURA_LOG,                  0x0CF2}, //++
            {Opcode.SMSG_SPELL_START,                              0x107A}, //++
            {Opcode.SMSG_SPELL_UPDATE_CHAIN_TARGETS,               0x0D52}, //++
            {Opcode.SMSG_SPIRIT_HEALER_CONFIRM,                    0x1EAA}, //++
            {Opcode.SMSG_SPLINE_MOVE_COLLISION_DISABLE,            0x186F}, //+-
            {Opcode.SMSG_SPLINE_MOVE_COLLISION_ENABLE,             0x006B}, //+-
            {Opcode.SMSG_SPLINE_MOVE_GRAVITY_DISABLE,              0x0845}, //++
            {Opcode.SMSG_SPLINE_MOVE_GRAVITY_ENABLE,               0x0865}, //++
            {Opcode.SMSG_SPLINE_MOVE_ROOT,                         0x0728}, //++
            {Opcode.SMSG_SPLINE_MOVE_SET_FEATHER_FALL,             0x1893}, //+-
            {Opcode.SMSG_SPLINE_MOVE_SET_FLIGHT_BACK_SPEED,        0x0B28}, //+-
            {Opcode.SMSG_SPLINE_MOVE_SET_FLIGHT_SPEED,             0x1DAB}, //++
            {Opcode.SMSG_SPLINE_MOVE_SET_FLYING,                   0x1046}, //++
            {Opcode.SMSG_SPLINE_MOVE_SET_HOVER,                    0x0258}, //+-
            {Opcode.SMSG_SPLINE_MOVE_SET_LAND_WALK,                0x18B6}, //+-
            {Opcode.SMSG_SPLINE_MOVE_SET_NORMAL_FALL,              0x0B08}, //+-
            {Opcode.SMSG_SPLINE_MOVE_SET_PITCH_RATE,               0x0AB3}, //+-
            {Opcode.SMSG_SPLINE_MOVE_SET_RUN_BACK_SPEED,           0x1F9F}, //++
            {Opcode.SMSG_SPLINE_MOVE_SET_RUN_MODE,                 0x0B18}, //+-
            {Opcode.SMSG_SPLINE_MOVE_SET_RUN_SPEED,                0x02F1}, //++
            {Opcode.SMSG_SPLINE_MOVE_SET_SWIM_BACK_SPEED,          0x0046}, //+-
            {Opcode.SMSG_SPLINE_MOVE_SET_SWIM_SPEED,               0x1D8E}, //++
            {Opcode.SMSG_SPLINE_MOVE_SET_TURN_RATE,                0x0832}, //+-
            {Opcode.SMSG_SPLINE_MOVE_SET_WALK_MODE,                0x1865}, //+-
            {Opcode.SMSG_SPLINE_MOVE_SET_WALK_SPEED,               0x08B2}, //++
            {Opcode.SMSG_SPLINE_MOVE_SET_WATER_WALK,               0x1823}, //+-
            {Opcode.SMSG_SPLINE_MOVE_START_SWIM,                   0x0F29}, //++
            {Opcode.SMSG_SPLINE_MOVE_STOP_SWIM,                    0x1798}, //+-
            {Opcode.SMSG_SPLINE_MOVE_UNROOT,                       0x01E1}, //++
            {Opcode.SMSG_SPLINE_MOVE_UNSET_FLYING,                 0x0DE2}, //+-
            {Opcode.SMSG_SPLINE_MOVE_UNSET_HOVER,                  0x0CE1}, //++
            {Opcode.SMSG_STABLE_RESULT,                            0x1613}, //++
            {Opcode.SMSG_STAND_STATE_UPDATE,                       0x1C12}, //++
            {Opcode.SMSG_START_ELAPSED_TIMERS,                     0x00AB}, //++
            {Opcode.SMSG_START_MIRROR_TIMER,                       0x0E12}, //++
            {Opcode.SMSG_START_TIMER,                              0x0E3F}, //+-
            {Opcode.SMSG_STOP_MIRROR_TIMER,                        0x1026}, //++
            {Opcode.SMSG_STREAMING_MOVIES,                         0x1843}, //++
            {Opcode.SMSG_SUPERCEDED_SPELLS,                        0x1943}, //++
            {Opcode.SMSG_SUSPEND_COMMS,                            0x1D48}, //+-
            {Opcode.SMSG_TABARD_VENDOR_ACTIVATE,                   0x0A3E}, //+-
            {Opcode.SMSG_TALENTS_INVOLUNTARILY_RESET,              0x088A}, //+-
            {Opcode.SMSG_TAXI_NODE_STATUS,                         0x169E}, //++ pair CMSG 02E1
            {Opcode.SMSG_TEXT_EMOTE,                               0x002E}, //++
            {Opcode.SMSG_THREAT_CLEAR,                             0x180B}, //++
            {Opcode.SMSG_THREAT_REMOVE,                            0x1960}, //++
            {Opcode.SMSG_THREAT_UPDATE,                            0x0632}, //++
            {Opcode.SMSG_TIME_ADJUSTMENT,                          0x04AA}, //+-
            {Opcode.SMSG_TIME_SYNC_REQUEST,                        0x1A8F}, //++
            {Opcode.SMSG_TITLE_EARNED,                             0x068E}, //++
            {Opcode.SMSG_TITLE_LOST,                               0x12BF}, //--
            {Opcode.SMSG_TOTEM_CREATED,                            0x1C8F}, //++
            {Opcode.SMSG_TRADE_STATUS,                             0x1963}, //++
            {Opcode.SMSG_TRADE_STATUS_EXTENDED,                    0x181E}, //++
            {Opcode.SMSG_TRAINER_BUY_FAILED,                       0x042E}, //++
            {Opcode.SMSG_TRAINER_LIST,                             0x189F}, //+-
            {Opcode.SMSG_TRANSFER_ABORTED,                         0x0C8F}, //++
            {Opcode.SMSG_TRANSFER_PENDING,                         0x061B}, //++
            {Opcode.SMSG_TRIGGER_CINEMATIC,                        0x0B01}, //+-
            {Opcode.SMSG_TRIGGER_MOVIE,                            0x1C2E}, //+-
            {Opcode.SMSG_TURN_IN_PETITION_RESULT,                  0x0E13}, //+-
            {Opcode.SMSG_TUTORIAL_FLAGS,                           0x1B90}, //++
            {Opcode.SMSG_UI_TIME,                                  0x0027}, //+-
            {Opcode.SMSG_UNK_000F,                                 0x000f}, //++
            {Opcode.SMSG_UNK_001B,                                 0x001B}, //++
            {Opcode.SMSG_UNK_0332,                                 0x0332}, //++
            {Opcode.SMSG_UNK_043A,                                 0x043A}, //+-
            {Opcode.SMSG_UNK_0470,                                 0x0470}, //+- spell
            {Opcode.SMSG_UNK_0B81,                                 0x0B81}, //++ pair 02DA auction
            {Opcode.SMSG_UNK_0C44,                                 0x0C44}, //+-
            {Opcode.SMSG_UNK_0E8E,                                 0x0E8E}, //+-
            {Opcode.SMSG_UNK_0EAA,                                 0x0EAA}, //++
            {Opcode.SMSG_UNK_0EAB,                                 0x0EAB}, //++
            {Opcode.SMSG_UNK_103E,                                 0x103E}, //++
            {Opcode.SMSG_UNK_10BA,                                 0x10BA}, //+-
            {Opcode.SMSG_UNK_10D8,                                 0x10D8}, //+- spell
            {Opcode.SMSG_UNK_1206,                                 0x1206}, //++
            {Opcode.SMSG_UNK_142B,                                 0x142B}, //+-
            {Opcode.SMSG_UNK_14D2,                                 0x14D2}, //+- spell
            {Opcode.SMSG_UNK_162A,                                 0x162A}, //++
            {Opcode.SMSG_UNK_188F,                                 0x188F}, //++
            {Opcode.SMSG_UNK_1904,                                 0x1904}, //++
            {Opcode.SMSG_UNK_1E1B,                                 0x1E1B}, //++ levelup 90
            {Opcode.SMSG_UNK_1E3F,                                 0x1E3F}, //+-
            {Opcode.SMSG_UNLEARNED_SPELLS,                         0x14C3}, //+-
            {Opcode.SMSG_UPDATE_ACCOUNT_DATA,                      0x0AAE}, //++
            {Opcode.SMSG_UPDATE_ACTION_BUTTONS,                    0x081A}, //++
            {Opcode.SMSG_UPDATE_COMBO_POINTS,                      0x082F}, //++
            {Opcode.SMSG_UPDATE_CURRENCY,                          0x129E}, //++
            {Opcode.SMSG_UPDATE_CURRENCY_WEEK_LIMIT,               0x0E2A}, //++
            {Opcode.SMSG_UPDATE_DUNGEON_ENCOUNTER_FOR_LOOT,        0x1863}, //++
            {Opcode.SMSG_UPDATE_INSTANCE_OWNERSHIP,                0x10E0}, //--
            {Opcode.SMSG_UPDATE_LAST_INSTANCE,                     0x189B}, //+-
            {Opcode.SMSG_UPDATE_OBJECT,                            0x1792}, //--
            {Opcode.SMSG_UPDATE_TALENT_DATA,                       0x0A9B}, //++
            {Opcode.SMSG_UPDATE_WORLD_STATE,                       0x121B}, //++
            {Opcode.SMSG_VENDOR_INVENTORY,                         0x1AAE}, //-+
            {Opcode.SMSG_VOICE_CHAT_STATUS,                        0x10E2}, //+-
            {Opcode.SMSG_VOID_ITEM_SWAP_RESPONSE,                  0x1EBF}, //--
            {Opcode.SMSG_VOID_STORAGE_CONTENTS,                    0x008B}, //--
            {Opcode.SMSG_VOID_STORAGE_FAILED,                      0x1569}, //--
            {Opcode.SMSG_VOID_STORAGE_TRANSFER_CHANGES,            0x14BA}, //--
            {Opcode.SMSG_VOID_TRANSFER_RESULT,                     0x1C9E}, //+-
            {Opcode.SMSG_WARDEN_DATA,                              0x0C0A}, //-- ??
            {Opcode.SMSG_WARGAME_REQUEST_SENT,                     0x0CAE}, //++
            {Opcode.SMSG_WEATHER,                                  0x06AB}, //++
            {Opcode.SMSG_WEEKLY_SPELL_USAGE,                       0x00F9}, //++
            {Opcode.SMSG_WEEKLY_SPELL_USAGE_UPDATE,                0x117A}, //+-
            {Opcode.SMSG_WHO,                                      0x161B}, //+-
            {Opcode.SMSG_WORLD_SERVER_INFO,                        0x0082}, //++
            {Opcode.SMSG_XP_GAIN_ABORTED,                          0x1A2B}, //++ hunter pet opcode
            {Opcode.SMSG_ZONE_UNDER_ATTACK,                        0x10C2}, //++
        };

        private static readonly BiDictionary<Opcode, int> MiscOpcodes = new BiDictionary<Opcode, int>
        {
            {Opcode.MSG_MOVE_WORLDPORT_ACK,                        0x1FAD}, //++
            {Opcode.MSG_VERIFY_CONNECTIVITY,                       0x4F57}, //++
        };
    }
}
