using WowPacketParser.Misc;

namespace WowPacketParser.Enums.Version.V5_0_5_16048
{
    public static class Opcodes_5_0_5
    {
        public static BiDictionary<Opcode, int> Opcodes(Direction direction)
        {
            switch (direction)
            {
                case Direction.ClientToServer:
                case Direction.BNClientToServer:
                    return ClientOpcodes;
                case Direction.ServerToClient:
                case Direction.BNServerToClient:
                    return ServerOpcodes;
                default:
                    return MiscOpcodes;
            }
        }

        private static readonly BiDictionary<Opcode, int> ClientOpcodes = new BiDictionary<Opcode, int>
        {
            {Opcode.CMSG_QUERY_CREATURE, 0x0884},

            {Opcode.CMSG_ACCEPT_LEVEL_GRANT, 0x0902},
            {Opcode.CMSG_ACCEPT_TRADE, 0x0194},
            {Opcode.CMSG_ACTIVATE_TAXI, 0x0D28},
            {Opcode.CMSG_ACTIVATE_TAXI_EXPRESS, 0x0CF7},
            {Opcode.CMSG_ADDON_REGISTERED_PREFIXES, 0x0789},
            {Opcode.CMSG_ADD_FRIEND, 0x0975},
            {Opcode.CMSG_ADD_IGNORE, 0x0D48},
            //{Opcode.CMSG_CHAT_CHANNEL_VOICE_OFF, 0x08BF},
            {Opcode.CMSG_ALTER_APPEARANCE, 0x0D72},
            {Opcode.CMSG_AREA_TRIGGER, 0x0272},
            {Opcode.CMSG_AREA_SPIRIT_HEALER_QUERY, 0x0953},
            {Opcode.CMSG_AREA_SPIRIT_HEALER_QUEUE, 0x0CB7},
            {Opcode.CMSG_ARENA_TEAM_ACCEPT, 0x0C69},
            {Opcode.CMSG_ARENA_TEAM_CREATE, 0x034A},
            {Opcode.CMSG_ARENA_TEAM_DECLINE, 0x08CB},
            {Opcode.CMSG_ARENA_TEAM_DISBAND, 0x097A},
            {Opcode.CMSG_ARENA_TEAM_INVITE, 0x0C61},
            {Opcode.CMSG_ARENA_TEAM_LEADER, 0x0CCC},
            {Opcode.CMSG_ARENA_TEAM_LEAVE, 0x09E8},
            {Opcode.CMSG_ARENA_TEAM_QUERY, 0x0CB5},
            {Opcode.CMSG_ARENA_TEAM_REMOVE, 0x0CEA},
            {Opcode.CMSG_ARENA_TEAM_ROSTER, 0x09D8},
            {Opcode.CMSG_ATTACK_STOP, 0x08A7},
            {Opcode.CMSG_ATTACK_SWING, 0x0C40},
            {Opcode.CMSG_AUCTION_LIST_BIDDER_ITEMS, 0x0947},
            {Opcode.CMSG_AUCTION_LIST_ITEMS, 0x0D71},
            {Opcode.CMSG_AUCTION_LIST_OWNER_ITEMS, 0x0D63},
            {Opcode.CMSG_AUCTION_LIST_PENDING_SALES, 0x096F},
            {Opcode.CMSG_AUCTION_PLACE_BID, 0x0915},
            {Opcode.CMSG_AUCTION_REMOVE_ITEM, 0x0965},
            {Opcode.CMSG_AUCTION_SELL_ITEM, 0x0CC6},
            {Opcode.CMSG_AUTH_SESSION, 0x008A},
            {Opcode.CMSG_AUTOBANK_ITEM, 0x0CC0},
            //{Opcode.CMSG_AUTO_EQUIP_GROUND_ITEM, 0x0000}, // Not found in 4.3.4
            {Opcode.CMSG_AUTO_EQUIP_ITEM, 0x0888},
            {Opcode.CMSG_AUTO_EQUIP_ITEM_SLOT, 0x0DC3},
            {Opcode.CMSG_AUTO_STORE_BAG_ITEM, 0x0D34},
            {Opcode.CMSG_AUTOSTORE_BANK_ITEM, 0x08B8},
            //{Opcode.CMSG_AUTOSTORE_GROUND_ITEM, 0x0000}, // Not found in 4.3.4
            {Opcode.CMSG_AUTOSTORE_LOOT_ITEM, 0x03D8},
            {Opcode.CMSG_AUTO_DECLINE_GUILD_INVITES, 0x0851},
            {Opcode.CMSG_BANKER_ACTIVATE, 0x0DA9},
            //{Opcode.CMSG_BATTLEFIELD_JOIN, 0x0000}, // Not found in 4.3.4
            {Opcode.CMSG_BATTLEFIELD_LEAVE, 0x0CC7},
            {Opcode.CMSG_BATTLEFIELD_LIST, 0x0058},
            {Opcode.CMSG_BF_MGR_ENTRY_INVITE_RESPONSE, 0x0745},
            {Opcode.CMSG_BF_MGR_QUEUE_EXIT_REQUEST, 0x07D2},
            {Opcode.CMSG_BF_MGR_QUEUE_INVITE_RESPONSE, 0x0793},
            {Opcode.CMSG_BF_MGR_QUEUE_REQUEST, 0x0529},
            {Opcode.CMSG_BATTLEFIELD_PORT, 0x0056},
            {Opcode.CMSG_BATTLEFIELD_REQUEST_SCORE_DATA, 0x0220},
            {Opcode.CMSG_BATTLEFIELD_STATUS, 0x004C},
            //{Opcode.CMSG_BATTLEGROUND_PLAYER_POSITIONS, 0x0}, // 0x3902 in 4.3.4
            {Opcode.CMSG_BATTLEMASTER_JOIN, 0x05F8},
            {Opcode.CMSG_BATTLEMASTER_JOIN_ARENA, 0x0530},
            {Opcode.CMSG_BATTLEMASTER_JOIN_RATED, 0x01F0},
            {Opcode.CMSG_BEGIN_TRADE, 0x0618},
            {Opcode.CMSG_BINDER_ACTIVATE, 0x090A},
            //{Opcode.CMSG_BOT_DETECTED2, 0x0000}, // Not Usefull
            {Opcode.CMSG_BUG, 0x0C6A},
            {Opcode.CMSG_BUSY_TRADE, 0x0319},
            {Opcode.CMSG_BUY_BACK_ITEM, 0x0C3B},
            {Opcode.CMSG_BUY_BANK_SLOT, 0x0968},
            {Opcode.CMSG_BUY_ITEM, 0x0D1E},
            {Opcode.CMSG_CALENDAR_ADD_EVENT, 0x0DB7},
            {Opcode.CMSG_CALENDAR_ARENA_TEAM, 0x08C9},
            {Opcode.CMSG_CALENDAR_COMPLAIN, 0x0986},
            //{Opcode.CMSG_CALENDAR_CONTEXT_EVENT_SIGNUP, 0x0000}, // Not found in 4.3.4
            {Opcode.CMSG_CALENDAR_COPY_EVENT, 0x08DD},
            {Opcode.CMSG_CALENDAR_EVENT_INVITE, 0x09BB},
            {Opcode.CMSG_CALENDAR_EVENT_MODERATOR_STATUS, 0x0C96},
            {Opcode.CMSG_CALENDAR_EVENT_REMOVE_INVITE, 0x0D0F},
            {Opcode.CMSG_CALENDAR_EVENT_RSVP, 0x09B2},
            {Opcode.CMSG_CALENDAR_EVENT_SIGN_UP, 0x0CF5},
            {Opcode.CMSG_CALENDAR_EVENT_STATUS, 0x09C5},
            {Opcode.CMSG_CALENDAR_GET_CALENDAR, 0x0868},
            {Opcode.CMSG_CALENDAR_GET_EVENT, 0x0CE5},
            {Opcode.CMSG_CALENDAR_GET_NUM_PENDING, 0x099A},
            {Opcode.CMSG_CALENDAR_GUILD_FILTER, 0x0DB4},
            {Opcode.CMSG_CALENDAR_REMOVE_EVENT, 0x0C3C},
            {Opcode.CMSG_CALENDAR_UPDATE_EVENT, 0x0818},
            {Opcode.CMSG_CANCEL_AURA, 0x0895},
            {Opcode.CMSG_CANCEL_AUTO_REPEAT_SPELL, 0x0903},
            {Opcode.CMSG_CANCEL_CAST, 0x0C66},
            {Opcode.CMSG_CANCEL_CHANNELLING, 0x09A7},
            //{Opcode.CMSG_CANCEL_GROWTH_AURA, 0x0},
            {Opcode.CMSG_CANCEL_MOUNT_AURA, 0x0DB6},
            {Opcode.CMSG_CANCEL_QUEUED_SPELL, 0x06D3},
            {Opcode.CMSG_CANCEL_TEMP_ENCHANTMENT, 0x0C8F},
            {Opcode.CMSG_CANCEL_TRADE, 0x0321},
            {Opcode.CMSG_CAST_SPELL, 0x0911},
            {Opcode.CMSG_CHANGEPLAYER_DIFFICULTY, 0x020D},
            {Opcode.CMSG_CHANGE_SEATS_ON_CONTROLLED_VEHICLE, 0x0676},
            {Opcode.CMSG_CHAT_CHANNEL_ANNOUNCEMENTS, 0x0389},
            {Opcode.CMSG_CHAT_CHANNEL_BAN, 0x07E9},
            {Opcode.CMSG_CHAT_CHANNEL_DECLINE_INVITE, 0x09CC},
            {Opcode.CMSG_CHAT_CHANNEL_DISPLAY_LIST, 0x02E4},
            {Opcode.CMSG_CHAT_CHANNEL_INVITE, 0x02AD},
            {Opcode.CMSG_CHAT_CHANNEL_KICK, 0x0785},
            {Opcode.CMSG_CHAT_CHANNEL_LIST, 0x05C8},
            {Opcode.CMSG_CHAT_CHANNEL_MODERATOR, 0x0581},
            {Opcode.CMSG_CHAT_CHANNEL_MUTE, 0x019E},
            {Opcode.CMSG_CHAT_CHANNEL_OWNER, 0x0088},
            {Opcode.CMSG_CHAT_CHANNEL_PASSWORD, 0x03A4},
            {Opcode.CMSG_CHAT_CHANNEL_SET_OWNER, 0x05E9},
            {Opcode.CMSG_CHAT_CHANNEL_SILENCE_ALL, 0x07C0},
            {Opcode.CMSG_CHAT_CHANNEL_SILENCE_VOICE, 0x006C},
            {Opcode.CMSG_CHAT_CHANNEL_UNBAN, 0x005A},
            {Opcode.CMSG_CHAT_CHANNEL_UNMODERATOR, 0x01C5},
            {Opcode.CMSG_CHAT_CHANNEL_UNMUTE, 0x02E1},
            {Opcode.CMSG_CHAT_CHANNEL_UNSILENCE_ALL, 0x03DE},
            {Opcode.CMSG_CHAT_CHANNEL_UNSILENCE_VOICE, 0x0788},
            {Opcode.CMSG_CHAT_CHANNEL_VOICE_OFF, 0x05C8},
            {Opcode.CMSG_CHAT_CHANNEL_VOICE_ON, 0x00E8},
            //{Opcode.CMSG_CHAT_CHAR_CREATE, 0x0332},
            {Opcode.CMSG_CHAR_CUSTOMIZE, 0x0C99},
            {Opcode.CMSG_CHAR_DELETE, 0x0944},
            {Opcode.CMSG_ENUM_CHARACTERS, 0x0576},
            {Opcode.CMSG_CHAR_FACTION_CHANGE, 0x09B9},
            {Opcode.CMSG_CHAR_RACE_CHANGE, 0x096C},
            {Opcode.CMSG_CHARACTER_RENAME_REQUEST, 0x0CD2},
            {Opcode.CMSG_CHAT_REPORT_FILTERED, 0x069B},
            {Opcode.CMSG_CHAT_REPORT_IGNORED, 0x00C8},
            //{Opcode.CMSG_CLEAR_CHANNEL_WATCH, 0x0}, // 0x2604 in 4.3.4
            {Opcode.CMSG_CLEAR_RAID_MARKER, 0x047C},
            {Opcode.CMSG_CLEAR_TRADE_ITEM, 0x01BC},
            {Opcode.CMSG_COMMENTATOR_ENABLE, 0x09A8},
            {Opcode.CMSG_COMMENTATOR_ENTER_INSTANCE, 0x0C60},
            {Opcode.CMSG_COMMENTATOR_EXIT_INSTANCE, 0x0DB2},
            {Opcode.CMSG_COMMENTATOR_GET_MAP_INFO, 0x0D89},
            {Opcode.CMSG_COMMENTATOR_GET_PARTY_INFO, 0x0132},
            {Opcode.CMSG_COMMENTATOR_GET_PLAYER_INFO, 0x0DD9},
            {Opcode.CMSG_COMMENTATOR_INSTANCE_COMMAND, 0x08E6},
            {Opcode.CMSG_COMMENTATOR_SKIRMISH_QUEUE_COMMAND, 0x088F},
            {Opcode.CMSG_COMMENTATOR_START_WARGAME, 0x0361},
            {Opcode.CMSG_COMPLAINT, 0x0D56},
            {Opcode.CMSG_COMPLETE_CINEMATIC, 0x0928},
            {Opcode.CMSG_COMPLETE_MOVIE, 0x0845},
            {Opcode.CMSG_CONFIRM_RESPEC_WIPE, 0x01F4},
            {Opcode.CMSG_CONNECT_TO_FAILED, 0x050E},
            {Opcode.CMSG_CONTACT_LIST, 0x0C80},
            {Opcode.CMSG_CORPSE_MAP_POSITION_QUERY, 0x05B2},
            {Opcode.CMSG_CORPSE_QUERY, 0x020C},
            //{Opcode.CMSG_QUERY_CREATURE, 0x0CA0},
            {Opcode.CMSG_DANCE_QUERY, 0x08F3},
            {Opcode.CMSG_DELETE_EQUIPMENT_SET, 0x09F2},
            {Opcode.CMSG_DEL_FRIEND, 0x093F},
            {Opcode.CMSG_DEL_IGNORE, 0x0863},
            {Opcode.CMSG_VOICE_DEL_IGNORE, 0x0DC5},
            {Opcode.CMSG_DESTROY_ITEM, 0x0C8E},
            {Opcode.CMSG_DISMISS_CONTROLLED_VEHICLE, 0x067C},
            {Opcode.CMSG_DISMISS_CRITTER, 0x087C},
            {Opcode.CMSG_DUEL_ACCEPTED, 0x0D40},
            {Opcode.CMSG_DUEL_CANCELLED, 0x0C85},
            {Opcode.CMSG_DUEL_PROPOSED, 0x0448},
            {Opcode.CMSG_EJECT_PASSENGER, 0x071D},
            {Opcode.CMSG_EMOTE, 0x0C6C},
            {Opcode.CMSG_ENABLE_TAXI_NODE, 0x08F8},
            {Opcode.CMSG_ENABLE_NAGLE, 0x03EA},
            {Opcode.CMSG_SAVE_EQUIPMENT_SET, 0x0C87},
            {Opcode.CMSG_EQUIPMENT_SET_USE, 0x0D95},
            {Opcode.CMSG_FAR_SIGHT, 0x0991},
            //{Opcode.CMSG_FORCE_MOVE_ROOT_ACK, 0x0000}, // Deprecated
            //{Opcode.CMSG_FORCE_MOVE_UNROOT_ACK, 0x0000}, // Deprecated
            {Opcode.CMSG_GAME_OBJ_REPORT_USE, 0x0838},
            {Opcode.CMSG_GAME_OBJ_USE, 0x0C92},
            //{Opcode.CMSG_GAMESPEED_SET, 0x0000}, // Not found in 4.3.4
            //{Opcode.CMSG_GAMETIME_SET, 0x0000}, // Not found in 4.3.4
            //{Opcode.CMSG_GETDEATHBINDZONE, 0x0000}, // Not found in 4.3.4
            {Opcode.CMSG_MAIL_GET_LIST, 0x0CC4},
            {Opcode.CMSG_GET_MIRROR_IMAGE_DATA, 0x0D87},
            //{Opcode.CMSG_GHOST, 0x0000}, // Not found in 4.3.4
            {Opcode.CMSG_GM_TICKET_RESPONSE_RESOLVE, 0x0C23},
            {Opcode.CMSG_GM_SURVEY_SUBMIT, 0x096B},
            {Opcode.CMSG_GM_TICKET_CREATE, 0x08FE},
            {Opcode.CMSG_GM_TICKET_DELETE_TICKET, 0x0DD7},
            {Opcode.CMSG_GM_TICKET_GET_TICKET, 0x08A2},
            {Opcode.CMSG_GM_TICKET_GET_SYSTEM_STATUS, 0x083A},
            {Opcode.CMSG_GM_TICKET_UPDATE_TEXT, 0x0D14},
            //{Opcode.CMSG_GM_INVIS, 0x0000}, // Not found in 4.3.4
            //{Opcode.CMSG_GM_NUKE, 0x0000}, // Not found in 4.3.4
            {Opcode.CMSG_GM_LAG_REPORT, 0x0D47},
            //{Opcode.CMSG_GM_SET_SECURITY_GROUP, 0x0000}, // Not found in 4.3.4
            {Opcode.CMSG_GOSSIP_HELLO, 0x0D7F},
            {Opcode.CMSG_GOSSIP_SELECT_OPTION, 0x0C78},
            {Opcode.CMSG_GRANT_LEVEL, 0x0D2D},
            {Opcode.CMSG_GROUP_ASSISTANT_LEADER, 0x024A},
            //{Opcode.CMSG_GROUP_CANCEL, 0x0000}, // Not found in 4.3.4
            {Opcode.CMSG_GROUP_CHANGE_SUB_GROUP, 0x0100},
            {Opcode.CMSG_GROUP_DISBAND, 0x0009},
            {Opcode.CMSG_GROUP_INVITE, 0x0507},
            {Opcode.CMSG_GROUP_INVITE_RESPONSE, 0x0542},
            {Opcode.CMSG_GROUP_RAID_CONVERT, 0x034F},
            {Opcode.CMSG_GROUP_REQUEST_JOIN_UPDATES, 0x0744},
            {Opcode.CMSG_GROUP_SET_LEADER, 0x01F7},
            {Opcode.CMSG_GROUP_SET_ROLES, 0x0302},
            {Opcode.CMSG_GROUP_SWAP_SUB_GROUP, 0x0369},
            //{Opcode.CMSG_GROUP_UNINVITE, 0x0000}, // Not found in 4.3.4
            {Opcode.CMSG_GROUP_UNINVITE_GUID, 0x0069},
            {Opcode.CMSG_GUILD_ACCEPT, 0x070B},
            {Opcode.CMSG_GUILD_ACHIEVEMENT_MEMBERS, 0x0026},
            {Opcode.CMSG_GUILD_ACHIEVEMENT_PROGRESS_QUERY, 0x0126},
            {Opcode.CMSG_GUILD_ADD_RANK, 0x036E},
            {Opcode.CMSG_GUILD_ASSIGN_MEMBER_RANK, 0x04A2},
            {Opcode.CMSG_GUILD_BANK_ACTIVATE, 0x0982},
            {Opcode.CMSG_GUILD_BANK_BUY_TAB, 0x0801},
            {Opcode.CMSG_GUILD_BANK_DEPOSIT_MONEY, 0x0D46},
            {Opcode.CMSG_GUILD_BANK_LOG_QUERY, 0x03E2},
            {Opcode.CMSG_GUILD_BANK_REMAINING_WITHDRAW_MONEY_QUERY, 0x01C6},
            //{Opcode.CMSG_GUILD_BANK_NOTE, 0x0000}, // Not found in 4.3.4
            {Opcode.CMSG_GUILD_BANK_QUERY_TAB, 0x0C6B},
            {Opcode.CMSG_GUILD_BANK_TEXT_QUERY, 0x0586},
            {Opcode.CMSG_GUILD_BANK_SWAP_ITEMS, 0x08CE},
            {Opcode.CMSG_GUILD_BANK_UPDATE_TAB, 0x0871},
            {Opcode.CMSG_GUILD_BANK_WITHDRAW_MONEY, 0x0900},
            //{Opcode.CMSG_GUILD_CHANGE_NAME_RANK, 0x05A6},
            {Opcode.CMSG_GUILD_CHANGE_NAME_REQUEST, 0x07E3},
            {Opcode.CMSG_GUILD_DECLINE_INVITATION, 0x05A7},
            {Opcode.CMSG_GUILD_DELETE_RANK, 0x0786},
            //{Opcode.CMSG_GUILD_DEMOTE_MEMBER, 0x0000}, //Deprecated ? 0x1020 4.3.4
            {Opcode.CMSG_GUILD_DISBAND, 0x0062},
            {Opcode.CMSG_GUILD_EVENT_LOG_QUERY, 0x06C3},
            //{Opcode.CMSG_GUILD_INFO, 0x0000}, // Not found in 4.3.4
            {Opcode.CMSG_GUILD_INFO_TEXT, 0x07E2},
            {Opcode.CMSG_GUILD_INVITE, 0x0602},
            //{Opcode.CMSG_GUILD_LEADER, 0x0000}, // Not found in 4.3.4
            {Opcode.CMSG_GUILD_LEAVE, 0x0461},
            {Opcode.CMSG_GUILD_MEMBER_SEND_SOR_REQUEST, 0x036F},
            {Opcode.CMSG_GUILD_MOTD, 0x0569},
            {Opcode.CMSG_GUILD_NEWS_UPDATE_STICKY, 0x026B},
            {Opcode.CMSG_GUILD_PERMISSIONS_QUERY, 0x06C6},
            //{Opcode.CMSG_GUILD_PROMOTE_MEMBER, 0x0000}, // DEPRECATED 0x1030 4.3.4
            //{Opcode.CMSG_GUILD_QUERY, 0x0946},
            {Opcode.CMSG_GUILD_QUERY_NEWS, 0x0067},
            //{Opcode.CMSG_GUILD_QUERY_RANKS, 0x026E},
            //{Opcode.CMSG_GUILD_REMOVE, 0x0183},
            {Opcode.CMSG_GUILD_REPLACE_GUILD_MASTER, 0x04E3},
            {Opcode.CMSG_GUILD_REQUEST_CHALLENGE_UPDATE, 0x0322},
            {Opcode.CMSG_GUILD_REQUEST_MAX_DAILY_XP, 0x0310},
            //{Opcode.CMSG_GUILD_REQUEST_PARTY_STATE, 0x0}, // 0x3900 4.3.4
            {Opcode.CMSG_GUILD_ROSTER_SEND_SOR, 0x0222},
            {Opcode.CMSG_GUILD_SET_ACHIEVEMENT_TRACKING, 0x02E7},
            {Opcode.CMSG_GUILD_SET_GUILD_MASTER, 0x012B},
            {Opcode.CMSG_GUILD_SET_NOTE, 0x0226},
            {Opcode.CMSG_GUILD_SET_RANK_PERMISSIONS, 0x05A6},
            {Opcode.CMSG_GUILD_SWITCH_RANK, 0x07C2},
            //{Opcode.CMSG_HEARTH_AND_RESURRECT, 0x0}, // 0x4B34 4.3.4
            //{Opcode.CMSG_IGNORE_TRADE, 0x0}, // Deprecated ? 0x7112 4.3.4
            {Opcode.CMSG_INITIATE_TRADE, 0x06F1},
            {Opcode.CMSG_INSPECT, 0x0254},
            {Opcode.CMSG_INSPECT_HONOR_STATS, 0x0171},
            {Opcode.CMSG_INSTANCE_LOCK_WARNING_RESPONSE, 0x0816},
            {Opcode.CMSG_ITEM_PURCHASE_REFUND, 0x0120},
            //{Opcode.CMSG_ITEM_REFUND_INFO, 0x0355},
            {Opcode.CMSG_ITEM_TEXT_QUERY, 0x09DA},
            {Opcode.CMSG_CHAT_JOIN_CHANNEL, 0x04EC},
            {Opcode.CMSG_KEEP_ALIVE, 0x0910},
            {Opcode.CMSG_LEARN_PET_SPECIALIZATION_GROUP, 0x0338},
            {Opcode.CMSG_LEARN_TALENTS, 0x031C},
            {Opcode.CMSG_LEAVE_BATTLEFIELD, 0x022C},
            {Opcode.CMSG_CHAT_LEAVE_CHANNEL, 0x07DA},
            {Opcode.CMSG_LFG_PLAYER_LOCK_INFO_REQUEST, 0x044A},
            //{Opcode.CMSG_LFG_GET_PLAYER_INFO, 0x0000}, // Unused 434
            {Opcode.CMSG_LFG_LIST_GET_STATUS, 0x004D},
            {Opcode.CMSG_LFG_JOIN, 0x03D2},
            {Opcode.CMSG_LFG_LEAVE, 0x0601},
            {Opcode.CMSG_LFG_PARTY_LOCK_INFO_REQUEST, 0x0000}, // Unused 434
            {Opcode.CMSG_LFG_PROPOSAL_RESULT, 0x0107},
            {Opcode.CMSG_LFG_SET_BOOT_VOTE, 0x064F},
            {Opcode.CMSG_LFG_SET_COMMENT, 0x0000}, // Only used for debug 0x0530 4.3.4
            {Opcode.CMSG_LFG_SET_ROLES, 0x040D},
            {Opcode.CMSG_LFG_TELEPORT, 0x064B},
            {Opcode.CMSG_LF_GUILD_ADD_RECRUIT, 0x0045},
            {Opcode.CMSG_LF_GUILD_BROWSE, 0x0061},
            {Opcode.CMSG_LF_GUILD_DECLINE_RECRUIT, 0x0367},
            {Opcode.CMSG_LF_GUILD_GET_APPLICATIONS, 0x0583},
            {Opcode.CMSG_LF_GUILD_GET_RECRUITS, 0x04A6},
            {Opcode.CMSG_LF_GUILD_POST_REQUEST, 0x03A6},
            {Opcode.CMSG_LF_GUILD_REMOVE_RECRUIT, 0x03A7},
            {Opcode.CMSG_LF_GUILD_SET_GUILD_POST, 0x014F},
            {Opcode.CMSG_LIST_INVENTORY, 0x0853},
            {Opcode.CMSG_LOADING_SCREEN_NOTIFY, 0x0060},
            {Opcode.CMSG_LOGOUT_CANCEL, 0x09E7},
            {Opcode.CMSG_LOGOUT_REQUEST, 0x0CE0},
            {Opcode.CMSG_LOG_DISCONNECT, 0x048F},
            //{Opcode.CMSG_LOOT, 0x0236},
            {Opcode.CMSG_LOOT_CURRENCY, 0x0}, // 0x781C in 4.3.4  @todo : find me i give you more bacon !
            {Opcode.CMSG_LOOT_ROLL, 0x01F9},
            {Opcode.CMSG_LOOT_MASTER_GIVE, 0x0239},
            //{Opcode.CMSG_LOOT_METHOD, 0x07F6},
            {Opcode.CMSG_LOOT_MONEY, 0x02D7},
            {Opcode.CMSG_LOOT_RELEASE, 0x00B2},
            {Opcode.CMSG_LOOT_ROLL, 0x077C},
            {Opcode.CMSG_MAIL_CREATE_TEXT_ITEM, 0x0834},
            {Opcode.CMSG_MAIL_DELETE, 0x0195},
            {Opcode.CMSG_MAIL_MARK_AS_READ, 0x099F},
            {Opcode.CMSG_MAIL_RETURN_TO_SENDER, 0x04B7},
            {Opcode.CMSG_MAIL_TAKE_ITEM, 0x0CD8},
            {Opcode.CMSG_MAIL_TAKE_MONEY, 0x0865},
            //{Opcode.CMSG_MEETINGSTONE_INFO, 0x0000}, // Not found in 4.3.4
            {Opcode.CMSG_CHAT_ADDON_MESSAGE_BATTLEGROUND, 0x0584},
            {Opcode.CMSG_CHAT_ADDON_MESSAGE_GUILD, 0x011E},
            {Opcode.CMSG_CHAT_ADDON_MESSAGE_OFFICER, 0x03ED},
            {Opcode.CMSG_CHAT_ADDON_MESSAGE_PARTY, 0x00DE},
            {Opcode.CMSG_CHAT_ADDON_MESSAGE_RAID, 0x04A9},
            {Opcode.CMSG_CHAT_ADDON_MESSAGE_WHISPER, 0x039F},
            {Opcode.CMSG_CHAT_MESSAGE_AFK, 0x0384},
            {Opcode.CMSG_CHAT_MESSAGE_BATTLEGROUND, 0x04CD},
            {Opcode.CMSG_CHAT_MESSAGE_CHANNEL, 0x079A},
            {Opcode.CMSG_CHAT_MESSAGE_DND, 0x01E4},
            {Opcode.CMSG_CHAT_MESSAGE_EMOTE, 0x0285},
            {Opcode.CMSG_CHAT_MESSAGE_GUILD, 0x00E4},
            {Opcode.CMSG_CHAT_MESSAGE_OFFICER, 0x01C1},
            {Opcode.CMSG_CHAT_MESSAGE_PARTY, 0x05A1},
            {Opcode.CMSG_CHAT_MESSAGE_RAID, 0x05E8},
            {Opcode.CMSG_CHAT_MESSAGE_RAID_WARNING, 0x031F},
            {Opcode.CMSG_CHAT_MESSAGE_SAY, 0x061A},
            {Opcode.CMSG_CHAT_MESSAGE_WHISPER, 0x00A8},
            {Opcode.CMSG_CHAT_MESSAGE_YELL, 0x06E5},
            {Opcode.CMSG_MINIGAME_MOVE, 0x0C93},
            {Opcode.CMSG_MOUNT_SPECIAL_ANIM, 0x0DB1},
            //{Opcode.CMSG_MOVE_CHARM_TELEPORT_CHEAT, 0x0000},
            //{Opcode.CMSG_MOVE_CHANGE_TRANSPORT, 0x0}, // 0x3102 in  4.3.4 @todo : find me and i give you lot of bacon
            {Opcode.CMSG_MOVE_ENABLE_SWIM_TO_FLY_TRANS_ACK, 0x0000},
            //{Opcode.CMSG_MOVE_NOT_ACTIVE_MOVER, 0x0}, // 0x7A1A in 4.3.4
            //{Opcode.CMSG_MOVE_SET_RELATIVE_POSITION, 0x0000}, // Not found in 4.3.4
            //{Opcode.CMSG_MOVE_SET_VEHICLE_REC_ID_ACK, 0x0000},
            {Opcode.CMSG_MOVE_SPLINE_DONE, 0x0651},
            {Opcode.CMSG_MOVE_TIME_SKIPPED, 0x0351},
            //{Opcode.CMSG_MOVE_TOGGLE_COLLISION_ACK, 0x0000}, // Not found in 4.3.4
            //{Opcode.CMSG_NAME_QUERY, 0x0884},
            //{Opcode.CMSG_NEW_SPELL_SLOT, 0x0000}, // Not found in 4.3.4
            {Opcode.CMSG_NEXT_CINEMATIC_CAMERA, 0x0D4F},
            {Opcode.CMSG_QUERY_NPC_TEXT, 0x0D1C},
            {Opcode.CMSG_OBJECT_UPDATE_FAILED, 0x0476},
            {Opcode.CMSG_OBJECT_UPDATE_RESCUED, 0x0551},
            {Opcode.CMSG_OFFER_PETITION, 0x0806},
            {Opcode.CMSG_OPENING_CINEMATIC, 0x0C2E},
            {Opcode.CMSG_OPEN_ITEM, 0x0D6A},
            {Opcode.CMSG_OPT_OUT_OF_LOOT, 0x0D12},
            {Opcode.CMSG_QUERY_PAGE_TEXT, 0x0862},
            //{Opcode.CMSG_PARTY_SILENCE, 0x0000}, //Deprecated, script doesn't exist anymore. Sure ? 0x6B26 in 4.3.4
            //{Opcode.CMSG_PARTY_UNSILENCE, 0x0000}, //Deprecated, script doesn't exist anymore. Sure ? 0x4D24 in 4.3.4
            {Opcode.CMSG_PETITION_BUY, 0x0DA2},
            {Opcode.CMSG_PETITION_QUERY, 0x0C83},
            {Opcode.CMSG_PETITION_SHOW_LIST, 0x09A1},
            {Opcode.CMSG_PETITION_SHOW_SIGNATURES, 0x083E},
            {Opcode.CMSG_PETITION_SIGN, 0x0887},
            {Opcode.CMSG_PET_ABANDON, 0x0CB2},
            {Opcode.CMSG_PET_ACTION, 0x0C0F},
            {Opcode.CMSG_PET_CANCEL_AURA, 0x0C4F},
            {Opcode.CMSG_PET_CAST_SPELL, 0x0CDB},
            {Opcode.CMSG_QUERY_PET_NAME, 0x0881},
            {Opcode.CMSG_PET_RENAME, 0x0846},
            {Opcode.CMSG_PET_SET_ACTION, 0x0D07},
            //{Opcode.CMSG_PET_SPELL_AUTOCAST, 0x0000}, // Deprecated in 5.0.5 16048
            {Opcode.CMSG_PET_STOP_ATTACK, 0x0C59},
            {Opcode.CMSG_PING, 0x04EB},
            {Opcode.CMSG_REQUEST_PLAYED_TIME, 0x09B1},
            //{Opcode.CMSG_PLAYER_DIFFICULTY_CHANGE, 0x0000}, // Not found in 4.3.4
            {Opcode.CMSG_PLAYER_LOGIN, 0x0203},
            {Opcode.CMSG_PLAYER_LOGOUT, 0x0412},
            //{Opcode.CMSG_PLAYER_MOVE, 0x03F8}, CUSTOM OPCODE, client patch
            {Opcode.CMSG_PLAYER_VEHICLE_ENTER, 0x06B0},
            {Opcode.CMSG_PLAY_DANCE, 0x0878},
            {Opcode.CMSG_PUSH_QUEST_TO_PARTY, 0x0840},
            {Opcode.CMSG_PVP_LOG_DATA, 0x0220},
            {Opcode.CMSG_QUERY_BATTLEFIELD_STATE, 0x037D},
            {Opcode.CMSG_QUERY_GAME_OBJECT, 0x0CF8},
            {Opcode.CMSG_GUILD_QUERY_MEMBERS_FOR_RECIPE, 0x01E3},
            {Opcode.CMSG_GUILD_QUERY_MEMBER_RECIPES, 0x00A7},
            {Opcode.CMSG_GUILD_QUERY_RECIPES, 0x05A2},
            {Opcode.CMSG_REQUEST_GUILD_REWARDS_LIST, 0x0624},
            {Opcode.CMSG_REQUEST_GUILD_XP, 0x01C7},
            {Opcode.CMSG_QUERY_INSPECT_ACHIEVEMENTS, 0x0C3A},
            //{Opcode.CMSG_QUERY_QUESTS_COMPLETED, 0x0000}, //Deprecated Sure ? 0x2317 in 4.3.4
            {Opcode.CMSG_QUERY_TIME, 0x0CDA},
            {Opcode.CMSG_QUEST_GIVER_ACCEPT_QUEST, 0x0DA0},
            //{Opcode.CMSG_QUEST_GIVER_CANCEL, 0x0000}, // Not found in 4.3.4
            {Opcode.CMSG_QUEST_GIVER_CHOOSE_REWARD, 0x09FC},
            {Opcode.CMSG_QUEST_GIVER_COMPLETE_QUEST, 0x0CEB},
            {Opcode.CMSG_QUEST_GIVER_HELLO, 0x0D0A},
            {Opcode.CMSG_QUEST_GIVER_QUERY_QUEST, 0x0CA1},
            //{Opcode.CMSG_QUEST_GIVER_QUEST_AUTOLAUNCH, 0x0000}, // Not found in 4.3.4
            {Opcode.CMSG_QUEST_GIVER_REQUEST_REWARD, 0x0D92},
            {Opcode.CMSG_QUEST_GIVER_STATUS_MULTIPLE_QUERY, 0x0C97},
            {Opcode.CMSG_QUEST_GIVER_STATUS_QUERY, 0x0C8D},
            {Opcode.CMSG_QUEST_LOG_REMOVE_QUEST, 0x07F4},
            //{Opcode.CMSG_QUEST_LOG_SWAP_QUEST, 0x0000}, // Not found in 4.3.4
            {Opcode.CMSG_QUEST_CONFIRM_ACCEPT, 0x0C34},
            {Opcode.CMSG_QUEST_NPC_QUERY, 0x06FD},
            {Opcode.CMSG_QUEST_POI_QUERY, 0x08B1},
            {Opcode.CMSG_QUERY_QUEST_INFO, 0x087F},
            //{Opcode.CMSG_RAID_CONFIRM_READY_CHECK, 0x0112},
            //{Opcode.CMSG_RAID_LEADER_READY_CHECK, 0x0709},
            //{Opcode.CMSG_RAID_TARGET_UPDATE, 0x0396},
            {Opcode.CMSG_GENERATE_RANDOM_CHARACTER_NAME, 0x0044},
            {Opcode.CMSG_READY_FOR_ACCOUNT_DATA_TIMES, 0x09A2},
            {Opcode.CMSG_READ_ITEM, 0x0819},
            {Opcode.CMSG_QUERY_REALM_NAME, 0x081B},
            {Opcode.CMSG_REALM_SPLIT, 0x0820},
            {Opcode.CMSG_RECLAIM_CORPSE, 0x0CF4},
            {Opcode.CMSG_REDIRECTION_AUTH_PROOF, 0x068A},
            {Opcode.CMSG_REFORGE_ITEM, 0x051C},
            {Opcode.CMSG_REORDER_CHARACTERS, 0x0541},
            {Opcode.CMSG_REPAIR_ITEM, 0x089D},
            //{Opcode.CMSG_REPLACE_ACCOUNT_DATA, 0x0000}, // Not found in 4.3.4
            {Opcode.CMSG_REPOP_REQUEST, 0x00D4},
            {Opcode.CMSG_REPORT_PVP_PLAYER_AFK, 0x09FB},
            {Opcode.CMSG_REQUEST_ACCOUNT_DATA, 0x09BD},
            {Opcode.CMSG_REQUEST_CATEGORY_COOLDOWNS, 0x01F5},
            //{Opcode.CMSG_REQUEST_CEMETERY_LIST, 0x0}, // 0x720A in 4.3.4 @todo : find me and i give you bacon
            {Opcode.CMSG_REQUEST_HOTFIX, 0x0643},
            //{Opcode.CMSG_REQUEST_INSPECT_RATED_BG_STATS, 0x0}, // 0x3010 in 4.3.4 @todo : find me and i give you bacon
            {Opcode.CMSG_REQUEST_PARTY_MEMBER_STATS, 0x044E},
            {Opcode.CMSG_REQUEST_PET_INFO, 0x0C50},
            {Opcode.CMSG_GET_PVP_OPTIONS_ENABLED, 0x0743},
            {Opcode.CMSG_REQUEST_PVP_REWARDS, 0x0329},
            {Opcode.CMSG_REQUEST_RAID_INFO, 0x0925},
            {Opcode.CMSG_REQUEST_RATED_BG_INFO, 0x07B2},
            {Opcode.CMSG_REQUEST_RATED_BG_STATS, 0x060D},
            {Opcode.CMSG_REQUEST_RESEARCH_HISTORY, 0x0574},
            {Opcode.CMSG_REQUEST_VEHICLE_EXIT, 0x0759},
            {Opcode.CMSG_REQUEST_VEHICLE_NEXT_SEAT, 0x0674},
            {Opcode.CMSG_REQUEST_VEHICLE_PREV_SEAT, 0x055C},
            {Opcode.CMSG_REQUEST_VEHICLE_SWITCH_SEAT, 0x0255},
            {Opcode.CMSG_RESET_FACTION_CHEAT, 0x04AB},
            {Opcode.CMSG_RESET_INSTANCES, 0x0C71},
            {Opcode.CMSG_RESURRECT_RESPONSE, 0x0C53},
            {Opcode.CMSG_CLIENT_PORT_GRAVEYARD, 0x06D2},
            {Opcode.CMSG_ROLE_POLL_BEGIN, 0x0104},
            {Opcode.CMSG_SAVE_CUF_PROFILES, 0x0633},
            //{Opcode.CMSG_SAVE_PLAYER, 0x0000}, // Not found in 4.3.4
            //{Opcode.CMSG_SEARCH_LFG_JOIN, 0x0000}, // Not found in 4.3.4
            //{Opcode.CMSG_SEARCH_LFG_LEAVE, 0x0000}, // Not found in 4.3.4
            {Opcode.CMSG_SELECT_FACTION, 0x07DD},
            {Opcode.CMSG_SELF_RES, 0x0974},
            {Opcode.CMSG_SELL_ITEM, 0x0997},
            {Opcode.CMSG_SEND_MAIL, 0x010C},
            {Opcode.CMSG_SEND_SOR_REQUEST_VIA_ADDRESS, 0x000E},
            {Opcode.CMSG_SEND_SOR_REQUEST_VIA_BNET_ACCOUNT_ID, 0x0008},
            //{Opcode.CMSG_SERVERTIME, 0x0000}, // Not found in 4.3.4
            //{Opcode.CMSG_SETDEATHBINDPOINT, 0x0000}, // Not found in 4.3.4
            {Opcode.CMSG_SET_SHEATHED, 0x0DC0},
            {Opcode.CMSG_SET_ACTION_BAR_TOGGLES, 0x08B0},
            {Opcode.CMSG_SET_ACTION_BUTTON, 0x0403},
            {Opcode.CMSG_SET_ACTIVE_MOVER, 0x04B5},
            //{Opcode.CMSG_SET_ACTIVE_VOICE_CHANNEL, 0x0000}, // Voice system not used
            {Opcode.CMSG_LOW_LEVEL_RAID1, 0x0827},
            {Opcode.CMSG_LOW_LEVEL_RAID2, 0x0916},
            {Opcode.CMSG_SET_CHANNEL_WATCH, 0x0D2A},
            {Opcode.CMSG_SET_CONTACT_NOTES, 0x0921},
            {Opcode.CMSG_SET_CURRENCY_FLAGS, 0x039C},
            {Opcode.CMSG_SET_EVERYONE_IS_ASSISTANT, 0x05D3},
            {Opcode.CMSG_SET_FACTION_AT_WAR, 0x0866},
            {Opcode.CMSG_SET_FACTION_CHEAT, 0x0000},
            {Opcode.CMSG_SET_FACTION_INACTIVE, 0x0CB0},
            {Opcode.CMSG_SET_GUILD_BANK_TEXT, 0x0122},
            //{Opcode.CMSG_LFG_SET_COMMENT, 0x0000}, // Not found in 4.3.4
            {Opcode.CMSG_SET_PET_SLOT, 0x0131},
            {Opcode.CMSG_SET_PLAYER_DECLINED_NAMES, 0x0DA3},
            {Opcode.CMSG_SET_PREFERRED_CEMETERY, 0x061C},
            //{Opcode.CMSG_SET_PRIMARY_TALENT_TREE, 0x0000}, //deprecated
            {Opcode.CMSG_SET_RELATIVE_POSITION, 0x03B5},
            {Opcode.CMSG_SET_SAVED_INSTANCE_EXTEND, 0x081D},
            {Opcode.CMSG_SET_SELECTION, 0x02B1},
            //{Opcode.CMSG_SET_SKILL_CHEAT, 0x0000}, // Not found in 4.3.4
            {Opcode.CMSG_SET_SPECIALIZATION, 0x05D8},
            {Opcode.CMSG_SET_TAXI_BENCHMARK_MODE, 0x0CFA},
            {Opcode.CMSG_SET_TITLE, 0x0995},
            {Opcode.CMSG_SET_TRADE_CURRENCY, 0x0534},
            {Opcode.CMSG_SET_TRADE_GOLD, 0x0410},
            {Opcode.CMSG_SET_TRADE_ITEM, 0x0696},
            //{Opcode.CMSG_SET_VEHICLE_REC_ID_ACK, 0x0}, // 0x3108 in 4.3.4 @todo : find me and BACON !
            {Opcode.CMSG_SET_WATCHED_FACTION, 0x0D66},
            {Opcode.CMSG_SHOWING_CLOAK, 0x09AD},
            {Opcode.CMSG_SHOWING_HELM, 0x0D7C},
            {Opcode.CMSG_SOCKET_GEMS, 0x084D},
            {Opcode.CMSG_SPELL_CLICK, 0x0DCD},
            {Opcode.CMSG_SPIRIT_HEALER_ACTIVATE, 0x09FA},
            {Opcode.CMSG_SPLIT_ITEM, 0x0DAD},
            {Opcode.CMSG_STAND_STATE_CHANGE, 0x0D96},
            //{Opcode.CMSG_START_QUEST, 0x0000}, // Not found in 4.3.4
            {Opcode.CMSG_STOP_DANCE, 0x0CF6},
            //{Opcode.CMSG_STORE_LOOT_IN_SLOT, 0x0000}, // Not found in 4.3.4
            {Opcode.CMSG_SUPPORT_TICKET_SUBMIT_BUG, 0x03D3},
            //{Opcode.CMSG_SUPPORT_TICKET_SUBMIT_COMPLAINT, 0x0000}, //Deprecated ? 0x2512 4.3.4
            {Opcode.CMSG_SUGGESTION_SUBMIT, 0x0001},
            {Opcode.CMSG_BATTLE_PET_SUMMON_COMPANION, 0x021c},
            {Opcode.CMSG_SUMMON_RESPONSE, 0x0CFE},
            //{Opcode.CMSG_SUSPEND_TOKEN_RESPONSE, 0x0000}, //Unused
            {Opcode.CMSG_SWAP_INV_ITEM, 0x0810},
            {Opcode.CMSG_SWAP_ITEM, 0x089C},
            {Opcode.CMSG_SYNC_DANCE, 0x0870},
            //{Opcode.CMSG_TAXICLEARALLNODES, 0x0000}, // Not found in 4.3.4
            //{Opcode.CMSG_TAXIENABLEALLNODES, 0x0000}, // Not found in 4.3.4
            {Opcode.CMSG_TAXI_NODE_STATUS_QUERY, 0x08DC},
            {Opcode.CMSG_TAXI_QUERY_AVAILABLE_NODES, 0x093E},
            //{Opcode.CMSG_TAXISHOWNODES, 0x0000}, // Not found in 4.3.4
            {Opcode.CMSG_TELEPORT_TO_UNIT, 0x0447},
            {Opcode.CMSG_SEND_TEXT_EMOTE, 0x086F},
            {Opcode.CMSG_TIME_ADJUSTMENT_RESPONSE, 0x0419},
            {Opcode.CMSG_TIME_SYNC_RESPONSE, 0x0729},
            {Opcode.CMSG_TIME_SYNC_RESPONSE_FAILED, 0x0751},
            {Opcode.CMSG_TOGGLE_PVP, 0x09D2},
            {Opcode.CMSG_TOTEM_DESTROYED, 0x0DBF},
            {Opcode.CMSG_TRAINER_BUY_SPELL, 0x0981},
            {Opcode.CMSG_TRAINER_LIST, 0x0904},
            {Opcode.CMSG_TRANSMOGRIFY_ITEMS, 0x047D},
            //{Opcode.CMSG_TRIGGER_CINEMATIC_CHEAT, 0x0},
            {Opcode.CMSG_TURN_IN_PETITION, 0x0DA6},
            {Opcode.CMSG_TUTORIAL_CLEAR, 0x0CD4},
            {Opcode.CMSG_TUTORIAL_FLAG, 0x0924},
            {Opcode.CMSG_TUTORIAL_RESET, 0x092A},
            {Opcode.CMSG_UNACCEPT_TRADE, 0x0390},
            {Opcode.CMSG_UNLEARN_SKILL, 0x08F4},
            {Opcode.CMSG_UNLEARN_SPECIALIZATION, 0x00D0},
            {Opcode.CMSG_CHAT_UNREGISTER_ALL_ADDON_PREFIXES, 0x071B},
            {Opcode.CMSG_UPDATE_ACCOUNT_DATA, 0x0984},
            //{Opcode.CMSG_UPDATE_MISSILE_TRAJECTORY, 0x0}, // 0x781E in 4.3.4 @todo : Find me and BACON !
            //{Opcode.CMSG_UPDATE_PROJECTILE_POSITION, 0x0}, // 0x0E24 in 4.3.4 @todo : Find me and BACON !
            {Opcode.CMSG_USED_FOLLOW, 0x0571},
            {Opcode.CMSG_USE_ITEM, 0x09FD},
            {Opcode.CMSG_VIOLENCE_LEVEL, 0x04B9},
            {Opcode.CMSG_VOICE_SESSION_ENABLE, 0x0937},
            {Opcode.CMSG_QUERY_VOID_STORAGE, 0x0378},
            {Opcode.CMSG_VOID_STORAGE_TRANSFER, 0x0699},
            {Opcode.CMSG_UNLOCK_VOID_STORAGE, 0x0079},
            {Opcode.CMSG_SWAP_VOID_ITEM, 0x071C},
            {Opcode.CMSG_WARDEN_DATA, 0x0309},
            {Opcode.CMSG_WARGAME_ACCEPT, 0x0196},
            {Opcode.CMSG_WARGAME_START, 0x010A},
            {Opcode.CMSG_WHO, 0x0D69},
            {Opcode.CMSG_WHO_IS, 0x02456},
            //{Opcode.CMSG_WORLD_STATE_UI_TIMER_UPDATE, 0x0DD0},
            {Opcode.CMSG_WORLD_TELEPORT, 0x040F},
            {Opcode.CMSG_WRAP_ITEM, 0x0959},
            {Opcode.CMSG_ZONEUPDATE, 0x0D3B},
        };

        private static readonly BiDictionary<Opcode, int> ServerOpcodes = new BiDictionary<Opcode, int>
        {
            {Opcode.SMSG_ENUM_CHARACTERS_RESULT, 0x0E28},
            {Opcode.SMSG_CACHE_VERSION, 0x0956},
            {Opcode.SMSG_CHAT, 0x0C9F},
            {Opcode.SMSG_QUERY_CREATURE_RESPONSE, 0x0D6C},
            {Opcode.SMSG_QUERY_GAME_OBJECT_RESPONSE, 0x0D21},
            {Opcode.SMSG_QUERY_GUILD_INFO_RESPONSE, 0x0D6B},
            {Opcode.SMSG_PHASE_SHIFT_CHANGE, 0x0A93},

            {Opcode.SMSG_ACCOUNT_DATA_TIMES, 0x0C4B},
            {Opcode.SMSG_ACCOUNT_INFO_RESPONSE, 0x0F05},
            {Opcode.SMSG_RESTRICTED_ACCOUNT_WARNING, 0x0B66},
            {Opcode.SMSG_ACHIEVEMENT_DELETED, 0x0920},
            {Opcode.SMSG_ACHIEVEMENT_EARNED, 0x0AF4},
            {Opcode.SMSG_UPDATE_ACTION_BUTTONS, 0x0E34},
            {Opcode.SMSG_ACTIVATE_TAXI_REPLY, 0x09DE},
            {Opcode.SMSG_ADDON_INFO, 0x09C6},
            {Opcode.SMSG_ADD_RUNE_POWER, 0x086A},
            {Opcode.SMSG_AI_REACTION, 0x0828},
            {Opcode.SMSG_ALL_ACHIEVEMENT_DATA, 0x0B64},
            {Opcode.SMSG_AREA_SPIRIT_HEALER_TIME, 0x0D1D},
            {Opcode.SMSG_AREA_TRIGGER_MESSAGE, 0x0C31},
            {Opcode.SMSG_AREA_TRIGGER_MOVEMENT_UPDATE, 0x0FB8},
            {Opcode.SMSG_AREA_TRIGGER_RESET, 0x0B9B},
            {Opcode.SMSG_ARENA_ERROR, 0x0CA5},
            {Opcode.SMSG_ARENA_OPPONENT_UPDATE, 0x0DA7},
            {Opcode.SMSG_ARENA_TEAM_CHANGE_FAILED_QUEUED, 0x09C2},
            {Opcode.SMSG_ARENA_TEAM_COMMAND_RESULT, 0x0EE2},
            {Opcode.SMSG_ARENA_TEAM_EVENT, 0x0D77},
            {Opcode.SMSG_ARENA_TEAM_INVITE, 0x0CC9},
            {Opcode.SMSG_ARENA_TEAM_QUERY_RESPONSE, 0x09D6},
            {Opcode.SMSG_ARENA_TEAM_ROSTER, 0x0CA4},
            {Opcode.SMSG_ARENA_TEAM_STATS, 0x0DD6},
            {Opcode.SMSG_ATTACKER_STATE_UPDATE, 0x0856},
            {Opcode.SMSG_ATTACK_START, 0x0992},
            {Opcode.SMSG_ATTACK_STOP, 0x0848},
            {Opcode.SMSG_ATTACKSWING_BADFACING, 0x0898},
            {Opcode.SMSG_ATTACKSWING_CANT_ATTACK, 0x08AC},
            {Opcode.SMSG_ATTACKSWING_DEADTARGET, 0x0C2B},
            {Opcode.SMSG_ATTACKSWING_NOTINRANGE, 0x0852},
            {Opcode.SMSG_AUCTION_LIST_BIDDER_ITEMS_RESULT, 0x0DB3},
            {Opcode.SMSG_AUCTION_BIDDER_NOTIFICATION, 0x09D0},
            {Opcode.SMSG_AUCTION_COMMAND_RESULT, 0x091A},
            {Opcode.SMSG_AUCTION_LIST_PENDING_SALES, 0x0C16},
            {Opcode.SMSG_AUCTION_LIST_RESULT, 0x088B},
            {Opcode.SMSG_AUCTION_LIST_OWNER_ITEMS_RESULT, 0x0DDF},
            {Opcode.SMSG_AUCTION_OWNER_NOTIFICATION, 0x0D6F},
            {Opcode.SMSG_AUCTION_REMOVED_NOTIFICATION, 0x0882},
            //{Opcode.SMSG_AURACASTLOG, 0x0000}, // Not found in 4.3.4
            {Opcode.SMSG_AURA_POINTS_DEPLETED, 0x0BF7},
            {Opcode.SMSG_AURA_UPDATE, 0x08AB},
            {Opcode.SMSG_AURA_UPDATE_ALL, 0x0DDA},
            {Opcode.SMSG_AUTH_CHALLENGE, 0x0523},
            {Opcode.SMSG_AUTH_RESPONSE, 0x0E20},
            {Opcode.SMSG_AVAILABLE_VOICE_CHANNEL, 0x0941},
            {Opcode.SMSG_AVERAGE_ITEM_LEVEL_INFORM, 0x0EF9},
            {Opcode.SMSG_BARBER_SHOP_RESULT, 0x0835},
            {Opcode.SMSG_BATTLEFIELD_LIST, 0x0FE5},
            {Opcode.SMSG_BATTLEFIELD_MGR_EJECTED, 0x0A89},
            {Opcode.SMSG_BATTLEFIELD_MGR_EJECT_PENDING, 0x0B36},
            {Opcode.SMSG_BATTLEFIELD_MGR_ENTERING, 0x0A0A},
            {Opcode.SMSG_BATTLEFIELD_MGR_ENTRY_INVITE, 0x0B44},
            {Opcode.SMSG_BATTLEFIELD_MGR_EXIT_REQUEST, 0x0E33},
            {Opcode.SMSG_BATTLEFIELD_MGR_QUEUE_INVITE, 0x0E6D},
            {Opcode.SMSG_BATTLEFIELD_MGR_QUEUE_REQUEST_RESPONSE, 0x0E15},
            //{Opcode.SMSG_BATTLEFIELD_MGR_STATE_CHANGED, 0x0}, // 0x35B4 in 4.3.4 @todo : Find me and BACON !
            //{Opcode.SMSG_BATTLEFIELD_PORT_DENIED, 0x0}, // 0x35A3 in 4.3.4 @todo : Find me and BACON !
            {Opcode.SMSG_BATTLEFIELD_RATED_INFO, 0x0A84},
            {Opcode.SMSG_BATTLEFIELD_STATUS, 0x0F39},
            {Opcode.SMSG_BATTLEFIELD_STATUS_ACTIVE, 0x0A33},
            {Opcode.SMSG_BATTLEFIELD_STATUS_FAILED, 0x0E88},
            {Opcode.SMSG_BATTLEFIELD_STATUS_NEED_CONFIRMATION, 0x0AE3},
            {Opcode.SMSG_BATTLEFIELD_STATUS_QUEUED, 0x0B88},
            {Opcode.SMSG_BATTLEFIELD_STATUS_WAIT_FOR_GROUPS, 0x0ADA},
            {Opcode.SMSG_BATTLEGROUND_INFO_THROTTLED, 0x0BEC},
            {Opcode.SMSG_BATTLEGROUND_PLAYER_JOINED, 0x0AB5},
            {Opcode.SMSG_BATTLEGROUND_PLAYER_LEFT, 0x0AD3},
            {Opcode.SMSG_BATTLEGROUND_PLAYER_POSITIONS, 0x0FA8},
            {Opcode.SMSG_BATTLE_PET_JOURNAL, 0x0B2E},
            {Opcode.SMSG_BINDER_CONFIRM, 0x08CC},
            {Opcode.SMSG_BIND_POINT_UPDATE, 0x0C0B},
            //{Opcode.SMSG_BINDZONEREPLY, 0x0000}, // Not found in 4.3.4
            {Opcode.SMSG_BREAK_TARGET, 0x0969},
            //{Opcode.SMSG_BUY_BANK_SLOT_RESULT, 0x0}, // Not found in 4.3.4
            {Opcode.SMSG_BUY_FAILED, 0x0D16},
            //{Opcode.SMSG_BUY_ITEM, 0x08E1},
            //{Opcode.SMSG_CALENDAR_ACTION_PENDING, 0x0}, // Not found in 4.3.4
            {Opcode.SMSG_CALENDAR_ARENA_TEAM, 0x08F6},
            {Opcode.SMSG_CALENDAR_CLEAR_PENDING_ACTION, 0x0DD5},
            {Opcode.SMSG_CALENDAR_COMMAND_RESULT, 0x0DA1},
            {Opcode.SMSG_CALENDAR_EVENT_INVITE, 0x092C},
            {Opcode.SMSG_CALENDAR_EVENT_INVITE_ALERT, 0x0850},
            {Opcode.SMSG_CALENDAR_EVENT_INVITE_NOTES, 0x0CAB},
            {Opcode.SMSG_CALENDAR_EVENT_INVITE_NOTES_ALERT, 0x095C},
            {Opcode.SMSG_CALENDAR_EVENT_INVITE_REMOVED, 0x0905},
            {Opcode.SMSG_CALENDAR_EVENT_INVITE_REMOVED_ALERT, 0x090E},
            {Opcode.SMSG_CALENDAR_EVENT_INVITE_STATUS_ALERT, 0x09AE},
            {Opcode.SMSG_CALENDAR_EVENT_MODERATOR_STATUS_ALERT, 0x093D},
            {Opcode.SMSG_CALENDAR_EVENT_REMOVED_ALERT, 0x08BA},
            {Opcode.SMSG_CALENDAR_EVENT_STATUS, 0x099D},
            {Opcode.SMSG_CALENDAR_EVENT_UPDATED_ALERT, 0x0C10},
            {Opcode.SMSG_CALENDAR_FILTER_GUILD, 0x0CAE},
            {Opcode.SMSG_CALENDAR_RAID_LOCKOUT_ADDED, 0x0DC8},
            {Opcode.SMSG_CALENDAR_RAID_LOCKOUT_REMOVED, 0x0839},
            {Opcode.SMSG_CALENDAR_RAID_LOCKOUT_UPDATED, 0x082F},
            {Opcode.SMSG_CALENDAR_SEND_CALENDAR, 0x0D36},
            {Opcode.SMSG_CALENDAR_SEND_EVENT, 0x0D90},
            {Opcode.SMSG_CALENDAR_SEND_NUM_PENDING, 0x0C29},
            //{Opcode.SMSG_CALENDAR_UPDATE_INVITE_LIST, 0x0}, // Not found in 4.3.4
            {Opcode.SMSG_CAMERA_SHAKE, 0x09AF},
            {Opcode.SMSG_CANCEL_AUTO_REPEAT, 0x0DBB},
            {Opcode.SMSG_CANCEL_COMBAT, 0x09D5},
            {Opcode.SMSG_CAST_FAILED, 0x091C},
            {Opcode.SMSG_CHANNEL_LIST, 0x0CC3},
            {Opcode.SMSG_CHANNEL_MEMBER_COUNT, 0x08D4},
            {Opcode.SMSG_CHANNEL_NOTIFY, 0x091D},
            {Opcode.SMSG_CHARACTER_LOGIN_FAILED, 0x0C6D},
            {Opcode.SMSG_CREATE_CHAR, 0x0C15},
            {Opcode.SMSG_CHAR_CUSTOMIZE, 0x0D27},
            {Opcode.SMSG_DELETE_CHAR, 0x0936},
            {Opcode.SMSG_CHAR_FACTION_CHANGE_RESULT, 0x09E0},
            {Opcode.SMSG_CHARACTER_RENAME_RESULT, 0x0945},
            {Opcode.SMSG_CHAT_IGNORED_ACCOUNT_MUTED, 0x0000},
            {Opcode.SMSG_CHAT_NOT_IN_PARTY, 0x0D98},
            {Opcode.SMSG_CHAT_PLAYER_AMBIGUOUS, 0x0989},
            {Opcode.SMSG_CHAT_PLAYER_NOTFOUND, 0x08F2},
            {Opcode.SMSG_CHAT_RESTRICTED, 0x0D3C},
            {Opcode.SMSG_CHAT_SERVER_DISCONNECTED, 0x0C70},
            {Opcode.SMSG_CHAT_SERVER_RECONNECTED, 0x0CC8},
            {Opcode.SMSG_CHAT_WRONG_FACTION, 0x086E},
            //{Opcode.SMSG_CHECK_FOR_BOTS, 0x0}, // Not found in 4.3.4
            {Opcode.SMSG_CLEAR_BOSS_EMOTES, 0x0B87},
            //{Opcode.SMSG_CLEAR_COOLDOWN, 0x0}, // Not found in 4.3.4
            {Opcode.SMSG_CLEAR_COOLDOWNS, 0x0EB2},
            {Opcode.SMSG_CLEAR_FAR_SIGHT_IMMEDIATE, 0x0CDE},
            {Opcode.SMSG_CLEAR_TARGET, 0x0D0B},
            {Opcode.SMSG_CLIENTCACHE_VERSION, 0x0EB4},
            //{Opcode.SMSG_CONTROL_UPDATE, 0x0}, // 0x2837 in 4.3.4 @todo : Find me and BACON !
            {Opcode.SMSG_COIN_REMOVED, 0x0BB1},
            {Opcode.SMSG_COMBAT_EVENT_FAILED, 0x09EF},
            //{Opcode.SMSG_COMBAT_LOG_MULTIPLE, 0x0}, // Not found in 4.3.4
            {Opcode.SMSG_COMMENTATOR_MAP_INFO, 0x0C11},
            {Opcode.SMSG_COMMENTATOR_PARTY_INFO, 0x0B06},
            {Opcode.SMSG_COMMENTATOR_PLAYER_INFO, 0x0960},
            {Opcode.SMSG_COMMENTATOR_SKIRMISH_QUEUE_RESULT1, 0x08AA},
            {Opcode.SMSG_COMMENTATOR_SKIRMISH_QUEUE_RESULT2, 0x0CAD},
            {Opcode.SMSG_COMMENTATOR_STATE_CHANGED, 0x099C},
            {Opcode.SMSG_COMPLAINT_RESULT, 0x0872},
            //{Opcode.SMSG_COMPRESSED_ACHIEVEMENT_DATA, 0x0}, // Not found in 4.3.4
            //{Opcode.SMSG_COMPRESSED_CHAR_ENUM, 0x0}, // Not found in 4.3.4
            //{Opcode.SMSG_COMPRESSED_GUILD_ROSTER, 0x0}, // Not found in 4.3.4
            {Opcode.SMSG_COMPRESSED_MOVES, 0x0855},
            //{Opcode.SMSG_COMPRESSED_UPDATE_OBJECT, 0x0}, // Not found in 4.3.4
            {Opcode.SMSG_COMSAT_CONNECT_FAIL, 0x0832},
            {Opcode.SMSG_COMSAT_DISCONNECT, 0x09BC},
            {Opcode.SMSG_COMSAT_RECONNECT_TRY, 0x0961},
            {Opcode.SMSG_CONTACT_LIST, 0x0DC6},
            {Opcode.SMSG_CONVERT_RUNE, 0x0CE9},
            {Opcode.SMSG_COOLDOWN_CHEAT, 0x08AD},
            {Opcode.SMSG_COOLDOWN_EVENT, 0x0879},
            {Opcode.SMSG_CORPSE_MAP_POSITION_QUERY_RESPONSE, 0x0836},
            //{Opcode.SMSG_CORPSE_NOT_IN_INSTANCE, 0x0D01},
            {Opcode.SMSG_CORPSE_MAP_POSITION_QUERY_RESPONSE, 0x0AA2},
            {Opcode.SMSG_CORPSE_RECLAIM_DELAY, 0x0C9E},
            {Opcode.SMSG_CRITERIA_DELETED, 0x0C5B},
            {Opcode.SMSG_CRITERIA_UPDATE, 0x090D},
            {Opcode.SMSG_CROSSED_INEBRIATION_THRESHOLD, 0x0CAA},
            {Opcode.SMSG_CURRENCY_LOOT_REMOVED, 0x0E01},
            //{Opcode.SMSG_CURRENCY_LOOT_RESTORED, 0x0000}, Deprecated 0x30A0 4.3.4
            {Opcode.SMSG_CUSTOM_LOAD_SCREEN, 0x0A5B},
            {Opcode.SMSG_DAMAGE_CALC_LOG, 0x0D9C},
            //{Opcode.SMSG_DAMAGE_DONE_OBSOLETE, 0x0}, // Not found in 4.3.4
            {Opcode.SMSG_DANCE_QUERY_RESPONSE, 0x0843},
            {Opcode.SMSG_DB_REPLY, 0x0B8B},
            {Opcode.SMSG_DEATH_RELEASE_LOC, 0x085E},
            {Opcode.SMSG_RUNE_REGEN_DEBUG, 0x0E2E},
            {Opcode.SMSG_DEFENSE_MESSAGE, 0x09E9},
            {Opcode.SMSG_DESTROY_OBJECT, 0x0D82},
            {Opcode.SMSG_DESTRUCTIBLE_BUILDING_DAMAGE, 0x0DE5},
            {Opcode.SMSG_DIFFERENT_INSTANCE_FROM_PARTY, 0x0E26},
            {Opcode.SMSG_DISENCHANT_CREDIT, 0x0E2D},
            {Opcode.SMSG_DISMOUNT, 0x09B3},
            {Opcode.SMSG_DISMOUNT_RESULT, 0x0C02},
            {Opcode.SMSG_DISPEL_FAILED, 0x0D8B},
            {Opcode.SMSG_DISPLAY_GAME_ERROR, 0x0A63},
            {Opcode.SMSG_DONT_AUTO_PUSH_SPELLS_TO_ACTION_BAR, 0x0BD1},
            {Opcode.SMSG_DROP_NEW_CONNECTION, 0x0527},
            {Opcode.SMSG_DUEL_COMPLETE, 0x09F6},
            {Opcode.SMSG_DUEL_COUNTDOWN, 0x0993},
            {Opcode.SMSG_DUEL_IN_BOUNDS, 0x08B7},
            {Opcode.SMSG_DUEL_OUT_OF_BOUNDS, 0x0D8A},
            {Opcode.SMSG_DUEL_REQUESTED, 0x0C30},
            {Opcode.SMSG_DUEL_WINNER, 0x0DD1},
            {Opcode.SMSG_DUMP_RIDE_TICKETS_RESPONSE, 0x0BF9},
            {Opcode.SMSG_DURABILITY_DAMAGE_DEATH, 0x0D0C},
            //{Opcode.SMSG_ECHO_PARTY_SQUELCH, 0x0}, // 0x0814 in 4.3.4 @todo : Find me and BACON !
            {Opcode.SMSG_EMOTE, 0x0C3E},
            {Opcode.SMSG_ENABLE_BARBER_SHOP, 0x0C19},
            {Opcode.SMSG_ENCHANTMENT_LOG, 0x0C49},
            {Opcode.SMSG_ENVIRONMENTAL_DAMAGE_LOG, 0x0951},
            {Opcode.SMSG_EQUIPMENT_SET_ID, 0x0980},
            {Opcode.SMSG_EQUIPMENT_SET_SAVED, 0x0990},
            {Opcode.SMSG_USE_EQUIPMENT_SET_RESULT, 0x0C52},
            {Opcode.SMSG_EXPECTED_SPAM_RECORDS, 0x0C4D},
            {Opcode.SMSG_EXPLORATION_EXPERIENCE, 0x0C38},
            {Opcode.SMSG_FAILED_PLAYER_CONDITION, 0x0A46},
            {Opcode.SMSG_FEATURE_SYSTEM_STATUS, 0x0B5B},
            {Opcode.SMSG_FEIGN_DEATH_RESISTED, 0x0D7D},
            {Opcode.SMSG_FISH_ESCAPED, 0x0875},
            {Opcode.SMSG_FISH_NOT_HOOKED, 0x08E2},
            {Opcode.SMSG_FLIGHT_SPLINE_SYNC, 0x0864},
            {Opcode.SMSG_FLOOD_DETECTED, 0x0566},
            //{Opcode.SMSG_FORCEACTIONSHOW, 0x0}, // Not found in 4.3.4
            {Opcode.SMSG_FORCED_DEATH_UPDATE, 0x0C13},
            //{Opcode.SMSG_FORCE_DISPLAY_UPDATE, 0x0}, // Not found in 4.3.4
            //{Opcode.SMSG_FORCE_SEND_QUEUED_PACKETS, 0x0626},
            {Opcode.SMSG_FORCE_SET_VEHICLE_REC_ID, 0x0AA7},
            {Opcode.SMSG_FORGE_MASTER_SET, 0x0F8F},
            {Opcode.SMSG_FRIEND_STATUS, 0x0DD4},
            {Opcode.SMSG_GAME_OBJECT_CUSTOM_ANIM, 0x0CDC},
            {Opcode.SMSG_GAMEOBJECT_DESPAWN_ANIM, 0x0D55},
            //{Opcode.SMSG_GAME_OBJECT_PAGETEXT, 0x087D},
            {Opcode.SMSG_GAME_OBJECT_RESET_STATE, 0x08C6},
            {Opcode.SMSG_GAME_SPEED_SET, 0x0D8F},
            {Opcode.SMSG_GAME_TIME_SET, 0x082E},
            {Opcode.SMSG_GAME_TIME_UPDATE, 0x0CE3},
            {Opcode.SMSG_GAME_EVENT_DEBUG_LOG, 0x0BDC},
            {Opcode.SMSG_GAME_OBJECT_ACTIVATE_ANIM_KIT, 0x0AB7},
            {Opcode.SMSG_GMRESPONSE_DB_ERROR, 0x0983},
            {Opcode.SMSG_GMRESPONSE_RECEIVED, 0x0C4E},
            {Opcode.SMSG_GMRESPONSE_STATUS_UPDATE, 0x0D2F},
            {Opcode.SMSG_GM_TICKET_CREATE, 0x0C32},
            {Opcode.SMSG_GM_TICKET_DELETE_TICKET, 0x08D0},
            {Opcode.SMSG_GM_TICKET_GET_TICKET, 0x0BBD},
            {Opcode.SMSG_GM_TICKET_SYSTEM_STATUS, 0x0D1F},
            {Opcode.SMSG_GM_TICKET_UPDATE_TEXT, 0x0CFB},
            {Opcode.SMSG_GM_MESSAGECHAT, 0x090F},
            {Opcode.SMSG_GM_PLAYER_INFO, 0x0D99},
            {Opcode.SMSG_GM_TICKET_STATUS_UPDATE, 0x0821},
            {Opcode.SMSG_GOD_MODE, 0x09F3},
            {Opcode.SMSG_GOSSIP_COMPLETE, 0x0CB6},
            {Opcode.SMSG_GOSSIP_MESSAGE, 0x0DE4},
            {Opcode.SMSG_GOSSIP_POI, 0x0D70},
            {Opcode.SMSG_GROUP_ACTION_THROTTLED, 0x0994},
            {Opcode.SMSG_GROUP_CANCEL, 0x084B},
            {Opcode.SMSG_GROUP_DECLINE, 0x08EA},
            {Opcode.SMSG_GROUP_DESTROYED, 0x0D3A},
            {Opcode.SMSG_GROUP_INVITE, 0x0F68},
            //{Opcode.SMSG_GROUP_JOINED_BATTLEGROUND, 0x0}, // Not found in TC
            //{Opcode.SMSG_GROUP_SET_LEADER, 0x0}, // 0xA1A Not sure ! 0x0526 in 4.3.4 @todo : Find me and BACON !
            {Opcode.SMSG_GROUP_SET_ROLE, 0x0A7B},
            {Opcode.SMSG_GROUP_UNINVITE, 0x08A8},
            {Opcode.SMSG_GUILD_ACHIEVEMENT_DATA, 0x0F23},
            {Opcode.SMSG_GUILD_ACHIEVEMENT_DELETED, 0x0B46},
            {Opcode.SMSG_GUILD_ACHIEVEMENT_EARNED, 0x0A8E},
            {Opcode.SMSG_GUILD_ACHIEVEMENT_MEMBERS, 0x0A62},
            //{Opcode.SMSG_GUILD_BANK_LIST, 0x0F2C},
            {Opcode.SMSG_GUILD_BANK_LOG_QUERY_RESULTS, 0x0F7F},
            {Opcode.SMSG_GUILD_BANK_MONEY_WITHDRAWN, 0x0E78},
            {Opcode.SMSG_GUILD_BANK_TEXT_QUERY_RESULT, 0x0F1C},
            //{Opcode.SMSG_GUILD_CANCEL, 0x0}, // Not found in 4.3.4
            {Opcode.SMSG_GUILD_CHALLENGE_COMPLETED, 0x0A96},
            {Opcode.SMSG_GUILD_CHALLENGE_UPDATE, 0x0EDC},
            {Opcode.SMSG_GUILD_CHANGE_NAME_RESULT, 0x0F07},
            {Opcode.SMSG_GUILD_COMMAND_RESULT, 0x0A59},
            {Opcode.SMSG_GUILD_COMMAND_RESULT_2, 0x0A59},
            {Opcode.SMSG_GUILD_CRITERIA_DATA, 0x0A81},
            {Opcode.SMSG_GUILD_CRITERIA_DELETED, 0x0F6B},
            {Opcode.SMSG_GUILD_DECLINE, 0x094F},
            {Opcode.SMSG_GUILD_EVENT, 0x08E4},
            {Opcode.SMSG_GUILD_EVENT_LOG_QUERY_RESULTS, 0x0EB6},
            {Opcode.SMSG_GUILD_FLAGGED_FOR_RENAME, 0x0ACD},
            {Opcode.SMSG_GUILD_INVITE, 0x0F69},
            //{Opcode.SMSG_GUILD_INVITE_CANCEL, 0x0}, // 0x0606 in 4.3.4 @todo : Find me and BACON !
            {Opcode.SMSG_GUILD_KNOWN_RECIPES, 0x0B7E},
            {Opcode.SMSG_GUILD_MAX_DAILY_XP, 0x0AAF},
            {Opcode.SMSG_GUILD_MEMBERS_FOR_RECIPE, 0x0A04},
            {Opcode.SMSG_GUILD_MEMBER_DAILY_RESET, 0x0A0C},
            {Opcode.SMSG_GUILD_MEMBER_RECIPES, 0x0BFF},
            {Opcode.SMSG_GUILD_MEMBER_UPDATE_NOTE, 0x0F6C},
            {Opcode.SMSG_GUILD_MOVE_COMPLETE, 0x0B40},
            {Opcode.SMSG_GUILD_MOVE_STARTING, 0x0A76},
            {Opcode.SMSG_GUILD_NEWS_DELETED, 0x0A03},
            {Opcode.SMSG_GUILD_NEWS_UPDATE, 0x0BE7},
            //{Opcode.SMSG_GUILD_PARTY_STATE_RESPONSE, 0x0B75},
            {Opcode.SMSG_GUILD_PERMISSIONS_QUERY_RESULTS, 0x0FE4},
            {Opcode.SMSG_GUILD_RANKS, 0x0F5D},
            //{Opcode.SMSG_GUILD_RANKS_UPDATE, 0x0E04},
            {Opcode.SMSG_GUILD_KNOWN_RECIPES, 0x0B7E},
            {Opcode.SMSG_GUILD_RENAMED, 0x0ED1},
            {Opcode.SMSG_GUILD_REPUTATION_REACTION_CHANGED, 0x0BDD},
            {Opcode.SMSG_GUILD_REPUTATION_WEEKLY_CAP, 0x0F29},
            {Opcode.SMSG_GUILD_RESET, 0x0E53},
            {Opcode.SMSG_GUILD_REWARD_LIST, 0x0F00},
            {Opcode.SMSG_GUILD_ROSTER, 0x0BEA},
            //{Opcode.SMSG_GUILD_SET_NOTE, 0x0}, // Not found in 4.3.4
            //{Opcode.SMSG_GUILD_TRADESKILL_UPDATE, 0x0}, // Not found in 4.3.4
            {Opcode.SMSG_GUILD_ROSTER_UPDATE, 0x0BE4},
            {Opcode.SMSG_GUILD_XP, 0x0E7D},
            {Opcode.SMSG_GUILD_XP_GAIN, 0x0EF8},
            //{Opcode.SMSG_GUILD_XP_UPDATE, 0x0}, // Not found in 4.3.4
            {Opcode.SMSG_HEALTH_UPDATE, 0x0841},
            {Opcode.SMSG_HIGHEST_THREAT_UPDATE, 0x0D1A},
            {Opcode.SMSG_HOTFIX_MESSAGE, 0x0F86},
            {Opcode.SMSG_HOTFIX_NOTIFY, 0x0EE0},
            {Opcode.SMSG_INITIALIZE_FACTIONS, 0x0824},
            //{Opcode.SMSG_INITIAL_SPELLS, 0x0000}, Deprecated
            {Opcode.SMSG_SETUP_CURRENCY, 0x0AE5},
            {Opcode.SMSG_INIT_WORLD_STATES, 0x0919},
            //{Opcode.SMSG_INSPECT, 0x0}, // Not found in 4.3.4
            {Opcode.SMSG_INSPECT_HONOR_STATS, 0x0FD4},
            {Opcode.SMSG_INSPECT_RATED_BG_STATS, 0x0B42},
            //{Opcode.SMSG_INSPECT_RESULTS_UPDATE, 0x0}, // 0x0C14 in 4.3.4 @todo : Find me and BACON !
            {Opcode.SMSG_INSPECT_TALENT, 0x0E3D},
            //{Opcode.SMSG_INSTANCE_DIFFICULTY, 0x0}, // Not found in 4.3.4
            {Opcode.SMSG_INSTANCE_LOCK_WARNING_QUERY, 0x0DAA},
            {Opcode.SMSG_INSTANCE_RESET, 0x0D58},
            {Opcode.SMSG_INSTANCE_RESET_FAILED, 0x098C},
            {Opcode.SMSG_INSTANCE_SAVE_CREATED, 0x0CFC},
            {Opcode.SMSG_INVALIDATE_DANCE, 0x0D7E},
            {Opcode.SMSG_INVALIDATE_PLAYER, 0x08CA},
            {Opcode.SMSG_INVALID_PROMOTION_CODE, 0x0C2F},
            {Opcode.SMSG_INVENTORY_CHANGE_FAILURE, 0x098F},
            {Opcode.SMSG_ITEM_ADD_PASSIVE, 0x0F6A},
            {Opcode.SMSG_ITEM_COOLDOWN, 0x096D},
            {Opcode.SMSG_ITEM_ENCHANT_TIME_UPDATE, 0x099E},
            {Opcode.SMSG_ITEM_EXPIRE_PURCHASE_REFUND, 0x0FC6},
            {Opcode.SMSG_ITEM_PUSH_RESULT, 0x0F64},
            {Opcode.SMSG_ITEM_REFUND_INFO_RESPONSE, 0x0B43},
            //{Opcode.SMSG_ITEM_REFUND_RESULT, 0x0B43},
            {Opcode.SMSG_ITEM_REMOVE_PASSIVE, 0x0A19},
            {Opcode.SMSG_ITEM_SEND_PASSIVE, 0x0F80},
            {Opcode.SMSG_QUERY_ITEM_TEXT_RESPONSE, 0x0CB9},
            {Opcode.SMSG_ITEM_TIME_UPDATE, 0x081A},
            //{Opcode.SMSG_JOINED_BATTLEGROUND_QUEUE, 0x0}, // Not found in 4.3.4
            {Opcode.SMSG_KICK_REASON, 0x0923},
            {Opcode.SMSG_LEARNED_DANCE_MOVES, 0x08C4},
            {Opcode.SMSG_LEARNED_SPELL, 0x0BF8},
            {Opcode.SMSG_LEVEL_UP_INFO, 0x085A},
            {Opcode.SMSG_LFG_BOOT_PROPOSAL_UPDATE, 0x091F},
            {Opcode.SMSG_LFG_DISABLED, 0x090C},
            {Opcode.SMSG_LFG_JOIN_RESULT, 0x0EA1},
            {Opcode.SMSG_LFG_OFFER_CONTINUE, 0x090B},
            //{Opcode.SMSG_LFG_OPEN_FROM_GOSSIP, 0x0}, // Not found in 4.3.4
            //{Opcode.SMSG_LFG_PARTY_INFO, 0x0}, //deprecated ? 0x2325 4.3.4
            {Opcode.SMSG_LFG_PLAYER_INFO, 0x08FF},
            {Opcode.SMSG_LFG_PLAYER_REWARD, 0x08C2},
            {Opcode.SMSG_LFG_PROPOSAL_UPDATE, 0x0AEE},
            {Opcode.SMSG_LFG_QUEUE_STATUS, 0x0E36},
            {Opcode.SMSG_LFG_ROLE_CHECK_UPDATE, 0x0F4E},
            {Opcode.SMSG_LFG_ROLE_CHOSEN, 0x08DE},
            {Opcode.SMSG_LFG_SLOT_INVALID, 0x0A40},
            {Opcode.SMSG_LFG_TELEPORT_DENIED, 0x0E24},
            //{Opcode.SMSG_LFG_UPDATE_LIST, 0x0}, // Not found in 4.3.4
            //{Opcode.SMSG_LFG_UPDATE_PARTY, 0x0}, // Not found in 4.3.4
            //{Opcode.SMSG_LFG_UPDATE_PLAYER, 0x0}, // Not found in 4.3.4
            //{Opcode.SMSG_LFG_UPDATE_SEARCH, 0x0}, // 0x54A1 4.3.4
            {Opcode.SMSG_LFG_UPDATE_STATUS, 0x0EEB},
            {Opcode.SMSG_LFG_UPDATE_STATUS_NONE, 0x0FA0},
            {Opcode.SMSG_LF_GUILD_APPLICATIONS_LIST_UPDATED, 0x0E67},
            {Opcode.SMSG_LF_GUILD_APPLICATIONS_LIST_CHANGED, 0x0A1F},
            {Opcode.SMSG_LF_GUILD_BROWSE_UPDATED, 0x0E9F},
            {Opcode.SMSG_LF_GUILD_COMMAND_RESULT, 0x0EC3},
            {Opcode.SMSG_LF_GUILD_MEMBERSHIP_LIST_UPDATED, 0x0AF7},
            {Opcode.SMSG_LF_GUILD_POST_UPDATED, 0x0E5A},
            {Opcode.SMSG_LF_GUILD_RECRUIT_LIST_UPDATED, 0x0B1D},
            //{Opcode.SMSG_LF_GUILD_SEARCH_RESULT, 0x0}, // Not found in TC
            //{Opcode.SMSG_LIST_INVENTORY, 0x0FDE},
            {Opcode.SMSG_LOAD_CUF_PROFILES, 0x0FC9},
            {Opcode.SMSG_LOGIN_SET_TIME_SPEED, 0x0C33},
            {Opcode.SMSG_LOGIN_VERIFY_WORLD, 0x0D33},
            {Opcode.SMSG_LOGOUT_CANCEL_ACK, 0x0803},
            {Opcode.SMSG_LOGOUT_COMPLETE, 0x08DA},
            {Opcode.SMSG_LOGOUT_RESPONSE, 0x0D86},
            {Opcode.SMSG_LOG_XP_GAIN, 0x098A},
            {Opcode.SMSG_LOOT_ALL_PASSED, 0x0E49},
            {Opcode.SMSG_LOOT_CLEAR_MONEY, 0x0B33},
            {Opcode.SMSG_LOOT_CONTENTS, 0x0BFC},
            {Opcode.SMSG_LOOT_LIST, 0x0C37},
            {Opcode.SMSG_LOOT_MASTER_LIST, 0x0A5A},
            {Opcode.SMSG_LOOT_MONEY_NOTIFY, 0x0F18},
            //{Opcode.SMSG_LOOT_RELEASE_RESPONSE, 0x0B8A},
            {Opcode.SMSG_LOOT_REMOVED, 0x0E6A},
            {Opcode.SMSG_LOOT_RESPONSE, 0x0A75},
            {Opcode.SMSG_LOOT_ROLL, 0x0B59},
            {Opcode.SMSG_LOOT_ROLL_WON, 0x0F32},
            {Opcode.SMSG_LOOT_START_ROLL, 0x0EF4},
            {Opcode.SMSG_MAIL_LIST_RESULT, 0x095E},
            {Opcode.SMSG_MAP_OBJ_EVENTS, 0x0BF6},
            {Opcode.SMSG_MEETINGSTONE_COMPLETE, 0x08E0},
            {Opcode.SMSG_MEETINGSTONE_IN_PROGRESS, 0x0D5A},
            //{Opcode.SMSG_MEETINGSTONE_MEMBER_ADDED, 0x0}, // Not found in 4.3.4
            //{Opcode.SMSG_MEETINGSTONE_SETQUEUE, 0x0}, // Not found in 4.3.4
            {Opcode.SMSG_MESSAGE_BOX, 0x0B2F},
            {Opcode.SMSG_MINIGAME_SETUP, 0x09D3},
            {Opcode.SMSG_MINIGAME_STATE, 0x0C57},
            //{Opcode.SMSG_MIRROR_IMAGE_DATA, 0x0DC1},
            {Opcode.SMSG_MISSILE_CANCEL, 0x0FD1},
            {Opcode.SMSG_MODIFY_COOLDOWN, 0x09C7},
            {Opcode.SMSG_MONEY_NOTIFY, 0x0B33},
            //{Opcode.SMSG_MONSTER_MOVE, 0x0942},
            {Opcode.SMSG_MONSTER_MOVE_TRANSPORT, 0x0C35},
            {Opcode.SMSG_MOTD, 0x0952},
            {Opcode.SMSG_MOUNT_RESULT, 0x09D9},
            {Opcode.SMSG_MOUNT_SPECIAL_ANIM, 0x0976},
            {Opcode.SMSG_MOVE_COLLISION_DISABLE, 0x0A16},
            {Opcode.SMSG_MOVE_COLLISION_ENABLE, 0x0F22},
            {Opcode.SMSG_MOVE_FEATHER_FALL, 0x0AFC},
            {Opcode.SMSG_MOVE_GRAVITY_DISABLE, 0x0E21},
            {Opcode.SMSG_MOVE_GRAVITY_ENABLE, 0x0BF2},
            {Opcode.SMSG_MOVE_KNOCK_BACK, 0x0A79},
            {Opcode.SMSG_MOVE_LAND_WALK, 0x0B1C},
            {Opcode.SMSG_MOVE_NORMAL_FALL, 0x0F42},
            {Opcode.SMSG_MOVE_ROOT, 0x0F61},
            {Opcode.SMSG_MOVE_SET_ACTIVE_MOVER, 0x0A67},
            {Opcode.SMSG_MOVE_SET_CAN_FLY, 0x0B90},
            {Opcode.SMSG_MOVE_SET_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY, 0x0BA7},
            {Opcode.SMSG_MOVE_SET_COLLISION_HEIGHT, 0x0E40},
            {Opcode.SMSG_MOVE_SET_COMPOUND_STATE, 0x0A98},
            {Opcode.SMSG_MOVE_SET_FLIGHT_BACK_SPEED, 0x0FDD},
            {Opcode.SMSG_MOVE_SET_FLIGHT_SPEED, 0x0A66},
            {Opcode.SMSG_MOVE_SET_HOVERING, 0x0E0E},
            {Opcode.SMSG_MOVE_SET_PITCH_RATE, 0x0F65},
            {Opcode.SMSG_MOVE_SET_RUN_BACK_SPEED, 0x0A24},
            {Opcode.SMSG_MOVE_SET_RUN_SPEED, 0x0E09},
            {Opcode.SMSG_MOVE_SET_SWIM_BACK_SPEED, 0x0E64},
            {Opcode.SMSG_MOVE_SET_SWIM_SPEED, 0x0E46},
            {Opcode.SMSG_MOVE_SET_TURN_RATE, 0x0E44},
            {Opcode.SMSG_MOVE_SET_VEHICLE_REC_ID, 0x0AA7},
            {Opcode.SMSG_MOVE_SET_WALK_SPEED, 0x0A23},
            {Opcode.SMSG_MOVE_UNROOT, 0x0B11},
            {Opcode.SMSG_MOVE_UNSET_CAN_FLY, 0x0BC9},
            {Opcode.SMSG_MOVE_UNSET_CAN_TRANSITION_BETWEEN_SWIM_AND_FLY, 0x0A28},
            {Opcode.SMSG_MOVE_UNSET_HOVERING, 0x0F75},
            {Opcode.SMSG_MOVE_UPDATE, 0x0A6F},
            {Opcode.SMSG_MOVE_UPDATE_COLLISION_HEIGHT, 0x0E3E},
            {Opcode.SMSG_MOVE_UPDATE_FLIGHT_BACK_SPEED, 0x0B2A},
            {Opcode.SMSG_MOVE_UPDATE_KNOCK_BACK, 0x0AF1},
            {Opcode.SMSG_MOVE_UPDATE_PITCH_RATE, 0x0E6C},
            {Opcode.SMSG_MOVE_UPDATE_RUN_BACK_SPEED, 0x0F4F},
            {Opcode.SMSG_MOVE_UPDATE_SWIM_BACK_SPEED, 0x0B24},
            {Opcode.SMSG_MOVE_UPDATE_SWIM_SPEED, 0x0AAE},
            {Opcode.SMSG_MOVE_UPDATE_TELEPORT, 0x0A80},
            {Opcode.SMSG_MOVE_UPDATE_TURN_RATE, 0x0F96},
            {Opcode.SMSG_MOVE_UPDATE_WALK_SPEED, 0x0B28},
            {Opcode.SMSG_MOVE_WATER_WALK, 0x0E66},
            {Opcode.SMSG_MULTIPLE_PACKETS, 0x0826},
            //{Opcode.SMSG_NAME_QUERY_RESPONSE, 0x0CF9},
            {Opcode.SMSG_NEW_TAXI_PATH, 0x0813},
            {Opcode.SMSG_NEW_WORLD, 0x0F21},
            {Opcode.SMSG_NEW_WORLD_ABORT, 0x0EA0},
            {Opcode.SMSG_NOTIFICATION, 0x0E0F},
            {Opcode.SMSG_NOTIFY_DANCE, 0x0917},
            {Opcode.SMSG_NOTIFY_DEST_LOC_SPELL_CAST, 0x08FA},
            //{Opcode.SMSG_NPC_TEXT_UPDATE, 0x080C},
            //{Opcode.SMSG_NPC_WONT_TALK, 0x0}, // Not found in 4.3.4
            {Opcode.SMSG_OFFER_PETITION_ERROR, 0x0CE7},
            {Opcode.SMSG_ON_CANCEL_EXPECTED_RIDE_VEHICLE_AURA, 0x0CB3},
            {Opcode.SMSG_OPEN_CONTAINER, 0x0844},
            {Opcode.SMSG_OPEN_LFG_DUNGEON_FINDER, 0x0894},
            {Opcode.SMSG_OVERRIDE_LIGHT, 0x08B3},
            {Opcode.SMSG_QUERY_PAGE_TEXT_RESPONSE, 0x0CE2},
            {Opcode.SMSG_PARTY_KILL_LOG, 0x084A},
            {Opcode.SMSG_PARTY_COMMAND_RESULT, 0x0C2D},
            {Opcode.SMSG_PARTY_MEMBER_STATS, 0x0CBA},
            {Opcode.SMSG_PARTY_MEMBER_STATS_FULL, 0x0912},
            {Opcode.SMSG_PARTY_UPDATE, 0x0B3E},
            {Opcode.SMSG_PAUSE_MIRROR_TIMER, 0x08E9},
            {Opcode.SMSG_SPELL_PERIODIC_AURA_LOG, 0x0CCF},
            {Opcode.SMSG_PETGODMODE, 0x09E4},
            {Opcode.SMSG_PETITION_ALREADY_SIGNED, 0x0AA8},
            {Opcode.SMSG_PETITION_QUERY_RESPONSE, 0x0C62},
            {Opcode.SMSG_PETITION_SHOW_LIST, 0x0891},
            {Opcode.SMSG_PETITION_SHOW_SIGNATURES, 0x0CBC},
            {Opcode.SMSG_PETITION_SIGN_RESULTS, 0x08E7},
            {Opcode.SMSG_PET_ACTION_FEEDBACK, 0x095D},
            {Opcode.SMSG_PET_ACTION_SOUND, 0x0C2A},
            {Opcode.SMSG_PET_ADDED, 0x0A7F},
            {Opcode.SMSG_PET_BROKEN, 0x0C8B},
            {Opcode.SMSG_PET_CAST_FAILED, 0x09C9},
            {Opcode.SMSG_PET_DISMISS_SOUND, 0x0D84},
            //{Opcode.SMSG_PET_GUIDS, 0x0}, // 0x2D26 in 4.3.4 @todo : Find me and BACON !
            {Opcode.SMSG_PET_LEARNED_SPELLS, 0x0E63},
            {Opcode.SMSG_PET_MODE, 0x0D2C},
            {Opcode.SMSG_PET_NAME_INVALID, 0x085B},
            //{Opcode.SMSG_PET_NAME_QUERY_RESPONSE, 0x088E},
            {Opcode.SMSG_PET_REMOVED_SPELL, 0x0EBE},
            {Opcode.SMSG_PET_RENAMEABLE, 0x09EB},
            {Opcode.SMSG_PET_SLOT_UPDATED, 0x0A1B},
            {Opcode.SMSG_PET_SPELLS_MESSAGE, 0x0D79},
            {Opcode.SMSG_PET_TAME_FAILURE, 0x08CD},
            {Opcode.SMSG_PET_UPDATE_COMBO_POINTS, 0x09CD},
            {Opcode.SMSG_PLAYED_TIME, 0x0D59},
            {Opcode.SMSG_PLAYERBINDERROR, 0x0C89},
            {Opcode.SMSG_PLAYER_BOUND, 0x0C95},
            {Opcode.SMSG_PLAYER_DIFFICULTY_CHANGE, 0x0CB4},
            {Opcode.SMSG_PLAYER_SKINNED, 0x08B2},
            //{Opcode.SMSG_PLAYER_UNK_DEAD_ALIVE, 0x0}, // Not found in 4.3.4
            {Opcode.SMSG_PLAYER_VEHICLE_DATA, 0x09C1},
            {Opcode.SMSG_PLAY_DANCE, 0x086C},
            {Opcode.SMSG_PLAY_MUSIC, 0x08EF},
            {Opcode.SMSG_PLAY_OBJECT_SOUND, 0x0CED},
            //{Opcode.SMSG_PLAY_ONE_SHOT_ANIM_KIT, 0x0}, // 0x4A35 in 4.3.4 @todo : Find me and BACON !
            {Opcode.SMSG_PLAY_SOUND, 0x0873},
            //{Opcode.SMSG_PLAY_SPELL_IMPACT, 0x0000}, //SMSG_PLAY_SPELL_IMPACT                            = 0x000,  removed in commit c041875
            {Opcode.SMSG_PLAY_SPELL_VISUAL, 0x0AE4},
            {Opcode.SMSG_PLAY_SPELL_VISUAL_KIT, 0x0BFD},
            {Opcode.SMSG_PLAY_TIME_WARNING, 0x0817},
            {Opcode.SMSG_PONG, 0x0462},
            {Opcode.SMSG_POWER_UPDATE, 0x094A},
            {Opcode.SMSG_PRE_RESSURECT, 0x088A},
            //{Opcode.SMSG_PROC_RESIST, 0x0},
            {Opcode.SMSG_PROPOSE_LEVEL_GRANT, 0x0D8D},
            //{Opcode.SMSG_PUREMOUNT_CANCELLED_OBSOLETE, 0x0}, // Not found in 4.3.4
            {Opcode.SMSG_PVP_CREDIT, 0x0D43},
            {Opcode.SMSG_PVP_LOG_DATA, 0x0B3F},
            {Opcode.SMSG_PVP_OPTIONS_ENABLED, 0x0A09},
            //{Opcode.SMSG_QUERY_QUESTS_COMPLETED_RESPONSE, 0x0000}, Deprecated
            {Opcode.SMSG_QUERY_TIME_RESPONSE, 0x0935},
            {Opcode.SMSG_QUEST_GIVER_OFFER_REWARD_MESSAGE, 0x085C},
            {Opcode.SMSG_QUEST_GIVER_QUEST_COMPLETE, 0x0B98},
            {Opcode.SMSG_QUEST_GIVER_QUEST_DETAILS, 0x0D4E},
            {Opcode.SMSG_QUEST_GIVER_QUEST_FAILED, 0x0D02},
            {Opcode.SMSG_QUEST_GIVER_INVALID_QUEST, 0x08C0},
            {Opcode.SMSG_QUEST_GIVER_QUEST_LIST_MESSAGE, 0x0877},
            {Opcode.SMSG_QUEST_GIVER_REQUEST_ITEMS, 0x08EE},
            {Opcode.SMSG_QUEST_GIVER_STATUS, 0x0DB8},
            {Opcode.SMSG_QUEST_GIVER_STATUS_MULTIPLE, 0x0D6D},
            {Opcode.SMSG_QUEST_LOG_FULL, 0x0C54},
            //{Opcode.SMSG_QUEST_UPDATE_ADD_ITEM, 0x0}, // Not found in 4.3.4
            {Opcode.SMSG_QUEST_UPDATE_ADD_KILL, 0x0C63},
            {Opcode.SMSG_QUEST_UPDATE_ADD_PVP_CREDIT, 0x0D3F},
            {Opcode.SMSG_QUEST_UPDATE_COMPLETE, 0x09B0},
            {Opcode.SMSG_QUEST_UPDATE_FAILED, 0x086B},
            {Opcode.SMSG_QUEST_UPDATE_FAILED_TIMER, 0x09F8},
            {Opcode.SMSG_QUEST_CONFIRM_ACCEPT, 0x09D1},
            {Opcode.SMSG_QUEST_FORCE_REMOVED, 0x0D76},
            {Opcode.SMSG_QUEST_NPC_QUERY_RESPONSE, 0x0A2E},
            {Opcode.SMSG_QUEST_POI_QUERY_RESPONSE, 0x0950},
            {Opcode.SMSG_QUERY_QUEST_INFO_RESPONSE, 0x0D5D},
            {Opcode.SMSG_RAID_GROUP_ONLY, 0x0DA4},
            {Opcode.SMSG_RAID_INSTANCE_INFO, 0x0F3B},
            {Opcode.SMSG_RAID_INSTANCE_MESSAGE, 0x0D0E},
            {Opcode.SMSG_RAID_MARKERS_CHANGED, 0x0BAA},
            {Opcode.SMSG_READY_CHECK_COMPLETED, 0x0A13},
            {Opcode.SMSG_READY_CHECK_RESPONSE, 0x0BDE},
            {Opcode.SMSG_READY_CHECK_STARTED, 0x0F28},
            //{Opcode.SMSG_READY_CHECK_THROTTLED_ERROR, 0x0}, // 0x2607 in 4.3.4 @todo : Find me and BACON !
            {Opcode.SMSG_RAID_SUMMON_FAILED, 0x0A4E},
            {Opcode.SMSG_SEND_RAID_TARGET_UPDATE_ALL, 0x0B9E},
            {Opcode.SMSG_SEND_RAID_TARGET_UPDATE_SINGLE, 0x0F13},
            {Opcode.SMSG_GENERATE_RANDOM_CHARACTER_NAME_RESULT, 0x0A9B},
            {Opcode.SMSG_RATED_BG_RATING, 0x0A4B},
            {Opcode.SMSG_INSPECT_RATED_BG_STATS, 0x0B21},
            {Opcode.SMSG_READ_ITEM_RESULT_FAILED, 0x086D},
            {Opcode.SMSG_READ_ITEM_RESULT_OK, 0x0D80},
            {Opcode.SMSG_REALM_QUERY_RESPONSE, 0x0C26},
            {Opcode.SMSG_REALM_SPLIT, 0x0CCD},
            //{Opcode.SMSG_REAL_GROUP_UPDATE, 0x0000}, Deprecated
            {Opcode.SMSG_RECEIVED_MAIL, 0x08D7},
            //{Opcode.SMSG_REDIRECT_CLIENT, 0x0423},
            {Opcode.SMSG_REFER_A_FRIEND_EXPIRED, 0x0C01},
            {Opcode.SMSG_REFER_A_FRIEND_FAILURE, 0x08C5},
            {Opcode.SMSG_REFORGE_RESULT, 0x0BA6},
            {Opcode.SMSG_SPELL_REMOVED_LOG, 0x0BB0},
            {Opcode.SMSG_REPORT_PVP_AFK_RESULT, 0x0897},
            {Opcode.SMSG_REQUEST_CEMETERY_LIST_RESPONSE, 0x0BB7},
            {Opcode.SMSG_REQUEST_PVP_REWARDS_RESPONSE, 0x0E30},
            {Opcode.SMSG_RESEARCH_COMPLETE, 0x0BF3},
            {Opcode.SMSG_SETUP_RESEARCH_HISTORY, 0x0BF1},
            {Opcode.SMSG_RESET_COMPRESSION_CONTEXT, 0x0627},
            {Opcode.SMSG_RESET_FAILED_NOTIFY, 0x0D3E},
            //{Opcode.SMSG_RESISTLOG, 0x0}, // Not found in 4.3.4
            {Opcode.SMSG_RESPEC_WIPE_CONFIRM, 0x0E83},
            {Opcode.SMSG_RESPOND_INSPECT_ACHIEVEMENTS, 0x0E4C},
            {Opcode.SMSG_RESURRECT_REQUEST, 0x0966},
            {Opcode.SMSG_RESYNC_RUNES, 0x0C05},
            //{Opcode.SMSG_ROLE_POLL_BEGIN, 0x0}, // 0x70B0 in 4.3.4 @todo : Find me and BACON !
            {Opcode.SMSG_RWHOIS, 0x0DCA},
            {Opcode.SMSG_SELL_ITEM, 0x0C76},
            {Opcode.SMSG_SEND_KNOWN_SPELLS, 0x0EA3},
            //{Opcode.SMSG_SEND_MAIL_RESULT, 0x0A4F},
            {Opcode.SMSG_SEND_UNLEARN_SPELLS, 0x0FD7},
            {Opcode.SMSG_SERVER_TIME, 0x0999},
            {Opcode.SMSG_SERVER_FIRST_ACHIEVEMENT, 0x08A6},
            {Opcode.SMSG_SERVER_INFO_RESPONSE, 0x0A5C},
            //{Opcode.SMSG_SERVER_MESSAGE, 0x0962},
            {Opcode.SMSG_SERVER_PERF, 0x0E8D},
            //{Opcode.SMSG_SETUP_RESEARCH_HISTORY, 0x0}, // Not found in TC
            //{Opcode.SMSG_SET_AI_ANIM_KIT, 0x0}, // Not found in 4.3.4
            {Opcode.SMSG_SET_DF_FAST_LAUNCH_RESULT, 0x0E54},
            {Opcode.SMSG_SET_FACTION_AT_WAR, 0x0DD2},
            {Opcode.SMSG_SET_FACTION_STANDING, 0x0C64},
            {Opcode.SMSG_SET_FACTION_VISIBLE, 0x0D20},
            {Opcode.SMSG_SET_FLAT_SPELL_MODIFIER, 0x0C74},
            {Opcode.SMSG_SET_FORCED_REACTIONS, 0x0DE0},
            //{Opcode.SMSG_SET_MELEE_ANIM_KIT, 0x0}, // Not found in 4.3.4
            //{Opcode.SMSG_SET_MOVEMENT_ANIM_KIT, 0x0}, // Not found in 4.3.4
            {Opcode.SMSG_SET_PCT_SPELL_MODIFIER, 0x0802},
            {Opcode.SMSG_SET_PET_SPECIALIZATION, 0x0E17},
            {Opcode.SMSG_SET_PLAYER_DECLINED_NAMES_RESULT, 0x0D26},
            {Opcode.SMSG_SET_PLAY_HOVER_ANIM, 0x0E84},
            {Opcode.SMSG_SET_PROFICIENCY, 0x0823},
            {Opcode.SMSG_SET_PROJECTILE_POSITION, 0x08BC},
            {Opcode.SMSG_SHOW_TAXI_NODES, 0x0D49},
            {Opcode.SMSG_SHOW_BANK, 0x09C8},
            {Opcode.SMSG_SHOW_NEUTRAL_PLAYER_FACTION_SELECT_UI, 0x0AC0},
            {Opcode.SMSG_SHOW_RATINGS, 0x0B99},
            {Opcode.SMSG_SOR_START_EXPERIENCE_INCOMPLETE, 0x0AB4},
            {Opcode.SMSG_SPELL_BREAK_LOG, 0x0C45},
            {Opcode.SMSG_SPELL_DAMAGE_SHIELD, 0x0DA5},
            {Opcode.SMSG_SPELL_DISPELL_LOG, 0x0931},
            {Opcode.SMSG_SPELL_ENERGIZE_LOG, 0x09C0},
            {Opcode.SMSG_SPELL_HEAL_LOG, 0x0890},
            {Opcode.SMSG_SPELL_INSTAKILL_LOG, 0x0C56},
            {Opcode.SMSG_SPELL_INTERRUPT_LOG, 0x0F8A},
            {Opcode.SMSG_SPELL_EXECUTE_LOG, 0x0C72},
            {Opcode.SMSG_SPELL_MISS_LOG, 0x0854},
            {Opcode.SMSG_SPELL_NON_MELEE_DAMAGE_LOG, 0x09F4},
            {Opcode.SMSG_SPELL_OR_DAMAGE_IMMUNE, 0x0},
            {Opcode.SMSG_SPELL_STEAL_LOG, 0x0DAC},
            {Opcode.SMSG_SPELL_CATEGORY_COOLDOWN, 0x0F25},
            {Opcode.SMSG_SPELL_COOLDOWN, 0x0D75},
            {Opcode.SMSG_SPELL_DELAYED, 0x0C17},
            {Opcode.SMSG_SPELL_FAILED_OTHER, 0x0C0E},
            {Opcode.SMSG_SPELL_FAILURE, 0x0D93},
            {Opcode.SMSG_SPELL_GO, 0x0D42},
            {Opcode.SMSG_SPELL_START, 0x08FC},
            {Opcode.SMSG_SPELL_UPDATE_CHAIN_TARGETS, 0x0858},
            {Opcode.SMSG_SPIRIT_HEALER_CONFIRM, 0x0C7F},
            {Opcode.SMSG_SPLINE_MOVE_COLLISION_DISABLE, 0x0E81},
            {Opcode.SMSG_SPLINE_MOVE_COLLISION_ENABLE, 0x0E12},
            {Opcode.SMSG_SPLINE_MOVE_GRAVITY_DISABLE, 0x0E2B},
            {Opcode.SMSG_SPLINE_MOVE_GRAVITY_ENABLE, 0x0A56},
            {Opcode.SMSG_SPLINE_MOVE_ROOT, 0x0FAA},
            {Opcode.SMSG_SPLINE_MOVE_SET_FEATHER_FALL, 0x0BD5},
            {Opcode.SMSG_SPLINE_MOVE_SET_FLIGHT_BACK_SPEED, 0x0E8E},
            {Opcode.SMSG_SPLINE_MOVE_SET_FLIGHT_SPEED, 0x0E5D},
            {Opcode.SMSG_SPLINE_MOVE_SET_FLYING, 0x0E95},
            {Opcode.SMSG_SPLINE_MOVE_SET_HOVER, 0x0A90},
            {Opcode.SMSG_SPLINE_MOVE_SET_LAND_WALK, 0x0A49},
            {Opcode.SMSG_SPLINE_MOVE_SET_NORMAL_FALL, 0x0F42},
            {Opcode.SMSG_SPLINE_MOVE_SET_PITCH_RATE, 0x0E82},
            {Opcode.SMSG_SPLINE_MOVE_SET_RUN_BACK_SPEED, 0x0A10},
            {Opcode.SMSG_SPLINE_MOVE_SET_RUN_MODE, 0x0A9A},
            {Opcode.SMSG_SPLINE_MOVE_SET_RUN_SPEED, 0x0A9C},
            {Opcode.SMSG_SPLINE_MOVE_SET_SWIM_BACK_SPEED, 0x0FC3},
            {Opcode.SMSG_SPLINE_MOVE_SET_SWIM_SPEED, 0x0FAD},
            {Opcode.SMSG_SPLINE_MOVE_SET_TURN_RATE, 0x0A44},
            {Opcode.SMSG_SPLINE_MOVE_SET_WALK_MODE, 0x0A2C},
            {Opcode.SMSG_SPLINE_MOVE_SET_WALK_SPEED, 0x0B8F},
            {Opcode.SMSG_SPLINE_MOVE_SET_WATER_WALK, 0x0B69},
            {Opcode.SMSG_SPLINE_MOVE_START_SWIM, 0x0EEE},
            {Opcode.SMSG_SPLINE_MOVE_STOP_SWIM, 0x0E0B},
            {Opcode.SMSG_SPLINE_MOVE_UNROOT, 0x0AAC},
            {Opcode.SMSG_SPLINE_MOVE_UNSET_FLYING, 0x0EB1},
            {Opcode.SMSG_SPLINE_MOVE_UNSET_HOVER, 0x0BC0},
            {Opcode.SMSG_SPLINE_MOVE_WATER_WALK, 0x0B69},
            {Opcode.SMSG_STABLE_RESULT, 0x08F5},
            {Opcode.SMSG_STAND_STATE_UPDATE, 0x08BB},
            {Opcode.SMSG_START_MIRROR_TIMER, 0x0CA9},
            {Opcode.SMSG_START_TIMER, 0x0EBA},
            {Opcode.SMSG_STOP_DANCE, 0x09B5},
            {Opcode.SMSG_STOP_MIRROR_TIMER, 0x0D64},
            {Opcode.SMSG_STREAMING_MOVIES, 0x0B4C},
            {Opcode.SMSG_SUMMON_CANCEL, 0x0CD0},
            {Opcode.SMSG_SUMMON_REQUEST, 0x082D},
            {Opcode.SMSG_SUPERCEDED_SPELLS, 0x0A6B},
            {Opcode.SMSG_SUPPRESS_NPC_GREETINGS, 0x0A2A},
            {Opcode.SMSG_SUSPEND_COMMS, 0x0662},
            {Opcode.SMSG_SUSPEND_TOKEN, 0x0B4F},
            {Opcode.SMSG_TALENTS_INVOLUNTARILY_RESET, 0x09E1},
            {Opcode.SMSG_TAXI_NODE_STATUS, 0x0DC4},
            //{Opcode.SMSG_TEST_DROP_RATE_RESULT, 0x0000}, //Unused
            {Opcode.SMSG_TEXT_EMOTE, 0x0880},
            {Opcode.SMSG_THREAT_CLEAR, 0x0C9B},
            {Opcode.SMSG_THREAT_REMOVE, 0x09BF},
            {Opcode.SMSG_THREAT_UPDATE, 0x0DB0},
            {Opcode.SMSG_TIME_ADJUSTMENT, 0x0F3A},
            {Opcode.SMSG_TIME_SYNC_REQUEST, 0x0AA9},
            {Opcode.SMSG_TITLE_EARNED, 0x094B},
            {Opcode.SMSG_TOGGLE_XP_GAIN, 0x0D62},
            {Opcode.SMSG_TOTEM_CREATED, 0x0918},
            {Opcode.SMSG_TRADE_STATUS, 0x0F85},
            {Opcode.SMSG_TRADE_STATUS_EXTENDED, 0x0AFB},
            //{Opcode.SMSG_TRAINER_BUY_SUCCEEDED, 0x0D31}, //removed in commit c041875
            {Opcode.SMSG_TRAINER_LIST, 0x0C65},
            //{Opcode.SMSG_TRAINER_SERVICE, 0x0D31},
            {Opcode.SMSG_TRANSFER_ABORTED, 0x0889},
            {Opcode.SMSG_TRANSFER_PENDING, 0x0F79},
            {Opcode.SMSG_TRIGGER_CINEMATIC, 0x0C18},
            {Opcode.SMSG_TRIGGER_MOVIE, 0x0D51},
            {Opcode.SMSG_TURN_IN_PETITION_RESULT, 0x0D7B},
            {Opcode.SMSG_TUTORIAL_FLAGS, 0x08AE},
            {Opcode.SMSG_UNIT_HEALTH_FREQUENT, 0x08D1},
            {Opcode.SMSG_UNIT_SPELLCAST_START, 0x0C12},
            {Opcode.SMSG_UPDATE_ACCOUNT_DATA, 0x0860},
            {Opcode.SMSG_UPDATE_ACCOUNT_DATA_COMPLETE, 0x0D35},
            {Opcode.SMSG_UPDATE_COMBO_POINTS, 0x09A5},
            {Opcode.SMSG_UPDATE_CURRENCY, 0x0E55},
            {Opcode.SMSG_UPDATE_CURRENCY_WEEK_LIMIT, 0x0AEA},
            {Opcode.SMSG_UPDATE_DUNGEON_ENCOUNTER_FOR_LOOT, 0x0A53},
            {Opcode.SMSG_UPDATE_INSTANCE_ENCOUNTER_UNIT, 0x0CA3},
            {Opcode.SMSG_UPDATE_INSTANCE_OWNERSHIP, 0x0C8C},
            //{Opcode.SMSG_UPDATE_ITEM_ENCHANTMENTS, 0x098E},
            {Opcode.SMSG_UPDATE_LAST_INSTANCE, 0x0DDC},
            {Opcode.SMSG_UPDATE_OBJECT, 0x08F7},
            {Opcode.SMSG_UPDATE_SERVER_PLAYER_POSITION, 0x0E1B}, // 0x74A3  in 4.3.4 @todo find me 
            {Opcode.SMSG_UPDATE_TALENT_DATA, 0x0CEC},
            {Opcode.SMSG_UPDATE_WORLD_STATE, 0x0847},
            {Opcode.SMSG_USERLIST_ADD, 0x095A},
            {Opcode.SMSG_USERLIST_REMOVE, 0x0D6E},
            {Opcode.SMSG_USERLIST_UPDATE, 0x095A},
            {Opcode.SMSG_VOICESESSION_FULL, 0x0CA6},
            {Opcode.SMSG_VOICE_CHAT_STATUS, 0x09EE},
            {Opcode.SMSG_VOICE_PARENTAL_CONTROLS, 0x0CF0},
            {Opcode.SMSG_VOICE_SESSION_LEAVE, 0x085D},
            {Opcode.SMSG_VOICE_SESSION_ROSTER_UPDATE, 0x0CCE},
            {Opcode.SMSG_VOICE_SET_TALKER_MUTED, 0x097B},
            {Opcode.SMSG_VOID_ITEM_SWAP_RESPONSE, 0x0FB1},
            {Opcode.SMSG_VOID_STORAGE_CONTENTS, 0x0E85},
            {Opcode.SMSG_VOID_STORAGE_FAILED, 0x0F40},
            {Opcode.SMSG_VOID_STORAGE_TRANSFER_CHANGES, 0x0BD9},
            {Opcode.SMSG_VOID_TRANSFER_RESULT, 0x0E02},
            {Opcode.SMSG_WAIT_QUEUE_FINISH, 0x0F17},
            {Opcode.SMSG_WAIT_QUEUE_UPDATE, 0x0AC8},
            {Opcode.SMSG_WARDEN_DATA, 0x0EA8},
            {Opcode.SMSG_WARGAME_CHECK_ENTRY, 0x0BE6},
            {Opcode.SMSG_WARGAME_REQUEST_SENT, 0x0F48},
            {Opcode.SMSG_WEATHER, 0x0814},
            {Opcode.SMSG_WEEKLY_LAST_RESET, 0x0B2D},
            {Opcode.SMSG_WEEKLY_RESET_CURRENCY, 0x0EBB},
            {Opcode.SMSG_WEEKLY_SPELL_USAGE, 0x0B6D}, //unused
            {Opcode.SMSG_WEEKLY_SPELL_USAGE_UPDATE, 0x0B6D}, //unused
            {Opcode.SMSG_WHO, 0x0933},
            {Opcode.SMSG_WHO_IS, 0x0943},
            {Opcode.SMSG_WORLD_SERVER_INFO, 0x0A6D},
            //{Opcode.SMSG_WORLD_STATE_UI_TIMER_UPDATE, 0x0D83},
            {Opcode.SMSG_XP_GAIN_ABORTED, 0x0B76},
            {Opcode.SMSG_ZONE_UNDER_ATTACK, 0x08BD},
        };

        private static readonly BiDictionary<Opcode, int> MiscOpcodes = new BiDictionary<Opcode, int>
        {
            {Opcode.MSG_AUCTION_HELLO, 0x08DF},
            //{Opcode.MSG_BATTLEGROUND_PLAYER_POSITIONS, 0x0000}, //deprecated
            {Opcode.MSG_CHANNEL_START, 0x0831},
            {Opcode.MSG_CHANNEL_UPDATE, 0x08ED},
            //{Opcode.MSG_GM_BIND_OTHER, 0x0000}, // Not found in 4.3.4
            //{Opcode.MSG_GM_SHOWLABEL, 0x0000}, // Not found in 4.3.4
            //{Opcode.MSG_GM_SUMMON, 0x0000}, // Not found in 4.3.4
            {Opcode.MSG_INSPECT_ARENA_TEAMS, 0x0C75},
            {Opcode.MSG_LIST_STABLED_PETS, 0x0D91},
            {Opcode.MSG_MINIMAP_PING, 0x0808},
            {Opcode.MSG_MOVE_STOP, 0x0455}, //Used ?
            {Opcode.MSG_MOVE_TELEPORT, 0x0A95}, //Used ?
            {Opcode.MSG_MOVE_TELEPORT_ACK, 0x069D}, //Used ?
            {Opcode.MSG_MOVE_TELEPORT_CHEAT, 0x0A95}, //Used ?
            {Opcode.MSG_MOVE_TIME_SKIPPED, 0x0A52}, //Used ?
            {Opcode.MSG_MOVE_WORLDPORT_ACK, 0x03F6}, //Used ?
            {Opcode.MSG_PETITION_DECLINE, 0x0901},
            {Opcode.MSG_PETITION_RENAME, 0x0D53},
            {Opcode.MSG_QUERY_NEXT_MAIL_TIME, 0x097C},
            {Opcode.MSG_QUEST_PUSH_RESULT, 0x0939},
            {Opcode.MSG_RANDOM_ROLL, 0x0EDB},
            {Opcode.MSG_SAVE_GUILD_EMBLEM, 0x0C3D},
            {Opcode.MSG_SET_DUNGEON_DIFFICULTY, 0x0D24},
            {Opcode.MSG_SET_RAID_DIFFICULTY, 0x0957},
            {Opcode.MSG_TABARDVENDOR_ACTIVATE, 0x0C1D},

            {Opcode.MSG_VERIFY_CONNECTIVITY, 0x04F57},
        };
    }
}
