namespace WowPacketParser.Enums
{
    public enum GMTicketResponse
    {
        GMTICKET_RESPONSE_ALREADY_EXIST = 1,
        GMTICKET_RESPONSE_CREATE_SUCCESS = 2,
        GMTICKET_RESPONSE_CREATE_ERROR = 3,
        GMTICKET_RESPONSE_UPDATE_SUCCESS = 4,
        GMTICKET_RESPONSE_UPDATE_ERROR = 5,
        GMTICKET_RESPONSE_TICKET_DELETED = 9
    }
}
